### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by michaeleisel** [DataDog/datadog-agent#10052]
**Describe what happened:**

When running a lambda in AWS, with the JS runtime, using `datadog-lambda-js` at version 4.62.0, I occasionally see this crash:

```
panic: assignment to entry in nil map
--
  | 2021-11-30T16:12:05.380-05:00 |  
  | 2021-11-30T16:12:05.380-05:00 | goroutine 120 [running]:
  | 2021-11-30T16:12:05.380-05:00 | github.com/DataDog/datadog-agent/pkg/aggregator.sketchMap.getOrCreate(...)
  | 2021-11-30T16:12:05.380-05:00 | /tmp/dd/datadog-agent/pkg/aggregator/sketch_map.go:63
  | 2021-11-30T16:12:05.380-05:00 | github.com/DataDog/datadog-agent/pkg/aggregator.sketchMap.insert(0xc00048d9b0, 0x61a692f6, 0xe6c64b18bbb2ce10, 0x3f179a0bf9bb6a07, 0x3ff0000000000000, 0x1)
  | 2021-11-30T16:12:05.380-05:00 | /tmp/dd/datadog-agent/pkg/aggregator/sketch_map.go:34 +0x15a
  | 2021-11-30T16:12:05.380-05:00 | github.com/DataDog/datadog-agent/pkg/aggregator.(*TimeSampler).addSample(0xc000380cc0, 0xc0000b1e80, 0x41d869a4bfdbb645)
  | 2021-11-30T16:12:05.380-05:00 | /tmp/dd/datadog-agent/pkg/aggregator/time_sampler.go:63 +0x116
  | 2021-11-30T16:12:05.380-05:00 | github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).addSample(...)
  | 2021-11-30T16:12:05.380-05:00 | /tmp/dd/datadog-agent/pkg/aggregator/aggregator.go:448
  | 2021-11-30T16:12:05.380-05:00 | github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).run(0xc000380c60)
  | 2021-11-30T16:12:05.380-05:00 | /tmp/dd/datadog-agent/pkg/aggregator/aggregator.go:773 +0xaac
  | 2021-11-30T16:12:05.380-05:00 | created by github.com/DataDog/datadog-agent/pkg/aggregator.InitAggregatorWithFlushInterval.func1
  | 2021-11-30T16:12:05.380-05:00 | /tmp/dd/datadog-agent/pkg/aggregator/aggregator.go:187 +0x97
```

What might be the issue?

**Steps to reproduce the issue:**

This is a flaky failure, it only happens occasionally

**Additional environment details (Operating System, Cloud provider, etc):**

AWS Lambda (JS runtime)

**Comment by djmitche** [comment]
What agent version is running?

**Comment by maxday** [comment]
Thanks for raising this issue, this has been fixed, you can upgrade to v16 : https://github.com/DataDog/datadog-lambda-extension/releases
