### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by liranms** [DataDog/datadog-agent#10372]
Occationally we get this panic:
```
E1229 05:33:43.356589       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 351 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x31d9960, 0x5492330)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/runtime/runtime.go:48 +0x86
panic(0x31d9960, 0x5492330)
    /goroot/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/pkg/mod/k8s.io/client-go@v0.20.11/tools/cache/shared_informer.go:774 +0x194
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00006bf60)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000e51f60, 0x3be8760, 0xc0007d2d80, 0x3164101, 0xc0005cad80)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00006bf60, 0x3b9aca00, 0x0, 0x1, 0xc0005cad80)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0007ec000)
    /go/pkg/mod/k8s.io/client-go@v0.20.11/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0009480d0, 0xc000874900)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x17383d4]
goroutine 351 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/runtime/runtime.go:55 +0x109
panic(0x31d9960, 0x5492330)
    /goroot/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/pkg/mod/k8s.io/client-go@v0.20.11/tools/cache/shared_informer.go:774 +0x194
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00006bf60)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000e51f60, 0x3be8760, 0xc0007d2d80, 0x3164101, 0xc0005cad80)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00006bf60, 0x3b9aca00, 0x0, 0x1, 0xc0005cad80)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0007ec000)
    /go/pkg/mod/k8s.io/client-go@v0.20.11/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0009480d0, 0xc000874900)
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/pkg/mod/k8s.io/apimachinery@v0.20.11/pkg/util/wait/wait.go:71 +0x65

```

Agent version is 1.16.0 (gcr.io/datadoghq/cluster-agent:1.16.0)

**Comment by smitthakkar96** [comment]
We are also facing this, can we please prioritise investigation and fix on this.

**Comment by grzn** [comment]
@paulcacheux @djmitche @davidor @KSerrania @juliogreff @safchain, sorry for mentioning you directly, but can someone please take a look at this? we've submitted this issue 3 weeks ago... and the containers keep panic'ing several times a day...

**Comment by jacobdr** [comment]
Also seeing this, support ticket is https://help.datadoghq.com/hc/en-us/requests/715448?page=1

**Comment by rbarabas** [comment]
Same, support ticket http://help.datadoghq.com/hc/requests/712121

**Comment by Temikus** [comment]
Same, support ticket: https://help.datadoghq.com/hc/en-us/requests/820598

We suspect this change introduced from 1.15.1 --> 1.16 cluster agent where there was an attempt to fix stale informer...  

Our suspicion is a race condition with informer sync causing the segfault in a perfect storm scenario --> https://github.com/DataDog/datadog-agent/pull/9464

The following log messages seem to corroborate incorrect use of factory methods:

```
E0527 22:36:52.760835       1 shared_informer.go:781] unrecognized notification: <nil>
```

, see: https://github.com/kubernetes/client-go/issues/991
