### ISSUE TITLE
dockerExtractEnvironmentVariables and empty variables

### ISSUE THREAD

**Issue by marczahn** [DataDog/datadog-agent#1106]
## Problem:
When I run datadog-agent 6.0.0-beta.8 I get this output:
```
sudo datadog-agent start -c /etc/datadog-agent/datadog.yaml
2018-01-25 17:03:18 CET | INFO | (start.go:149 in StartAgent) | Starting Datadog Agent v6.0.0-beta.8
2018-01-25 17:03:18 CET | INFO | (start.go:167 in StartAgent) | Hostname is: marczahn-ThinkPad-T540p
2018-01-25 17:03:18 CET | INFO | (start.go:177 in StartAgent) | GUI server port -1 specified: not starting the GUI.
2018-01-25 17:03:18 CET | INFO | (forwarder.go:228 in Start) | DefaultForwarder started (4 workers), sending to 1 endpoint(s): "https://6-0-0-app.agent.datadoghq.com" (1 api key(s))
2018-01-25 17:03:18 CET | INFO | (udp.go:63 in Listen) | dogstatsd-udp: starting to listen on 127.0.0.1:8125
2018-01-25 17:03:18 CET | ERROR | (start.go:213 in StartAgent) | Could not start logs-agent: Could not find any valid logs integration configuration file in /etc/datadog-agent/conf.d
2018-01-25 17:03:18 CET | INFO | (tagger.go:80 in Init) | starting the tagging system
2018-01-25 17:03:18 CET | INFO | (tagger.go:153 in tryCollectors) | docker tag collector successfully started
2018-01-25 17:03:19 CET | ERROR | (auth.go:23 in GetAuthToken) | Could not read token from /var/run/secrets/kubernetes.io/serviceaccount/token: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2018-01-25 17:03:19 CET | INFO | (runner.go:93 in NewRunner) | Runner started with 4 workers.
2018-01-25 17:03:19 CET | INFO | (collector.go:51 in NewCollector) | Embedding Python 2.7.14 (default, Jan 10 2018, 22:30:29) [GCC 4.7.2]
2018-01-25 17:03:19 CET | INFO | (file.go:68 in Collect) | File Configuration Provider: searching for configuration files at: /etc/datadog-agent/conf.d
2018-01-25 17:03:19 CET | INFO | (file.go:68 in Collect) | File Configuration Provider: searching for configuration files at: /opt/datadog-agent/bin/agent/dist/conf.d
2018-01-25 17:03:19 CET | WARN | (file.go:72 in Collect) | Skipping, open /opt/datadog-agent/bin/agent/dist/conf.d: no such file or directory
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for apache at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for consul at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for couch at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for couchbase at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for elastic at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for etcd at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for kube_dns at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for kubernetes_state at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for kyototycoon at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for mcache at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for redisdb at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:288 in resolve) | Can't resolve the template for riak at this moment.
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'apm'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'cpu'
2018-01-25 17:03:19 CET | WARN | (check.go:243 in Configure) | could not get a check instance with the new api: __init__() takes at least 4 arguments (4 given)
2018-01-25 17:03:19 CET | WARN | (check.go:244 in Configure) | trying to instantiate the check with the old api, passing agentConfig to the constructor
2018-01-25 17:03:19 CET | WARN | (check.go:269 in Configure) | passing `agentConfig` to the constructor is deprecated, please use the `get_config` function from the 'datadog_agent' package (disk).
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Python Check Loader: successfully loaded check 'disk'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'file_handle'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'io'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'load'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'memory'
2018-01-25 17:03:19 CET | WARN | (check.go:243 in Configure) | could not get a check instance with the new api: __init__() takes at least 4 arguments (4 given)
2018-01-25 17:03:19 CET | WARN | (check.go:244 in Configure) | trying to instantiate the check with the old api, passing agentConfig to the constructor
2018-01-25 17:03:19 CET | WARN | (check.go:269 in Configure) | passing `agentConfig` to the constructor is deprecated, please use the `get_config` function from the 'datadog_agent' package (network).
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Python Check Loader: successfully loaded check 'network'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'ntp'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'process_agent'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:458 in GetChecks) | Core Check Loader: successfully loaded check 'uptime'
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check APM Agent
2018-01-25 17:03:19 CET | INFO | (scheduler.go:214 in enqueueOnce) | Scheduling check APM Agent for one-time execution
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check cpu
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check cpu with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check disk
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check disk with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check file_handle
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check file_handle with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check io
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check io with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check load
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check load with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check memory
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check memory with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check network
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check network with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check ntp
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check ntp with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check Process Agent
2018-01-25 17:03:19 CET | INFO | (scheduler.go:214 in enqueueOnce) | Scheduling check Process Agent for one-time execution
2018-01-25 17:03:19 CET | INFO | (autoconfig.go:254 in schedule) | Scheduling check uptime
2018-01-25 17:03:19 CET | INFO | (scheduler.go:71 in Enter) | Scheduling check uptime with an interval of 15s
2018-01-25 17:03:19 CET | INFO | (runner.go:134 in UpdateNumWorkers) | Added 6 workers to runner: now at 10 workers.
2018-01-25 17:03:19 CET | INFO | (runner.go:242 in work) | Running check APM Agent
2018-01-25 17:03:19 CET | INFO | (runner.go:242 in work) | Running check Process Agent
2018-01-25 17:03:19 CET | INFO | (process_agent.go:64 in run) | Not running process_agent because 'enabled' is false in init_config
2018-01-25 17:03:19 CET | INFO | (runner.go:298 in work) | Done running check Process Agent
2018-01-25 17:03:19 CET | INFO | (apm.go:83 in func1) | 2018-01-25 17:03:19 INFO (agent.go:142) - error retrieving dd-agent hostname, falling back to os.Hostname(): exit status 1
2018-01-25 17:03:19 CET | INFO | (apm.go:83 in func1) | 2018-01-25 17:03:19 INFO (agent.go:82) - overriding hostname from env DD_HOSTNAME value
2018-01-25 17:03:19 CET | INFO | (apm.go:83 in func1) | 2018-01-25 17:03:19 INFO (agent.go:87) - overriding API key from env API_KEY value
2018-01-25 17:03:19 CET | INFO | (apm.go:83 in func1) | 2018-01-25 17:03:19 INFO (main.go:210) - trace-agent running on host marczahn-ThinkPad-T540p
2018-01-25 17:03:19 CET | INFO | (apm.go:83 in func1) | 2018-01-25 17:03:19 INFO (receiver.go:142) - listening for traces at http://localhost:8126
2018-01-25 17:03:19 CET | INFO | (cloudfoundry.go:20 in GetHostAlias) | cloud_foundry is not enable in the conf: not cloudfoudry host alias
2018-01-25 17:03:20 CET | INFO | (serializer.go:180 in SendMetadata) | Sent host metadata payload, size: 6629 bytes.
2018-01-25 17:03:20 CET | INFO | (transaction.go:133 in Process) | Successfully posted payload to "https://6-0-0-app.agent.datadoghq.com/intake/?api_key=*************************40494", the agent will only log transaction success every 20 transactions
panic: runtime error: index out of range

goroutine 110 [running]:
github.com/DataDog/datadog-agent/pkg/tagger/collectors.dockerExtractEnvironmentVariables(0xc420785c60, 0xc420247dc0, 0x16, 0x1c, 0xc420077ef0)
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/docker_extract.go:87 +0x6de
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*DockerCollector).extractFromInspect(0xc4204b5890, 0xc4200a3340, 0x1d537b8, 0x0, 0x0, 0xc4203ce000, 0xc42030c200, 0x0, 0xc4203ce000, 0xc42030c200, ...)
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/docker_extract.go:32 +0x242
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*DockerCollector).fetchForDockerID(0xc4204b5890, 0xc4203cc1c0, 0x40, 0xc42000e090, 0x1, 0x1, 0xc420549f18, 0x3, 0x3, 0xc420549fa8, ...)
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/docker_main.go:114 +0x2d8
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*DockerCollector).processEvent(0xc4204b5890, 0xc420178480)
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/docker_main.go:101 +0x129
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*DockerCollector).Stream(0xc4204b5890, 0x7f55a40600b0, 0xc4204b5890)
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/docker_main.go:68 +0x9f
created by github.com/DataDog/datadog-agent/pkg/tagger.(*Tagger).registerCollectors
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/tagger.go:185 +0x436
```
When I look at this place in the code: https://github.com/DataDog/datadog-agent/blob/6.0.0-beta.8/pkg/tagger/collectors/docker_extract.go#L87
It seems that there is a string which does not contain a "=". Unfortunately I do not see which one.

The problem occurs only when I install datadog-agent via apt-get (Instructions from your website). When I check the code out and run it manually I cannot reproduce it.

I would like to use version 6 since we want to check out the logs.

**Comment by xvello** [comment]
Hi @marczahn 

Very sorry for that bug. we identified and fixed it in https://github.com/DataDog/datadog-agent/pull/1040, this is probably why you cannot reproduce it from master.

We are putting the finishing touches on `beta9` that will ship this fix. It should be out in a couple of days. In the meantime, could you try with `datadog/agent-dev:master` to make sure it addresses your issue?

**Comment by marczahn** [comment]
Hi @xvello 

Thank you for this quick response. I did as you said and it is working fine now. But there is one thing left and I do not find the problem. Every call of the logger seems to produce this error message:

```
...
2018-01-26 08:52:43 CET | INFO | (runner.go:298 in work) | Done running check uptime, next runs will be logged every 20 runs
*seelog.formattedWriterseelog internal error: invalid argument
2018-01-26 08:52:43 CET | INFO | (runner.go:242 in work) | Running check ntp
*seelog.formattedWriterseelog internal error: invalid argument
2018-01-26 08:52:43 CET | INFO | (runner.go:298 in work) | Done running check memory, next runs will be logged every 20 runs
*seelog.formattedWriterseelog internal error: invalid argument
...
```

**Comment by xvello** [comment]
I used to get this error when we cannot write to `/var/log/datadog/`.
Can you please parse your deployment command, to see if any option would be causing this? Are you running on a read-only volume, or non-root?

**Comment by marczahn** [comment]
Hi,

the problem has been solved with a newer build meanwhile.
