### ISSUE TITLE
How to use the DD_API_KEY from environment

### ISSUE THREAD

**Issue by SebastianBalle** [DataDog/datadog-agent#11153]
## Describe what happened

Instead of writing `api_key` to `/etc/datadog-agent/datadog.yaml` we would like to source this from the environment variable `DD_API_KEY`.

We have a Dockerfile (simplified) which installs the Datadog Agent using the official `install_dd.sh` provided from within Datadog. We remove the configuration file `/etc/datadog-agent/datadog.yaml` as we want to inject this file with the correct values in our `start.sh` script. `DD_API_KEY` is available in the context of executing the `start.sh`, however the variable does not seem to set correctly as the following error is returned:

```sh
ERROR:ddtrace.internal.writer:failed to send traces to Datadog Agent at http://localhost:8126/v0.4/traces
```

If we write the `api_key` in the `/etc/datadog-agent/datadog.yaml` the information are send succesfully. It seems like [preivous cases](https://github.com/DataDog/datadog-agent/issues/3235) indicate that it was possible to use to `DD_API_KEY` from the environment.

## Details of setup

```Dockerfile
FROM condaforge/miniforge3:4.10.1-0

# Install datadog
COPY install_dd.sh install_dd.sh
RUN chmod u+x install_dd.sh && DD_API_KEY=placeholder DD_AGENT_MAJOR_VERSION=7 ./install_dd.sh
RUN rm -rf /etc/datadog-agent/datadog.yaml

# Set up directories
WORKDIR /app
COPY . /app

ENTRYPOINT ["/app/scripts/start.sh"]
```

```sh
#!/bin/sh

echo "Creating Datadog configuration"
cat <<EOT > /etc/datadog-agent/datadog.yaml
---
api_key: ${DD_API_KEY}
hostname: hostname
site: app.datadog.eu
EOT

echo "Restarting Datadog agent"
service datadog-agent restart
```

We would like to avoid writing secrets unencrypted to a YAML file stored on the filesystem of the machine running our application.

In <https://docs.datadoghq.com/agent/guide/environment-variables/> they say that

> Not all datadog.yaml options are available with environment variables.
>See config.go in the Datadog Agent GitHub repo. Options with environment variables start with config.BindEnv*.

There is api_key in
<https://github.com/DataDog/datadog-agent/blob/55e28c8c06e1e76d5668e07c7a3d8dc52569c057/pkg/config/config.go#L837>  so DD_API_KEY should read as an environment variable. However if I remove the `api_key`from the `/etc/datadog-agent/datadog.yaml` I get the following error. The Python library [ddtrace](https://github.com/DataDog/dd-trace-py) is used to send logs using the Datadog agent.

```sh
ERROR:ddtrace.internal.writer:failed to send traces to Datadog Agent at http://localhost:8126/v0.4/traces
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 412, in _send_payload
    response = self._put(payload, headers)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 371, in _put
    conn.request("PUT", self._endpoint, data, headers)
  File "/opt/conda/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/opt/conda/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/conda/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 525, in flush_queue
    self._retry_upload(self._send_payload, encoded, n_traces)
  File "/opt/conda/lib/python3.8/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/opt/conda/lib/python3.8/site-packages/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f7207010d90 state=finished raised ConnectionRefusedError>]
error: read tcp xx.xxx.xxx.xxx:xxxxx->xx.xx.x.xxx:xxx: read: connection reset by peer
```

## Describe what you expected

I expected that the Datadog agent could recognize the `DD_API_KEY` environment variable from the host machine but this does not seem to be the case. We do not want to install the Datadog agent with secrets in the image.

## Steps to reproduce the issue

See above configurations. The test was made on Kubernetes. We are aware of the [official helm chart for Kubernetes](https://github.com/DataDog/helm-charts) but are only interested in testing the agent configurations. The intention is to run the Datadog alongside the application on a different setup.

## Additional environment details (Operating System, Cloud provider, etc)

We intent to install the Datadog agent on an Azure App Service, but the logging capabilities are more mature on Kubernetes hence the test is performed here.

**Comment by gtirloni** [comment]
When you don't set `api_key` in the datadog.yaml file, does the agent still listen on port 5000, 5001, 8125 and 8126? I'm asking this because the error is `connection refused` which seems to imply the app couldn't contact the agent iself (unrelated to actually contacting the DD server).

**Comment by SebastianBalle** [comment]
@gtirloni 
When I don't set `api_key` the agent listens on port 5000, 5001, and 8125 but not 8126. When I set the `api_key` and restart the service the agent listen also on port 8126.

**Comment by bronumski** [comment]
I'm having a similar issue trying to create a docker image hich uses the install script from:

https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh

```
RUN DD_INSTALL_ONLY=true \
    DD_API_KEY=dummy \
    DD_AGENT_MAJOR_VERSION=7 \
    DD_AGENT_MINOR_VERSION=39 \
    ./install_script.sh
 ```

Values defined in the datadog.yaml are respected but any `DD_` prefixed environment variable is ignored.
