### ISSUE TITLE
Missing metrics in `docker.containers.running`

### ISSUE THREAD

**Issue by renchap** [DataDog/datadog-agent#11610]
<details>
<summary>**Output of the info page (if this is a bug)**</summary>

```
datadog-agent status
Getting the status from the agent.

===============
Agent (v7.35.0)
===============

  Status date: 2022-04-08 20:27:37.681 UTC (1649449657681)
  Agent start: 2022-04-08 13:12:33.99 UTC (1649423553990)
  Pid: 3.263892e+06
  Go Version: go1.17.6
  Python Version: 3.8.11
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log File: /var/log/datadog/agent.log
  Log Level: INFO

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -1.413ms
    System time: 2022-04-08 20:27:37.681 UTC (1649449657681)

  Host Info
  =========
    bootTime: 2021-09-12 13:02:24 UTC (1631451744000)
    kernelArch: x86_64
    kernelVersion: 5.10.0-8-amd64
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 11.3
    procs: 149
    uptime: 4992h10m19s
    virtualizationRole: guest
    virtualizationSystem: kvm

  Hostnames
  =========
    hostname: 
    socket-fqdn: localhost
    socket-hostname: 
    host tags:
      docker_swarm_node_role:manager
    hostname provider: configuration

  Metadata
  ========
    agent_version: 7.35.0
    config_apm_dd_url:
    config_dd_url:
    config_logs_dd_url:
    config_logs_socks5_proxy_address:
    config_no_proxy: []
    config_process_dd_url: https://process.datadoghq.com
    config_proxy_http:
    config_proxy_https:
    config_site:
    feature_apm_enabled: true
    feature_cspm_enabled: false
    feature_cws_enabled: false
    feature_logs_enabled: true
    feature_networks_enabled: true
    feature_networks_http_enabled: false
    feature_networks_https_enabled: false
    feature_otlp_enabled: false
    feature_process_enabled: true
    feature_processes_container_enabled: false
    flavor: agent
    hostname_source: configuration
    install_method_installer_version: datadog_cookbook-4.12.0
    install_method_tool: chef
    install_method_tool_version: chef-17.10.3
    logs_transport: HTTP

=========
Collector
=========

  Running Checks
  ==============

    container
    ---------
      Instance ID: container [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/container.d/conf.yaml.default
      Total Runs: 1,740
      Metric Samples: Last Run: 89, Total: 156,051
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 4ms
      Last Execution Date : 2022-04-08 20:27:31 UTC (1649449651000)
      Last Successful Execution Date : 2022-04-08 20:27:31 UTC (1649449651000)


    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 1,740
      Metric Samples: Last Run: 9, Total: 15,653
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-04-08 20:27:27 UTC (1649449647000)
      Last Successful Execution Date : 2022-04-08 20:27:27 UTC (1649449647000)


    disk (4.6.0)
    ------------
      Instance ID: disk:63ca5afeebc4ab99 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/disk.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 32, Total: 55,680
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 25ms
      Last Execution Date : 2022-04-08 20:27:25 UTC (1649449645000)
      Last Successful Execution Date : 2022-04-08 20:27:25 UTC (1649449645000)


    docker
    ------
      Instance ID: docker [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/docker.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 26, Total: 43,310
      Events: Last Run: 1, Total: 29
      Service Checks: Last Run: 1, Total: 1,740
      Average Execution Time : 34ms
      Last Execution Date : 2022-04-08 20:27:32 UTC (1649449652000)
      Last Successful Execution Date : 2022-04-08 20:27:32 UTC (1649449652000)


    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 1,740
      Metric Samples: Last Run: 5, Total: 8,700
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-04-08 20:27:34 UTC (1649449654000)
      Last Successful Execution Date : 2022-04-08 20:27:34 UTC (1649449654000)


    haproxy (4.1.0)
    ---------------
      Instance ID: haproxy:221564aec9d41635 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/haproxy.d/conf.yaml
      Total Runs: 1,739
      Metric Samples: Last Run: 387, Total: 672,993
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 18, Total: 31,302
      Average Execution Time : 57ms
      Last Execution Date : 2022-04-08 20:27:24 UTC (1649449644000)
      Last Successful Execution Date : 2022-04-08 20:27:24 UTC (1649449644000)
      metadata:
        version.major: 2
        version.minor: 4
        version.patch: 15
        version.raw: 2.4.15-1~bpo11+1
        version.release: 1
        version.scheme: semver


    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 1,740
      Metric Samples: Last Run: 41, Total: 71,313
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-04-08 20:27:26 UTC (1649449646000)
      Last Successful Execution Date : 2022-04-08 20:27:26 UTC (1649449646000)


    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 1,740
      Metric Samples: Last Run: 6, Total: 10,440
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-04-08 20:27:33 UTC (1649449653000)
      Last Successful Execution Date : 2022-04-08 20:27:33 UTC (1649449653000)


    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 1,740
      Metric Samples: Last Run: 20, Total: 34,800
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-04-08 20:27:25 UTC (1649449645000)
      Last Successful Execution Date : 2022-04-08 20:27:25 UTC (1649449645000)


    network (2.6.0)
    ---------------
      Instance ID: network:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 1,740
      Metric Samples: Last Run: 165, Total: 287,060
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 20ms
      Last Execution Date : 2022-04-08 20:27:32 UTC (1649449652000)
      Last Successful Execution Date : 2022-04-08 20:27:32 UTC (1649449652000)


    nginx (5.2.1)
    -------------
      Instance ID: nginx:968f73d70f7ef99d [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/nginx.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1,740
      Average Execution Time : 11ms
      Last Execution Date : 2022-04-08 20:27:31 UTC (1649449651000)
      Last Successful Execution Date : Never
      Error: 404 Client Error: Not Found for url: http://localhost:8090/nginx_status/
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1071, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nginx/nginx.py", line 62, in check
          metrics = self.collect_unit_metrics()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nginx/nginx.py", line 180, in collect_unit_metrics
          response, content_type, version = self._get_data()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nginx/nginx.py", line 211, in _get_data
          r = self._perform_service_check(self.url)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nginx/nginx.py", line 231, in _perform_service_check
          r = self._perform_request(url)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nginx/nginx.py", line 218, in _perform_request
          r.raise_for_status()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
          raise HTTPError(http_error_msg, response=self)
      requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8090/nginx_status/

    ntp
    ---
      Instance ID: ntp:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 29
      Metric Samples: Last Run: 1, Total: 29
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 29
      Average Execution Time : 1.781s
      Last Execution Date : 2022-04-08 20:12:45 UTC (1649448765000)
      Last Successful Execution Date : 2022-04-08 20:12:45 UTC (1649448765000)


    postgres (12.1.1)
    -----------------
      Instance ID: postgres:c701c96a846e79ef [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/postgres.d/conf.yaml
      Total Runs: 1,739
      Metric Samples: Last Run: 30, Total: 52,170
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1,739
      Average Execution Time : 32ms
      Last Execution Date : 2022-04-08 20:27:23 UTC (1649449643000)
      Last Successful Execution Date : 2022-04-08 20:27:23 UTC (1649449643000)
      metadata:
        version.major: 13
        version.minor: 6
        version.patch: 0
        version.raw: 13.6 (Debian 13.6-1.pgdg110+1)
        version.scheme: semver


    redisdb (4.4.0)
    ---------------
      Instance ID: redisdb:6c893af6f0bd0387 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/redisdb.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 49, Total: 85,388
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1,740
      Average Execution Time : 24ms
      Last Execution Date : 2022-04-08 20:27:36 UTC (1649449656000)
      Last Successful Execution Date : 2022-04-08 20:27:36 UTC (1649449656000)
      metadata:
        version.major: 6
        version.minor: 0
        version.patch: 15
        version.raw: 6.0.15
        version.scheme: semver

      Instance ID: redisdb:730ebde70e3be1bd [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/redisdb.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 49, Total: 85,283
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1,740
      Average Execution Time : 12ms
      Last Execution Date : 2022-04-08 20:27:30 UTC (1649449650000)
      Last Successful Execution Date : 2022-04-08 20:27:30 UTC (1649449650000)
      metadata:
        version.major: 6
        version.minor: 0
        version.patch: 15
        version.raw: 6.0.15
        version.scheme: semver

      Instance ID: redisdb:90668d9493f9c761 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/redisdb.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 44, Total: 76,568
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1,740
      Average Execution Time : 10ms
      Last Execution Date : 2022-04-08 20:27:28 UTC (1649449648000)
      Last Successful Execution Date : 2022-04-08 20:27:28 UTC (1649449648000)
      metadata:
        version.major: 6
        version.minor: 0
        version.patch: 15
        version.raw: 6.0.15
        version.scheme: semver

      Instance ID: redisdb:c2947aaac5f298cb [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/redisdb.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 49, Total: 85,281
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1,740
      Average Execution Time : 11ms
      Last Execution Date : 2022-04-08 20:27:29 UTC (1649449649000)
      Last Successful Execution Date : 2022-04-08 20:27:29 UTC (1649449649000)
      metadata:
        version.major: 6
        version.minor: 0
        version.patch: 15
        version.raw: 6.0.15
        version.scheme: semver

      Instance ID: redisdb:ff22849370e043f3 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/redisdb.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 49, Total: 85,274
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1,740
      Average Execution Time : 10ms
      Last Execution Date : 2022-04-08 20:27:37 UTC (1649449657000)
      Last Successful Execution Date : 2022-04-08 20:27:37 UTC (1649449657000)
      metadata:
        version.major: 6
        version.minor: 0
        version.patch: 15
        version.raw: 6.0.15
        version.scheme: semver


    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 1,739
      Metric Samples: Last Run: 1, Total: 1,739
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-04-08 20:27:24 UTC (1649449644000)
      Last Successful Execution Date : 2022-04-08 20:27:24 UTC (1649449644000)


    varnish (1.13.0)
    ----------------
      Instance ID: varnish:8a47e1fa995ab9f1 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/varnish.d/conf.yaml
      Total Runs: 1,740
      Metric Samples: Last Run: 399, Total: 694,260
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 46ms
      Last Execution Date : 2022-04-08 20:27:35 UTC (1649449655000)
      Last Successful Execution Date : 2022-04-08 20:27:35 UTC (1649449655000)
      metadata:
        version.major: 6
        version.minor: 5
        version.patch: 1
        version.raw: 6.5.1
        version.scheme: semver

========
JMXFetch
========

  Information
  ==================
  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    Cluster: 0
    ClusterRole: 0
    ClusterRoleBinding: 0
    CronJob: 0
    DaemonSet: 0
    Deployment: 0
    Dropped: 0
    HighPriorityQueueFull: 0
    Ingress: 0
    Job: 0
    Node: 0
    PersistentVolume: 0
    PersistentVolumeClaim: 0
    Pod: 0
    ReplicaSet: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Role: 0
    RoleBinding: 0
    Service: 0
    ServiceAccount: 0
    StatefulSet: 0

  Transaction Successes
  =====================
    Total number: 3688
    Successes By Endpoint:
      check_run_v1: 1,740
      intake: 164
      metadata_v1: 44
      series_v1: 1,740

  On-disk storage
  ===============
    On-disk storage is disabled. Configure `forwarder_storage_max_size_in_bytes` to enable it.

  API Keys status
  ===============
    API key ending with 71fd4: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 71fd4

==========
Logs Agent
==========

    Reliable: Sending compressed logs in HTTPS to agent-http-intake.logs.datadoghq.com on port 443
    BytesSent: 1.530778e+06
    EncodedBytesSent: 441573
    LogsProcessed: 2481
    LogsSent: 2481

  docker
  ------
    - Type: docker
      Status: OK
      Inputs:
        1cbd83739d88701e7a23a510924b9c6611edae899ed637edb1a3ebc8335b665b
        f1107ce1080df28250e28ab1a8ebe53722a3ef642fa665308d1331959a379192
        89faffdf52bbdacdf5e3270e6eb486d5cbab770b2c48110cd987bfb7b8225be3
      BytesRead: 449929
      Average Latency (ms): 0
      24h Average Latency (ms): 0
      Peak Latency (ms): 3
      24h Peak Latency (ms): 3

  fail2ban
  --------
    - Type: file
      Path: /var/log/fail2ban.log
      Status: OK
      Inputs:
        /var/log/fail2ban.log
      BytesRead: 54364
      Average Latency (ms): 0
      24h Average Latency (ms): 0
      Peak Latency (ms): 1
      24h Peak Latency (ms): 1

  journald
  --------
    - Type: journald
      Status: OK
      Inputs:
        /run/log/journal
      BytesRead: 0
      Average Latency (ms): 0
      24h Average Latency (ms): 0
      Peak Latency (ms): 0
      24h Peak Latency (ms): 0

  nginx
  -----
    - Type: file
      Path: /var/log/nginx/access.log
      Status: OK
      Inputs:
        /var/log/nginx/access.log
      BytesRead: 0
      Average Latency (ms): 0
      24h Average Latency (ms): 0
      Peak Latency (ms): 0
      24h Peak Latency (ms): 0
    - Type: file
      Path: /var/log/nginx/error.log
      Status: OK
      Inputs:
        /var/log/nginx/error.log
      BytesRead: 0
      Average Latency (ms): 0
      24h Average Latency (ms): 0
      Peak Latency (ms): 0
      24h Peak Latency (ms): 0

============
System Probe
============
System Probe is running

=============
Process Agent
=============

  Version: 7.35.0
  Status date: 2022-04-08 20:27:45.23 UTC (1649449665230)
  Process Agent Start: 2022-04-08 13:12:34.204 UTC (1649423554204)
  Pid: 3.263893e+06
  Go Version: go1.17.6
  Build arch: amd64
  Log Level: INFO
  Enabled Checks: [process rtprocess connections]
  Allocated Memory: 14,402,168 bytes

  =================
  Process Endpoints
  =================
    https://process.datadoghq.com - API Key ending with:
        - 71fd4

  =========
  Collector
  =========
    Last collection time: 2022-04-08 20:27:40
    Docker socket: /var/run/docker.sock
    Number of processes: 68
    Number of containers: 3
    Process Queue length: 0
    RTProcess Queue length: 0
    Pod Queue length: 0
    Process Bytes enqueued: 0
    RTProcess Bytes enqueued: 0
    Pod Bytes enqueued: 0

=========
APM Agent
=========
  Status: Running
  Pid: 3.263894e+06
  Uptime: 26111 seconds
  Mem alloc: 10,649,872 bytes
  Hostname: 
  Receiver: 0.0.0.0:8126
  Endpoints:
    https://trace.agent.datadoghq.com

  Receiver (previous minute)
  ==========================
    From ruby 3.1.1 (ruby-x86_64-linux), client 0.54.2
      Traces received: 256 (233,080 bytes)
      Spans received: 501

    Default priority sampling rate: 100.0%
    Priority sampling rate for 'service:notos,env:': 100.0%
    Priority sampling rate for 'service:notos,env:none': 100.0%
    Priority sampling rate for 'service:redis,env:': 100.0%
    Priority sampling rate for 'service:redis,env:none': 100.0%
    Priority sampling rate for 'service:sidekiq,env:': 100.0%
    Priority sampling rate for 'service:sidekiq,env:none': 100.0%

  Writer (previous minute)
  ========================
    Traces: 0 payloads, 0 traces, 0 events, 0 bytes
    Stats: 0 payloads, 0 stats buckets, 0 bytes

=========
Aggregator
=========
  Checks Metric Sample: 2,690,091
  Dogstatsd Metric Sample: 476,886
  Event: 30
  Events Flushed: 30
  Number Of Flushes: 1,740
  Series Flushed: 2,882,801
  Service Check: 78,336
  Service Checks Flushed: 80,071
=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 476,885
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 55,168,537
  Udp Packet Reading Errors: 0
  Udp Packets: 314,039
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0
  Unterminated Metric Errors: 0
```

</details>

**Describe what happened:**
After upgrading to agent 7.35.0, we are seeing issues with the `docker.containers.running` metric.

We are using Docker Swarm and have alerts on the number of running containers based on their `swarm_service` attribute. We are monitoring this for 3 values of this attribute.

This is running on a single node (staging environment).

Since the update, only containers for 2 of those tags have a `docker.containers.running` metric, triggering the alert for the 3rd service. But it is not always the same containers, when we deploy our service the metric can start to have values for the service that missed them previously, and another one starts not having containers reported.

For example:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/42070/162526178-2cea2f59-48db-4754-a3ca-42d3c14e082b.png">

You can see here that at 22:05 our sidekiq container series stopped, and we correctly have 2 running containers for our Puma service.

This worked fine with the previous agent version

**Describe what you expected:**
`docker.containers.running` metric exists for all 3 `swarm_service` attributes

**Steps to reproduce the issue:**
Not sure what triggers this and how to reproduce, but I can send you our DD account details if you want to have a look.

**Additional environment details (Operating System, Cloud provider, etc):**
Running on Debian 11.3, installed with Chef from the Datadog cookbook and packages.

**Comment by jacjtito** [comment]
Automatically closed due to inactivity.
