### ISSUE TITLE
Build error with downloaded source : expecting git initialisation 

### ISSUE THREAD

**Issue by HarinadhD** [DataDog/datadog-agent#12416]
Describe what happened: 
Unable to build from extracted source 

Describe what you expected: 
should be able to build without any error 

Steps to reproduce the issue: 
1. Download source from the following link : https://github.com/DataDog/datadog-agent/archive/refs/tags/7.36.1.tar.gz  
2. Extract source 
3. Install all dependencies 
4. invoke agent.build

error logs:
root@hdommaraju [ ~/datadog-agent/v7.36.1/datadog-agent-7.36.1 ]# invoke install-tools
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/usr/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/lib/python3.7/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/lib/python3.7/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/lib/python3.7/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/lib/python3.7/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/tasks/__init__.py", line 10, in <module>
    from . import (
  File "/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/tasks/pylauncher.py", line 14, in <module>
    PYLAUNCHER_BIN_PATH = os.path.join(get_root(), "bin", "pylauncher")
  File "/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/tasks/utils.py", line 313, in get_root
    return check_output(['git', 'rev-parse', '--show-toplevel']).decode('utf-8').strip()
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--show-toplevel']' returned non-zero exit status 128.

6. Run git init && invoke install-tools  && invoke agent.build 

--
[100%] Built target datadog-agent-three
make[1]: Leaving directory '/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/rtloader/build'
Install the project...
-- Install configuration: ""
-- Installing: /root/datadog-agent/v7.36.1/datadog-agent-7.36.1/dev/lib64/libdatadog-agent-three.so
-- Set runtime path of "/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/dev/lib64/libdatadog-agent-three.so" to ""
-- Installing: /root/datadog-agent/v7.36.1/datadog-agent-7.36.1/dev/lib64/libdatadog-agent-rtloader.so.0.1.0
-- Installing: /root/datadog-agent/v7.36.1/datadog-agent-7.36.1/dev/lib64/libdatadog-agent-rtloader.so.1
-- Installing: /root/datadog-agent/v7.36.1/datadog-agent-7.36.1/dev/lib64/libdatadog-agent-rtloader.so
-- Installing: /root/datadog-agent/v7.36.1/datadog-agent-7.36.1/dev/include/datadog_agent_rtloader.h
-- Installing: /root/datadog-agent/v7.36.1/datadog-agent-7.36.1/dev/include/rtloader_types.h
-- Installing: /root/datadog-agent/v7.36.1/datadog-agent-7.36.1/dev/include/rtloader_mem.h
make: Leaving directory '/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/rtloader/build'
fatal: Needed a single revision
Traceback (most recent call last):
  File "/usr/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/lib/python3.7/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/lib/python3.7/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/tasks/agent.py", line 129, in build
    python_runtimes=python_runtimes,
  File "/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/tasks/utils.py", line 156, in get_build_flags
    ldflags = get_version_ldflags(ctx, prefix, major_version=major_version)
  File "/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/tasks/utils.py", line 277, in get_version_ldflags
    commit = get_git_commit()
  File "/root/datadog-agent/v7.36.1/datadog-agent-7.36.1/tasks/utils.py", line 290, in get_git_commit
    return check_output(['git', 'rev-parse', '--short', 'HEAD']).decode('utf-8').strip()
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128

Additional environment details (Operating System, Cloud provider, etc): Linux environment

**Comment by jacjtito** [comment]
Automatically closed due to inactivity.
