### ISSUE TITLE
[BUG] There's no way to know when the trace agent is ready

### ISSUE THREAD

**Issue by lexicalunit** [DataDog/datadog-agent#14103]
**Agent Environment**
Agent is started locally via docker:

```
docker run --rm \
    --name dd-agent \
    -p8125:8125 \
    -p8126:8126 \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /proc/:/host/proc/:ro \
    -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
    -e DD_API_KEY="OMIT" \
    -e DD_APP_KEY="OMIT" \
    -e DD_AGENT_MAJOR_VERSION="7" \
    -e DD_SERVICE="myapp" \
    -e DD_HOSTNAME="localhost" \
    -e DD_ENV="dev" \
    gcr.io/datadoghq/agent:7
```

**Describe what happened:**
The start script for my application:

```shell
while ! nc localhost 8126 </dev/null; do
    echo "waiting for statsd server to start..."
    sleep 1
done

ddtrace-run myapp
```

If I run my start script it will sit and wait for statsd to start. If I then go and run the above docker command to start the dd agent, my start script eventually connects and then proceeds to run my app via ddtrace-run.

As my app is starting up though, I get this error:

```log
[2022-10-28 14:42:48][ddtrace.internal.writer][ERROR] - failed to send traces to Datadog Agent at http://localhost:8126/v0.4/traces
Traceback (most recent call last):
  File "myapp/env/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "myapp/env/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 446, in _send_payload
    response = self._put(payload, headers)
  File "myapp/env/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 399, in _put
    resp = compat.get_connection_response(self._conn)
  File "myapp/env/lib/python3.10/site-packages/ddtrace/internal/compat.py", line 235, in get_connection_response
    return conn.getresponse()
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "myapp/env/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 559, in flush_queue
    self._retry_upload(self._send_payload, encoded, n_traces)
  File "myapp/env/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "myapp/env/lib/python3.10/site-packages/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x106c2e9b0 state=finished raised RemoteDisconnected>]
```

This error comes 1 second before I finally see:

```log
2022-10-28 21:42:48 UTC | TRACE | INFO | (run.go:254 in Infof) | Listening for traces at http://0.0.0.0:8126
```

In the logs for the docker dd-agent. So what's happening is my app is trying to send traces before the dd-agent is ready to send them. There needs to be some way for me to ask dd-agent if it's ready to go so that my app can wait until that time to proceed with traces.

**Describe what you expected:**
I expect there to be some way in either bash or python for me to ask the dd-agent, "is it ok to send traces?"

**Steps to reproduce the issue:**
This will happen for any application that uses `ddtrace-run` and can not rely on `dd-agent` to be running already at start up time.

**Additional environment details (Operating System, Cloud provider, etc):**
I see this error on linux and mac systems, aws and heroku.

**Comment by vickenty** [comment]
Hi @lexicalunit, thanks for using Datadog.

Since in this case the port on the host is opened by docker rather than the agent itself, it indeed happens before the agent is ready to handle requests. It may be better to wait until a full http request succeeds, for example by running `curl http://localhost:8126/info` instead of `nc`. If you need further assistance, feel free to reach out to our [support](http://docs.datadoghq.com/help/).

Thanks.
