### ISSUE TITLE
[Mac] DMG install process failures

### ISSUE THREAD

**Issue by platinummonkey** [DataDog/datadog-agent#1453]
The upgrade process is never clean on `brew cask upgrade` which seems to just pull the DMG and install.

**`brew cask upgrade` output**
```
==> Downloading https://s3.amazonaws.com/dd-agent/datadogagent.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask datadog-agent
==> Starting upgrade for Cask datadog-agent
==> Running uninstall process for datadog-agent; your password may be necessary
==> Uninstalling packages:
com.datadoghq.agent
==> rm: /opt/datadog-agent/embedded/share/terminfo/2/2621a: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/e/eterm: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/e/eterm-color: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/h/hp2621a: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/h/hp70092a: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/l/lft-pc850: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/n/ncr260vt300wpp: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/n/ncrvt100wpp: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p12: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p12-m: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p12-m-w: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p12-w: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p14: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p14-m: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p14-m-w: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p14-w: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p4: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p5: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p7: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p8: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p8-w: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p9: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p9-8: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p9-8-w: No such file or directory
==> rm: /opt/datadog-agent/embedded/share/terminfo/p/p9-w: No such file or directory
==> Purging files for version 6.0.3-1 of Cask datadog-agent
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm --

==> Standard Output of failed command:


==> Standard Error of failed command:
rm: /opt/datadog-agent/embedded/share/terminfo/2/2621a: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/e/eterm: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/e/eterm-color: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/h/hp2621a: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/h/hp70092a: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/l/lft-pc850: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/n/ncr260vt300wpp: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/n/ncrvt100wpp: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p12: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p12-m: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p12-m-w: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p12-w: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p14: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p14-m: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p14-m-w: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p14-w: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p4: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p5: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p7: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p8: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p8-w: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p9: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p9-8: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p9-8-w: No such file or directory
rm: /opt/datadog-agent/embedded/share/terminfo/p/p9-w: No such file or directory


==> Exit status of failed command:
#<Process::Status: pid 9930 exit 1>
```

**Describe what happened:**
cask upgrading datadog-agent fails and requires manual intervention.

Step 1: See above.

Step 2: Copy your config over, this is going to be "fun".

Step 3: Let's try uninstalling: **Fail 2**
```
brew cask uninstall datadog-agent
==> Uninstalling Cask datadog-agent
==> Running uninstall process for datadog-agent; your password may be necessary
==> Uninstalling packages:
com.datadoghq.agent
Password:

Error: No such file or directory @ rb_file_s_stat - /opt/datadog-agent/embedded/share/terminfo/X
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:96:in `stat'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:96:in `stat'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:96:in `with_full_permissions'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:30:in `block in uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:29:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:214:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:212:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:212:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:211:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:211:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

Step 4: Is it still there? *Yes, kinda*:
```
ls -l /opt/datadog-agent
total 0
drwxr-xr-x 15 root    wheel 480 Mar 14 08:19 LICENSES
drwxr-xr-x  3 root    wheel  96 Mar 14 08:19 bin
drwxr-xr-x  9 root    wheel 288 Mar  7 05:46 embedded
drwxr-xr-x  6 **** admin 192 Mar 14 08:19 etc
drwxr-xr-x  2 **** admin  64 Mar  7 05:43 run
drwxr-xr-x  2 root    wheel  64 Mar  7 05:43 scripts
drwxr-xr-x  3 root    wheel  96 Mar  7 05:43 sources
```

Step 5: Kill it with fire: `sudo rm -Rf /opt/datadog-agent`

Step 6: Now you must make homebrew happy:
```
brew cask uninstall datadog-agent
==> Uninstalling Cask datadog-agent
==> Running uninstall process for datadog-agent; your password may be necessary
==> Uninstalling packages:
com.datadoghq.agent
==> Purging files for version 6.0.2-1 of Cask datadog-agent
```

Step 7: Now install again:
```
brew cask install datadog-agent
==> Caveats
You will need to update /opt/datadog-agent/etc/datadog.conf and replace APIKEY with your api key

If you ever want to start/stop the Agent, please use the Datadog Agent App or datadog-agent command.
It will start automatically at login, if you want to enable it at startup, run these commands:

sudo cp '/opt/datadog-agent/etc/com.datadoghq.agent.plist' /Library/LaunchDaemons
sudo launchctl load -w /Library/LaunchDaemons/com.datadoghq.agent.plist

==> Satisfying dependencies
==> Downloading https://s3.amazonaws.com/dd-agent/datadogagent.dmg
Already downloaded: /Users/*****/Library/Caches/Homebrew/Cask/datadog-agent--6.0.3-1.dmg
==> Verifying checksum for Cask datadog-agent
==> Installing Cask datadog-agent
==> Running installer for datadog-agent; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Agent
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  datadog-agent was successfully installed!
```

Step 8: Now copy back over your config & restart the agent. And we're left with:
```
ls -l /opt/datadog-agent
total 48
-rw-r--r--   1 root    wheel 31633 Mar 12 08:31 LICENSE
drwxr-xr-x 121 root    wheel  3872 Mar 14 08:29 LICENSES
-rw-r--r--   1 root    wheel    30 Mar 12 08:27 agent_requirements.txt
drwxr-xr-x   4 root    wheel   128 Mar 12 08:27 bin
drwxr-xr-x   9 root    wheel   288 Mar 12 08:29 embedded
drwxr-xr-x   7 ***** admin   224 Mar 14 08:29 etc
drwxr-xr-x   2 ***** admin    64 Mar 12 08:27 run
drwxr-xr-x   2 root    wheel    64 Mar 12 08:27 scripts
drwxr-xr-x   3 root    wheel    96 Mar 12 08:19 sources
-rw-r--r--   1 root    wheel  7906 Mar 12 08:31 version-manifest.json
-rw-r--r--   1 root    wheel  2843 Mar 12 08:31 version-manifest.txt
```

**Describe what you expected:**
Clean upgrade process that is tolerant of directories missing and minor errors.

**Steps to reproduce the issue:**
just upgrade 🍭 See above.

**Additional environment details (Operating System, Cloud provider, etc):**
OS: High Sierra 10.13.3
Model: MBP 2017

**Comment by olivielpeau** [comment]
Hi @platinummonkey! Thanks for the detailed report.

The `datadog-agent` cask isn't officially supported and we haven't tested the upgrade path from Agent v5 to 6 on the cask.

I'm not very familiar with how casks work, and which commands are run exactly when upgrading a pkg, but upgrades from v5 to v6 work without errors when done using the [official install script](https://github.com/DataDog/datadog-agent/blob/6.0.3/cmd/agent/install_mac_os.sh) or when executing the DMG directly.

Would you happen to know which tools/command cask uses internally to install/upgrade a pkg?

**Comment by platinummonkey** [comment]
hey! I didn't try from `v5` to `v6`, only `v6.<some revision>` -> `v6.<some newer revision>`. In a nutshell it's just downloading the DMG extracting the pkg and installing that.

**Comment by platinummonkey** [comment]
same things happens this latest release `datadog-agent (6.0.3-1) --> 6.1.0-1`
