### ISSUE TITLE
Installation of DataDog agent results in GO related errors

### ISSUE THREAD

**Issue by nick-kostov** [DataDog/datadog-agent#14689]
Hello Guys,

OS: 
```bash 
~]$ cat /etc/redhat-release
CentOS release 6.10 (Final)
```

I have found out that using the ansible datadog.datadog role and using the installation procedure on datadog webpage results in:

Errors received upon start:
 ```bash 
2022-12-10 14:36:53 CET | CORE | INFO | (pkg/forwarder/domain_forwarder.go:236 in Stop) | domainForwarder stopped
2022-12-10 14:36:53 CET | CORE | INFO | (pkg/logs/logs.go:149 in Stop) | Stopping logs-agent
2022-12-10 14:36:53 CET | CORE | INFO | (pkg/logs/logs.go:158 in Stop) | logs-agent stopped
2022-12-10 14:36:53 CET | CORE | INFO | (cmd/agent/app/run.go:535 in StopAgent) | See ya!
panic: runtime error: slice bounds out of range [56:25]

goroutine 1 [running]:
github.com/DataDog/gohai/filesystem.parseDfOutput({0xc000c994a0?, 0xc000e32600?})
        /go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20220823152657-b201b8a4ebec/filesystem/filesystem.go:97 +0x53c
github.com/DataDog/gohai/filesystem.getFileSystemInfo()
        /go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20220823152657-b201b8a4ebec/filesystem/filesystem.go:34 +0x16d
github.com/DataDog/gohai/filesystem.(*FileSystem).Collect(...)
        /go/pkg/mod/github.com/!data!dog/gohai@v0.0.0-20220823152657-b201b8a4ebec/filesystem/filesystem_common.go:12
github.com/DataDog/datadog-agent/pkg/metadata/internal/gohai.getGohaiInfo()
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/internal/gohai/gohai.go:44 +0xdf
github.com/DataDog/datadog-agent/pkg/metadata/internal/gohai.GetPayload(...)
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/internal/gohai/gohai.go:30
github.com/DataDog/datadog-agent/pkg/metadata/v5.GetPayload({0x5612f30, 0xc0000560b8}, {{0xc0004fbb78?, 0x7f2013a29a68?}, {0x4d8909e?, 0x1ee3442?}})
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/v5/v5.go:38 +0x1c5
github.com/DataDog/datadog-agent/pkg/metadata.(*HostCollector).Send(0x4744e40?, {0x5612f30, 0xc0000560b8}, {0x5625ac0, 0xc0005b78b0})
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/host.go:27 +0x52
github.com/DataDog/datadog-agent/pkg/metadata.(*Scheduler).firstRun(0xc000e2ae40)
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/scheduler.go:155 +0xd5
github.com/DataDog/datadog-agent/pkg/metadata.NewScheduler({0x56262c0?, 0xc000d04b60})
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/scheduler.go:52 +0xc5
github.com/DataDog/datadog-agent/cmd/agent/app.StartAgent()
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/app/run.go:473 +0x1b27
github.com/DataDog/datadog-agent/cmd/agent/app.run(0x0?, {0x0?, 0x0?, 0x0?})
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/app/run.go:156 +0x1b5
github.com/DataDog/datadog-agent/cmd/agent/app.start(0x75574c0?, {0x7c3ad58?, 0x0?, 0x0?})
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/app/start.go:30 +0x1e
github.com/spf13/cobra.(*Command).execute(0x75574c0, {0x7c3ad58, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x7553640)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/main.go:19 +0x25
```

Upon checking status:
```bash
Getting the status from the agent.

Could not reach agent: Get "https://localhost:5001/agent/status": dial tcp [::1]:5001: connect: connection refused
Make sure the agent is running before requesting the status and contact support if you continue having issues.
Error: Get "https://localhost:5001/agent/status": dial tcp [::1]:5001: connect: connection refused
```

**Comment by sgnn7** [comment]
Hi @nick-kostov!
This issue has already been identified and [fixed](https://github.com/DataDog/datadog-agent/pull/14385) in the pending Agent v7.41.0 release. The mentioned release is in the final stages of QA so it should be available soon (baring any surprises). A downgrade to v7.38 should alleviate the issue if you need an immediate fix.

Hope this helps.

PS: I'll leave the issue open until the 7.41.0 release is published/available for visibility.

**Comment by sgnn7** [comment]
Hi @nick-kostov,
Since 7.41.0 is now released, the issue can be closed but feel free to reopen it if needed.
