### ISSUE TITLE
[BUG] Multiline log processing rule not working as expected

### ISSUE THREAD

**Issue by PaoloSivieroPV** [DataDog/datadog-agent#14977]
**Agent Environment**

**Describe what happened:**
DataLog isn't unpacking the logs that are being sent from my machine correctly. I have enabled the line "logs_enabled = true" on the datadog.yaml. I setup my app.d/conf.yaml in this way:

```
#Log section
logs:

    # - type : (mandatory) type of log input source (tcp / udp / file)
    #   port / path : (mandatory) Set port if type is tcp or udp. Set path if type is file
    #   service : (mandatory) name of the service owning the log
    #   source : (mandatory) attribute that defines which integration is sending the log
    #   sourcecategory : (optional) Multiple value attribute. Can be used to refine the source attribute
    #   tags: (optional) add tags to each log collected

  - type: file
    path: C:\weblogs\*.log
    service: ParcVu
    source: parcvu
    log_processing_rules:
       - type: multi_line
         name: multiline_log
         pattern: \!\!\!\s\d{7}\t\d{2}\/\d{2}\/\d{4}\s\d{2}:\d{2}:\d{2}\.\d{3}
       - type: include_at_match
         name: singleline_log
         pattern: \?\?\?\s\d{7}\t\d{2}\/\d{2}\/\d{4}\s\d{2}:\d{2}:\d{2}\.\d{3}

```
So all the lines that are starting with "!!!" have to be considered as a multiline, while the lines starting with "???" should be considered as a single line log. 

Here's the example file I've been using:
```
??? 0000007	07/12/2022 05:00:00.004	PARCVUSQL1	Info	 Scheduler	PARCVUSQL1	INFO	*SCHEDULER* Running 'Bulk Export' Scheduled Task against database 'LIVE', writing to file 'c:\temp\export.csv', with errors emailed to ''
??? 0000007	07/12/2022 05:00:00.004	PARCVUSQL1	Calls	BulkExpTsk	PARCVUSQL1	CALL	SaveAndReturnScheduledItems at c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Server\SystemTools\Scheduler\DalScheduler.cs : line 123
!!! 0000007	07/12/2022 05:00:00.004	PARCVUSQL1	Calls	BulkExpTsk	PARCVUSQL1	CALL	UpdateDataSet at c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Server\DataManager.cs : line 42
EXCEPTION: System.UnauthorizedAccessException
MESSAGE: Access to the path 'c:\temp\export221207.csv' is denied.
SOURCE: mscorlib
STACK:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at ParcVuBase.Framework.CSVExport.DataSetExporter.Export(DataTable dt, String destinationFileName, Boolean includeHeaders, IExportDataFormatter formatter, ExportMetaData metaData) in c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Framework\CSVExport\DataSetExporter.cs:line 77

!!! 0000007	07/12/2022 05:00:03.442	PARCVUSQL1	Errors	BulkExpTsk	PARCVUSQL1	EXCEPTION	
EXCEPTION: System.UnauthorizedAccessException
MESSAGE: Access to the path 'c:\temp\export221207.csv' is denied.
SOURCE: mscorlib
STACK:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at ParcVuBase.Framework.CSVExport.DataSetExporter.Export(DataTable dt, String destinationFileName, Boolean includeHeaders, IExportDataFormatter formatter, ExportMetaData metaData) in c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Framework\CSVExport\DataSetExporter.cs:line 88
   at ParcVuBase.Server.SystemTools.Maintenance.RunBulkExportTask(String baseFilename) in c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Server\SystemTools\Maintenance.cs:line 1678

??? 0000007	07/12/2022 05:00:03.442	PARCVUSQL1	Calls	BulkExpTsk	PARCVUSQL1	END	RunBulkExportTask at c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Server\SystemTools\Maintenance.cs : line 1641
??? 0000007	07/12/2022 05:00:03.442	PARCVUSQL1	Calls	BulkExpTsk	PARCVUSQL1	CALL	GetLookupData at c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Server\SystemTools\Maintenance.cs : line 161
??? 0000007	07/12/2022 05:00:03.442	PARCVUSQL1	Calls	BulkExpTsk	PARCVUSQL1	CALL	LoadConfigurationWrapper at c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Server\SystemTools\Maintenance.cs : line 1039
!!! 0000007 00:00:00.734	0000007	07/12/2022 05:00:04.942	PARCVUSQL1	Errors	BulkExpTsk	PARCVUSQL1	EXCEPTION	*** UNHANDLED EXCEPTION : 
CLIENT MACHINE : SERVER
USER : SERVER

EXCEPTION: System.UnauthorizedAccessException
MESSAGE: Access to the path 'c:\temp\export221207.csv' is denied.
SOURCE: mscorlib
STACK:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at ParcVuBase.Framework.CSVExport.DataSetExporter.Export(DataTable dt, String destinationFileName, Boolean includeHeaders, IExportDataFormatter formatter, ExportMetaData metaData) in c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Framework\CSVExport\DataSetExporter.cs:line 88
   at ParcVuBase.Server.SystemTools.Maintenance.RunBulkExportTask(String baseFilename) in c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Server\SystemTools\Maintenance.cs:line 1691
   at ParcVuBase.Server.ScheduledTasks.ScheduledBulkExport.<ExecuteAsync>d__1.MoveNext() in c:\SOURCE_CODE\ParcVu\ParcVu_2_Main\Branches\Rel\ParcVu_2_2_27_xx\ParcVuBase\Server\ScheduledTasks\ScheduledBulkExport.cs:line 66`

```
What happens is: if I remove the multiline processing rule I get  all the single lines starting with ??? unpacked correctly on DataDog. 
![image](https://user-images.githubusercontent.com/122089347/210976764-821ba96d-ff60-4837-b15a-68e50a09fd4f.png)

As soon as I implement the multiline one, all the logs are considered to be multilined and the parses doesn't stop at the next occurence as indicated in the documentation. 
![image](https://user-images.githubusercontent.com/122089347/210976855-4a1d2bf3-c951-4a79-bfff-d05a69702433.png)
![image](https://user-images.githubusercontent.com/122089347/210976892-6e4202d6-9431-4968-96c4-2de35542dab6.png)

If I comment the multiline processing rules, Datadog gets 

**Describe what you expected:**
I expected Datadog, given two different processing rules, to be able to analyse a log file and parse the different lines with different processing rules.

**Steps to reproduce the issue:**
As described in the previous sections, setup the datadog.yaml to accepts logs, setup a new app.d/conf.yaml and run the agent. 
Conf.yaml

```

#Log section
logs:

    # - type : (mandatory) type of log input source (tcp / udp / file)
    #   port / path : (mandatory) Set port if type is tcp or udp. Set path if type is file
    #   service : (mandatory) name of the service owning the log
    #   source : (mandatory) attribute that defines which integration is sending the log
    #   sourcecategory : (optional) Multiple value attribute. Can be used to refine the source attribute
    #   tags: (optional) add tags to each log collected

  - type: file
    path: C:\weblogs\*.log
    service: ParcVu
    source: parcvu
    log_processing_rules:
       - type: multi_line
         name: multiline_log
         pattern: \!\!\!\s\d{7}\t\d{2}\/\d{2}\/\d{4}\s\d{2}:\d{2}:\d{2}\.\d{3}
       - type: include_at_match
         name: singleline_log
         pattern: \?\?\?\s\d{7}\t\d{2}\/\d{2}\/\d{4}\s\d{2}:\d{2}:\d{2}\.\d{3}

```

Next upload the file used in the example above..

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
