### ISSUE TITLE
[BUG] Failing checks after upgrade to Agent 7.42.1

### ISSUE THREAD

**Issue by momelod** [DataDog/datadog-agent#15525]
**Agent Environment**
Agent 7.42.1 - Commit: 40fce81 - Serialization version: v5.0.46 - Go version: go1.18.9

`datadog-agent status`:

> ```
> ...
>   Loading Errors
>   ==============
>     apt-check
>     ---------
>       Core Check Loader:
>         Check apt-check not found in Catalog
> 
>       JMX Check Loader:
>         check is not a jmx check, or unable to determine if it's so
> 
>       Python Check Loader:
>         unable to import module 'apt-check': Traceback (most recent call last):
>   File "/etc/datadog-agent/checks.d/apt-check.py", line 1, in <module>
>     from datadog_checks.base import AgentCheck
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/datadog_checks/base/__init__.py", line 5, in <module>
>     from .checks import AgentCheck
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/datadog_checks/base/checks/__init__.py", line 5, in <module>
>     from .base import AgentCheck
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 34, in <module>
>     from ..utils.http import RequestsWrapper
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/datadog_checks/base/utils/http.py", line 20, in <module>
>     from requests_toolbelt.adapters import host_header_ssl
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
>     from .adapters import SSLAdapter, SourceAddressAdapter
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
>     from .ssl import SSLAdapter
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
>     from .._compat import poolmanager
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/requests_toolbelt/_compat.py", line 56, in <module>
>     from requests.packages.urllib3.contrib.pyopenssl \
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
>     import OpenSSL.SSL
>   File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import SSL, crypto
>   File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/OpenSSL/SSL.py", line 19, in <module>
>     from OpenSSL.crypto import (
>   File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3224, in <module>
>     utils.deprecated(
> TypeError: deprecated() got an unexpected keyword argument 'name'
> 
>     custom_domain_expiry
>     --------------------
>       Core Check Loader:
>         Check custom_domain_expiry not found in Catalog
> 
>       JMX Check Loader:
>         check is not a jmx check, or unable to determine if it's so
> 
>       Python Check Loader:
>         unable to import module 'custom_domain_expiry': Traceback (most recent call last):
>   File "/etc/datadog-agent/checks.d/custom_domain_expiry.py", line 10, in <module>
>     from datadog_checks.base import AgentCheck
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/datadog_checks/base/__init__.py", line 5, in <module>
>     from .checks import AgentCheck
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/datadog_checks/base/checks/__init__.py", line 5, in <module>
>     from .base import AgentCheck
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 34, in <module>
>     from ..utils.http import RequestsWrapper
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/datadog_checks/base/utils/http.py", line 20, in <module>
>     from requests_toolbelt.adapters import host_header_ssl
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
>     from .adapters import SSLAdapter, SourceAddressAdapter
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
>     from .ssl import SSLAdapter
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
>     from .._compat import poolmanager
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/requests_toolbelt/_compat.py", line 56, in <module>
>     from requests.packages.urllib3.contrib.pyopenssl \
>   File "/opt/datadog-agent/.local/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
>     import OpenSSL.SSL
>   File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import SSL, crypto
>   File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/OpenSSL/SSL.py", line 19, in <module>
>     from OpenSSL.crypto import (
>   File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3224, in <module>
>     utils.deprecated(
> TypeError: deprecated() got an unexpected keyword argument 'name'
> 
>     tls
>     ---
>       Core Check Loader:
>         Check tls not found in Catalog
> 
>       JMX Check Loader:
>         check is not a jmx check, or unable to determine if it's so
> 
>       Python Check Loader:
>         unable to import module 'tls': No module named 'tls'
> ...
> 
> ```

**Describe what happened:**
The agent starts and the service is running. The agent appears to be running and all checks/metrics are reporting to datadog where I can see them in my dashboard. Except however for a few checks. Those appear in the datadog dashboard with a status of `NO DATA`.

**Describe what you expected:**
I expect that when upgrading to the latest version my checks should work as before.

**Steps to reproduce the issue:**
- upgrade to Agent 7.42.1
- configure the tls check eg:

`cat /etc/datadog-agent/conf.d/tls.d/conf.yaml`:

> ```
> ## All options defined here are available to all instances.
> #
> init_config:
>     allowed_versions:
>       - TLSv1.2
>       - TLSv1.3
>     fetch_intermediate_certs: false
>     service: tls-check
> 
> ## Every instance is scheduled independent of the others.
> #
> instances:
> 
>   - server: example.com
>     port: 443
>     server_hostname: example.com
>     days_warning: 45.0
>     days_critical: 7.0
>     timeout: 30
>     min_collection_interval: 900
> ```

- run `datadog-agent check tls` (everything runs fine, all green OK but the metrics are not shown in the datadog dashboard)

**Comment by steveny91** [comment]
@momelod Hello! I wasn't able to replicate this issue. May I kindly ask if you can create a support ticket to easier troubleshoot this issue?

```
===============
Agent (v7.42.1)
===============
...
    tls (2.9.1)
    -----------
      Instance ID: tls:472f294b289f45f2 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/tls.d/conf.yaml
      Total Runs: 53
      Metric Samples: Last Run: 2, Total: 106
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 4, Total: 212
      Average Execution Time : 234ms
      Last Execution Date : 2023-02-14 07:12:46 UTC (1676358766000)
      Last Successful Execution Date : 2023-02-14 07:12:46 UTC (1676358766000)
```

Config:
```
=== tls check ===
Configuration provider: file
Configuration source: file:/etc/datadog-agent/conf.d/tls.d/conf.yaml
Instance ID: tls:472f294b289f45f2
days_critical: 7
days_warning: 45
min_collection_interval: 900
port: 443
server: example.com
server_hostname: example.com
timeout: 30
~
Init Config:
allowed_versions:
- TLSv1.2
- TLSv1.3
fetch_intermediate_certs: false
service: tls-check
```
