### ISSUE TITLE
APM Charts empty after upgrading from ddtrace 0.54.2 to 1.9.0 - trace_id_zero reported in logs

### ISSUE THREAD

**Issue by ricksuggs** [DataDog/datadog-agent#15808]
**Current behaviour**
I'm upgrading ddtrace in a Rails app from 0.54.2 to 1.9.0, but APM metrics are not appearing in DataDog. I verified that the APM metrics were not just showing up under a different service or env.

**Expected behaviour**
The APM metrics should continue to appear in DataDog.

**Steps to reproduce**
Using the datadog-heroku-buildpack.
I check `agent-wrapper status` after some traces should have been sent to the datadog agent. It looks like it received some traces and spans, but did not write any.

```
=========
APM Agent
=========
  Status: Running
  Pid: 91
  Uptime: 2485 seconds
  Mem alloc: 10,203,784 bytes
  Hostname: redacted
  Receiver: localhost:8126
  Endpoints:
    https://trace.agent.datadoghq.com

  Receiver (previous minute)
  ==========================
    From ruby 3.0.5 (ruby-x86_64-linux), client 1.9.0
      Traces received: 3 (16,694 bytes)
      Spans received: 26

  Writer (previous minute)
  ========================
    Traces: 0 payloads, 0 traces, 0 events, 0 bytes
    Stats: 0 payloads, 0 stats buckets, 0 bytes
```

Enabling tracer debug logging and agent debug logging, I have many log entries showing that traces were dropped with reason `trace_id_zero` even though the trace id is not zero.

```
"2023-02-24T00:12:08.794Z","2023-02-24 00:12:08 UTC | TRACE | DEBUG | (run.go:254 in Debugf) | Dropping invalid trace: TraceID is zero (reason:trace_id_zero):"
"2023-02-24T00:12:08.794Z","2023-02-24 00:12:08 UTC | TRACE | DEBUG | (run.go:254 in Debugf) | Dropping invalid trace: TraceID is zero (reason:trace_id_zero):"
"2023-02-24T00:12:08.793Z","2023-02-24 00:12:08 UTC | TRACE | DEBUG | (run.go:254 in Debugf) | Dropping invalid trace: TraceID is zero (reason:trace_id_zero):"
"2023-02-24T00:12:08.793Z","2023-02-24 00:12:08 UTC | TRACE | DEBUG | (run.go:254 in Debugf) | Dropping invalid trace: TraceID is zero (reason:trace_id_zero):"
"2023-02-24T00:12:08.792Z","D, [2023-02-24T00:12:08.792163 DataDog/dd-trace-rb#12] DEBUG -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/3.0.0/gems/ddtrace-1.9.0/lib/ddtrace/transport/traces.rb:104:in `encode_trace') Flushing trace: [{""error"":0,""meta"":{""dyno"":""worker.2"",""dynotype"":""worker"",""buildpackversion"":""dev"",""appname"":""redacted"",""version"":""6a32f6c"",""env"":""test"",""component"":""sidekiq"",""operation"":""job_fetch"",""_dd.p.dm"":""-0"",""language"":""ruby"",""runtime-id"":""2ec27768-db13-4f22-ae8f-e8b0e3c7b029""},""metrics"":{""_dd.top_level"":1.0,""_dd.agent_psr"":1.0,""process_id"":12.0,""_sampling_priority_v1"":1.0},""name"":""sidekiq.job_fetch"",""parent_id"":0,""resource"":""sidekiq.job_fetch"",""service"":""redacted-sidekiq"",""span_id"":2086167332410080375,""trace_id"":2392727949725510185,""type"":""worker"",""start"":1677197524510583577,""duration"":3314429210}]"
"2023-02-24T00:12:08.792Z","D, [2023-02-24T00:12:08.792307 DataDog/dd-trace-rb#10] DEBUG -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/3.0.0/gems/ddtrace-1.9.0/lib/ddtrace/transport/traces.rb:104:in `encode_trace') Flushing trace: [{""error"":0,""meta"":{""dyno"":""worker.1"",""dynotype"":""worker"",""buildpackversion"":""dev"",""appname"":""redacted"",""version"":""6a32f6c"",""env"":""test"",""component"":""sidekiq"",""operation"":""job_fetch"",""_dd.p.dm"":""-0"",""language"":""ruby"",""runtime-id"":""282fe37b-6191-460c-ab12-30cf9344af28""},""metrics"":{""_dd.top_level"":1.0,""_dd.agent_psr"":1.0,""process_id"":10.0,""_sampling_priority_v1"":1.0},""name"":""sidekiq.job_fetch"",""parent_id"":0,""resource"":""sidekiq.job_fetch"",""service"":""redacted-sidekiq"",""span_id"":2656744934175146795,""trace_id"":1313853397762386975,""type"":""worker"",""start"":1677197519694018631,""duration"":8532064151}]"
"2023-02-24T00:12:08.792Z","D, [2023-02-24T00:12:08.791920 DataDog/dd-trace-rb#10] DEBUG -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/3.0.0/gems/ddtrace-1.9.0/lib/ddtrace/transport/traces.rb:104:in `encode_trace') Flushing trace: [{""error"":0,""meta"":{""dyno"":""worker.1"",""dynotype"":""worker"",""buildpackversion"":""dev"",""appname"":""redacted"",""version"":""6a32f6c"",""env"":""test"",""component"":""sidekiq"",""operation"":""job_fetch"",""_dd.p.dm"":""-0"",""language"":""ruby"",""runtime-id"":""282fe37b-6191-460c-ab12-30cf9344af28""},""metrics"":{""_dd.top_level"":1.0,""_dd.agent_psr"":1.0,""process_id"":10.0,""_sampling_priority_v1"":1.0},""name"":""sidekiq.job_fetch"",""parent_id"":0,""resource"":""sidekiq.job_fetch"",""service"":""redacted-sidekiq"",""span_id"":1058185645200663099,""trace_id"":471997803240144647,""type"":""worker"",""start"":1677197525044067479,""duration"":3181524267}]"
"2023-02-24T00:12:08.791Z","D, [2023-02-24T00:12:08.791798 DataDog/dd-trace-rb#12] DEBUG -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/3.0.0/gems/ddtrace-1.9.0/lib/ddtrace/transport/traces.rb:104:in `encode_trace') Flushing trace: [{""error"":0,""meta"":{""dyno"":""worker.2"",""dynotype"":""worker"",""buildpackversion"":""dev"",""appname"":""redacted"",""version"":""6a32f6c"",""env"":""test"",""component"":""sidekiq"",""operation"":""job_fetch"",""_dd.p.dm"":""-0"",""language"":""ruby"",""runtime-id"":""2ec27768-db13-4f22-ae8f-e8b0e3c7b029""},""metrics"":{""_dd.top_level"":1.0,""_dd.agent_psr"":1.0,""process_id"":12.0,""_sampling_priority_v1"":1.0},""name"":""sidekiq.job_fetch"",""parent_id"":0,""resource"":""sidekiq.job_fetch"",""service"":""redacted-sidekiq"",""span_id"":2736959921115804281,""trace_id"":165718975896980251,""type"":""worker"",""start"":1677197520297913723,""duration"":7526597929}]"
```

**Environment**

* **ddtrace version:**
Attempting to upgrade from 0.54.2 to 1.9.0

* **Configuration block (`Datadog.configure ...`):**

After upgrading:

```ruby
require 'ddtrace/auto_instrument'

Datadog.configure do |c|
  c.env = 'test'
  c.service = 'redacted'
  # a git commit short sha
  c.version = '98fh802f'

  sidekiq_options = {
    service_name: "redacted-sidekiq",
    client_service_name: "redacted-sidekiq-client"
  }
  c.tracing.instrument(:sidekiq, **sidekiq_options)
  c.tracing.instrument(:rails, { request_queueing: true })
  c.tracing.instrument(:sneakers, { service_name: "redacted-sneakers" })

  # appsec
  c.appsec.enabled = true
  c.appsec.instrument(:rails)
end
```

* **Ruby version:**

  * Ruby 3.0.5

* **Operating system:**

  * [Ubuntu 20 Heroku-20 Stack](https://devcenter.heroku.com/articles/heroku-20-stack)
  * This is running in the Heroku "Private Space" dyno.

* **Relevant library versions:**

  * Rails 6.1.71

More output from `agent_wrapper status` command:

```
===============
Agent (v7.42.0)
===============

  Status date: 2023-02-24 00:01:35.625 UTC (1677196895625)
  Agent start: 2023-02-23 23:18:26.16 UTC (1677194306160)
  Pid: 82
  Go Version: go1.18.9
  Python Version: 3.8.16
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log File: /app/.apt/var/log/datadog/datadog.log
  Log Level: WARN

  Paths
  =====
    Config File: /app/.apt/etc/datadog-agent/datadog.yaml
    conf.d: /app/.apt/etc/datadog-agent/conf.d
    checks.d: /app/.apt/etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -1.667ms
    System time: 2023-02-24 00:01:35.625 UTC (1677196895625)

  Host Info
  =========
    bootTime: 2023-02-10 00:14:03 UTC (1675988043000)
    hostId: redacted
    kernelArch: x86_64
    kernelVersion: 4.4.0-1104-aws
    os: linux
    platform: ubuntu
    platformFamily: debian
    platformVersion: 20.04
    procs: 9
    uptime: 335h4m26s

  Hostnames
  =========
    host_aliases: [redacted]
    hostname: redacted
    socket-fqdn: redacted
    socket-hostname: redacted
    host tags:
      appname:redacted
      buildpackversion:dev
      dyno:web.1
      dynotype:web
    hostname provider: configuration

  Metadata
  ========
    agent_version: 7.42.0
    config_apm_dd_url:

    config_dd_url:

    config_logs_dd_url: 
    config_logs_socks5_proxy_address: 
    config_no_proxy: []
    config_process_dd_url: 
    config_proxy_http: 
    config_proxy_https:

    config_site: 
    feature_apm_enabled: true
    feature_cspm_enabled: false
    feature_cws_enabled: false
    feature_logs_enabled: false
    feature_networks_enabled: false
    feature_networks_gotls_enabled: false
    feature_networks_http_enabled: false
    feature_networks_https_enabled: false
    feature_otlp_enabled: false
    feature_process_enabled: false
    feature_processes_container_enabled: true
    flavor: agent
    hostname_source: configuration
    install_method_installer_version: heroku-dev
    install_method_tool: heroku
    install_method_tool_version: heroku
```

**Comment by marcotc** [comment]
👋 @ricksuggs, the traces and setup look correct from the Ruby Tracer side.

The agent error seems very specific, `(run.go:254 in Debugf) | Dropping invalid trace: TraceID is zero (reason:trace_id_zero):`, despite evidence that the trace ids are not zero.

**Comment by ricksuggs** [comment]
> 👋 @ricksuggs, the traces and setup look correct from the Ruby Tracer side.
> 
> The agent error seems very specific, `(run.go:254 in Debugf) | Dropping invalid trace: TraceID is zero (reason:trace_id_zero):`, despite evidence that the trace ids are not zero.

@marcotc Thank you for moving this to the correct repo.
I found where this logging originates from in the source code.
https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/agent/normalizer.go#L42

Maybe there is a problem parsing the trace payload??

**Comment by ricksuggs** [comment]
@marcotc This turned out to be an issue with the [msgpack_rails](https://github.com/lawgical/msgpack-rails) gem.
The gem is no longer maintained. It overrides some behavior of the [msgpack](https://github.com/msgpack/msgpack-ruby) gem, which ddtrace uses to serialize traces.
I resolved the issue by removing msgpack_rails from my Gemfile, and updating the code that was using it in my project to use msgpack directly.

**Comment by marcotc** [comment]
Thank you for the investigation, @ricksuggs!

I'll add a warning to the `ddtrace` project about using the archived `msgpack-rails` gem.

**Comment by marcotc** [comment]
Just to confirm, @ricksuggs: the issue you had is with https://rubygems.org/gems/msgpack-rails, not https://rubygems.org/gems/msgpack_rails, correct?

**Comment by ricksuggs** [comment]
> Just to confirm, @ricksuggs: the issue you had is with https://rubygems.org/gems/msgpack-rails, not https://rubygems.org/gems/msgpack_rails, correct?

It was https://rubygems.org/gems/msgpack_rails

**Comment by marcotc** [comment]
Thank you, @ricksuggs!
