### ISSUE TITLE
DNS check failed on K8s

### ISSUE THREAD

**Issue by zymzxq** [DataDog/datadog-agent#2066]
```
+Error: (dns_check.py:99) | DNS resolution of localhost has failed.
  +Traceback (most recent call last):
  +  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/dns_check/dns_check.py", line 89, in _check
  +    answer = resolver.query(hostname, rdtype=record_type)
  +  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/dns/resolver.py", line 910, in query
  +    raise NXDOMAIN
  +NXDOMAIN
```

**Issue:**
After upgrading 6.3.3, `/opt/datadog-agent/bin/agent/agent check dns_check` fails with  error above

**When on 6.3.2:**
It worked without problem

**Environment:**
We install dd agent on `ubuntu:latest` docker image which runs on K8s

**Comment by zymzxq** [comment]
Looks like relates to https://github.com/DataDog/datadog-trace-agent/pull/450
