### ISSUE TITLE
pyyaml dependency not mentioned in README

### ISSUE THREAD

**Issue by p-leger** [DataDog/datadog-agent#2211]
Hey :)

I installed `invoke` in a newly created virtualenv and ran 'invoke deps` which resulted in the error below. 

I was able to fix this with `pip install pyyaml`.

```python
Traceback (most recent call last):
  File "/home/philipp/go/src/github.com/datadog-agent/env/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/philipp/go/src/github.com/datadog-agent/env/lib/python2.7/site-packages/invoke/program.py", line 324, in run
    self.parse_collection()
  File "/home/philipp/go/src/github.com/datadog-agent/env/lib/python2.7/site-packages/invoke/program.py", line 408, in parse_collection
    self.load_collection()
  File "/home/philipp/go/src/github.com/datadog-agent/env/lib/python2.7/site-packages/invoke/program.py", line 599, in load_collection
    module, parent = loader.load(coll_name)
  File "/home/philipp/go/src/github.com/datadog-agent/env/lib/python2.7/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/philipp/go/src/github.com/datadog-agent/tasks/__init__.py", line 7, in <module>
    from . import agent, android, benchmarks, customaction, docker, dogstatsd, pylauncher, cluster_agent, systray, release
  File "/home/philipp/go/src/github.com/datadog-agent/tasks/android.py", line 6, in <module>
    import yaml
ImportError: No module named yaml
```

Cheers

**Comment by truthbk** [comment]
Hi @p-leger, you have to install the python dependencies as well! Before running `invoke` make sure you run `pip install -r requirements.txt`. We now ship a [requirements file](https://github.com/DataDog/datadog-agent/blob/master/requirements.txt) to ensure all python dependencies are in place too.

I will make sure we update the README. Thank you for reporting this! 🙇

**Comment by p-leger** [comment]
Hey thanks for the quick answer.

Since the `requirements.txt` wasn't in the readme, I didn't realize that there was one :sweat_smile:. I tried it again with the `requirements.txt` and hat works like a charm. Maybe there should also be mention about `virtualenv` stuff in the README?

Another thing that tripped me up was the fact that my GOPATH was empty (eventhough I thought i set it, `go env` reported it correctly). That doesn't throw a proper error but breaks in `bootstrap.py` line 45. 
A proper error message would have saved me a couple of minutes :).

One last question, do you know, when you are planning on switching to python3?
