### ISSUE TITLE
[BUG] Datadog agent fails check with Portworx + Prometheus

### ISSUE THREAD

**Issue by aneesh-joshi-px** [DataDog/datadog-agent#22267]
**Agent Environment**
```
$ datadog-agent version
Agent 7.50.3 - Commit: abce0cb - Serialization version: v5.0.100 - Go version: go1.20.12
```

**Describe what happened:**
Tried setting up Datadog with Portworx integration with Prometheus.

- I installed the Datadog agent for Kubernetes from here: https://us3.datadoghq.com/signup/agent#kubernetes
- I integrated with Portworx using: https://docs.datadoghq.com/integrations/portworx/#overview
- I set up the Squid proxy to point it to the Datadog website
- I updated  `/etc/datadog-agent/conf.d/portworx.d/conf.yaml`  to use the prometheus endpoint as: http://localhost:9090/metrics
- I verified that the above actually exposes the metrics
- I installed the plugin for Portworx on the Datadog website

I didn't see any of the Portworx stats on the Datadog website.

When I checked the status, I saw the following error:
```
$ datadog-agent status
....
....
....
  Check Initialization Errors
  ===========================


      portworx (1.1.0)
      ----------------

      instance 0:

        could not invoke 'portworx' python check constructor. New constructor API returned:
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/portworx/portworx.py", line 13, in __init__
    super(PortworxCheck, self).__init__(name, init_config, instances)
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/prometheus/prometheus_base.py", line 31, in __init__
    super(PrometheusCheck, self).__init__(name, init_config, agentConfig, instances)
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/prometheus/mixins.py", line 58, in __init__
    super(PrometheusScraperMixin, self).__init__(*args, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 243, in __init__
    self.proxies = self._get_requests_proxy()
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 1126, in _get_requests_proxy
    proxies = self.agentConfig.get('proxy', datadog_agent.get_config('proxy'))
AttributeError: 'tuple' object has no attribute 'get'
Deprecated constructor API returned:
__init__() got an unexpected keyword argument 'agentConfig'
  Loading Errors
  ==============
    portworx
    --------
      Core Check Loader:
        Check portworx not found in Catalog

      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so

      Python Check Loader:
        could not configure check instance for python check portworx: could not invoke 'portworx' python check constructor. New constructor API returned:
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/portworx/portworx.py", line 13, in __init__
    super(PortworxCheck, self).__init__(name, init_config, instances)
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/prometheus/prometheus_base.py", line 31, in __init__
    super(PrometheusCheck, self).__init__(name, init_config, agentConfig, instances)
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/prometheus/mixins.py", line 58, in __init__
    super(PrometheusScraperMixin, self).__init__(*args, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 243, in __init__
    self.proxies = self._get_requests_proxy()
  File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 1126, in _get_requests_proxy
    proxies = self.agentConfig.get('proxy', datadog_agent.get_config('proxy'))
AttributeError: 'tuple' object has no attribute 'get'
Deprecated constructor API returned:
__init__() got an unexpected keyword argument 'agentConfig'
```

I followed the code and it looks like there is some incorrect expectations in the check where a `get` call in made on a tuple.

**Describe what you expected:**
Portworx data to be seen on Datadog.

**Steps to reproduce the issue:**
Install Portworx and run its datadog agent

**Additional environment details (Operating System, Cloud provider, etc):**
```
[root@anjoshi-41-0 ~]# uname -a
Linux  3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jacjtito** [comment]
Hello, I'm closing this stale issue with no activity. Feel free to reopen it if you have any question. Thanks!
