### ISSUE TITLE
Agent running in a pod crashes from time to time

### ISSUE THREAD

**Issue by alexandru-calinoiu** [DataDog/datadog-agent#22728]
It runs fine most of the time but it will usually crash once a day and the pod never restarts, looking at the log I see the following:

```
datadog-skkcv — raise CheckException(
datadog-skkcv — datadog_checks.base.errors.CheckException: The agent could not connect to any of the following URLs: ['https://172.31.0.79:2379/metrics', 'http://172.31.0.79:2379/metrics'].
datadog-skkcv — Deprecated constructor API returned:
datadog-skkcv — __init__() got an unexpected keyword argument 'agentConfig'
datadog-skkcv — 2024-02-09 07:16:00 UTC | CORE | ERROR | (pkg/collector/scheduler.go:208 in getChecks) | Unable to load a check from instance of config 'etcd': JMX Check Loader: check is not a jmx check, or unable to determine if it's so; Python Check Loader: could not configure check instance for python check etcd: could not invoke 'etcd' python check constructor. New constructor API returned:
datadog-skkcv — Traceback (most recent call last):
datadog-skkcv — File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/etcd/etcd.py", line 74, in __init__
datadog-skkcv — super(Etcd, self).__init__(
datadog-skkcv — File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/openmetrics/base_check.py", line 126, in __init__
datadog-skkcv — raise CheckException(
datadog-skkcv — datadog_checks.base.errors.CheckException: The agent could not connect to any of the following URLs: ['https://172.31.0.79:2379/metrics', 'http://172.31.0.79:2379/metrics'].
datadog-skkcv — Deprecated constructor API returned:
datadog-skkcv — __init__() got an unexpected keyword argument 'agentConfig'; Core Check Loader: Check etcd not found in Catalog
```

**Comment by alexandru-calinoiu** [comment]
The problem gets solved by redeploying the pod, but this is very inconvenient.
