### ISSUE TITLE
[BUG] ConnectionResetError when enabling MTLS for Istio mesh with Datadog integration

### ISSUE THREAD

**Issue by AkramDhiabi** [DataDog/datadog-agent#23136]
Summary:
Enabling Mutual TLS (MTLS) for the entire Istio mesh causes loss of application metrics, and the Datadog agent reports a ConnectionResetError in the logs.

Environment:
Istio version: 1.20.2
Datadog agent version: 7.50.3
Kubernetes version: 1.28
MTLS configuration: Enabled for the entire Istio mesh

Issue Description:
When MTLS is enabled for the entire Istio mesh, the Datadog agent encounters a ConnectionResetError, leading to the loss of application metrics. The error message indicates that the connection is being reset by peer.

Steps to Reproduce:
1- Deploy Istio with Datadog integration.
2- Enable MTLS for the entire Istio mesh.
3- Observe the Datadog agent logs for ConnectionResetError.

Expected Behavior:
Enabling MTLS by sidecarInjectorWebhook for the mesh should not result in a ConnectionResetError, and Datadog should continue to collect and report application metrics.

Additional Information:

IstioD configuration:

```
sidecarInjectorWebhook:
  # This enables injection of sidecar in all namespaces,
  enableNamespacesByDefault: false
  templates:
    metricsProxy: |
      metadata:
        annotations:
          sidecar.istio.io/statsHistogramBuckets: '{"istio":[1,5,10,25,50,75,100,125,150,200,250,300,400,500,1000,2500,5000,10000,30000] ,"envoy":[1,5,10,25,50,75,100,125,150,200,250,300,400,500,1000,2500,5000,10000,30000]}'  
          ad.datadoghq.com/istio-proxy.check_names: '["openmetrics"]'
          ad.datadoghq.com/istio-proxy.init_configs: '[{}]'
          ad.datadoghq.com/istio-proxy.instances: |
            [{"openmetrics_endpoint": "http://%%host%%:15090/stats/prometheus", "histogram_buckets_as_distributions": true,"collect_counters_with_distributions":true,"namespace": "mind.events","exclude_metrics": ["envoy_*"],"metrics": [".*"], "max_returned_metrics": 4000}]
      spec:
        containers:
        - name: istio-proxy
          env:
          - name: TRACER.SERVICEVERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
    metricsAppGo: |
      metadata:
        annotations:
          ad.datadoghq.com/server.check_names: '["openmetrics"]'                          
          ad.datadoghq.com/server.init_configs: '[{}]'
          ad.datadoghq.com/server.instances: |
            [{"prometheus_url": "http://%%host%%:8082/metrics", "histogram_buckets_as_distributions": true,"collect_counters_with_distributions":true,"namespace": "mind.events","metrics": ["*"], "max_returned_metrics": 4000}]
pilot:
  replicaCount: 2
  autoscaleMin: 2
  podAnnotations:
      ad.datadoghq.com/discovery.check_names: '["istio"]'
      ad.datadoghq.com/discovery.init_configs: '[{}]'
      ad.datadoghq.com/discovery.instances: |
        [
          {
            "istiod_endpoint": "http://%%host%%:15014/metrics",
            "use_openmetrics": "true",
          }
        ]
```

ERROR when running `agent status`

```
Instance ID: openmetrics:mind.events:87de420e263b3732 [ERROR]
      Configuration Source: container:containerd://26e653ce3249a1dcb9bb80687686fa7666da94231f1e15dcd36ff30df900f8e7
      Total Runs: 3
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 3
      Average Execution Time : 10ms
      Last Execution Date : 2024-02-26 11:36:23 UTC (1708947383000)
      Last Successful Execution Date : Never
      Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
          httplib_response = self._make_request(
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
          six.raise_from(e, None)
        File "<string>", line 3, in raise_from
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/urllib3/connectionpool.py", line 462, in _make_request
          httplib_response = conn.getresponse()
        File "/opt/datadog-agent/embedded/lib/python3.9/http/client.py", line 1377, in getresponse
          response.begin()
        File "/opt/datadog-agent/embedded/lib/python3.9/http/client.py", line 320, in begin
          version, status, reason = self._read_status()
        File "/opt/datadog-agent/embedded/lib/python3.9/http/client.py", line 281, in _read_status
          line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
        File "/opt/datadog-agent/embedded/lib/python3.9/socket.py", line 704, in readinto
          return self._sock.recv_into(b)
      ConnectionResetError: [Errno 104] Connection reset by peer
      During handling of the above exception, another exception occurred:
```

**Comment by AkramDhiabi** [comment]
@legal90  when mtls is widely enabled. you can make use of both service annotations:
traffic.sidecar.istio.io/excludeInboundPorts and traffic.sidecar.istio.io/excludeOutboundPorts
To exclude the ports from being intercepted by envoy mtls.

**Comment by legal90** [comment]
Thank you, @AkramDhiabi ! I confirm - That could be a solution too. 
Just `traffic.sidecar.istio.io/excludeInboundPorts` annotation is enough in that case:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  # ...
spec:
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "8080"  # <= Now datadog-agent can access `http://%%host%%:8080/*`
  # ...
```

But that should be done with a caution, as it affects security negatively. 
That should be a dedicate port number which is only used to serve https check or metrics endpoint. Other type of traffic should still be served through the non-excluded ports, with mTLS enforced.

**Comment by FalconerTC** [comment]
Is there a solution for applications that server metrics on the same port as the main web server? There has to be a better approach here
