### ISSUE TITLE
[BUG]  ArrayIndexOutOfBoundsException at com.datadoghq.profiler.JavaProfiler.getPage(JavaProfiler.java:267)

### ISSUE THREAD

**Issue by andron3000** [DataDog/datadog-agent#23132]
**Agent Environment**
 dd-java-agent: 1.9.0

**Describe what happened:**
Intermitted errors from dd-java-agent

Stack-trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1953 out of bounds for length 1953
	at com.datadoghq.profiler.JavaProfiler.getPage(JavaProfiler.java:267)
	at com.datadoghq.profiler.JavaProfiler.setContextByteBuffer(JavaProfiler.java:256)
	at com.datadoghq.profiler.JavaProfiler.setContext(JavaProfiler.java:236)
	at com.datadog.profiling.ddprof.DatadogProfiler.setContext(DatadogProfiler.java:327)
	at com.datadog.profiling.ddprof.DatadogProfilingIntegration.setContext(DatadogProfilingIntegration.java:36)
	at datadog.trace.agent.core.scopemanager.ScopeStack.onTopChanged(ScopeStack.java:116)
	at datadog.trace.agent.core.scopemanager.ScopeStack.push(ScopeStack.java:61)
	at datadog.trace.agent.core.scopemanager.ContinuableScopeManager.activate(ContinuableScopeManager.java:141)
	at datadog.trace.agent.core.scopemanager.ContinuableScopeManager.activate(ContinuableScopeManager.java:98)
	at datadog.trace.agent.core.CoreTracer.activateSpan(CoreTracer.java:698)
	at datadog.trace.bootstrap.instrumentation.api.AgentTracer.activateSpan(AgentTracer.java:48)
	at datadog.trace.instrumentation.springdata.RepositoryInterceptor.invoke(RepositoryInterceptor.java:38)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
```

**Additional environment details (Operating System, Cloud provider, etc):
Java version: 17, Spring boot version: 2.6.6,

**Comment by andron3000** [comment]
Response provided
https://github.com/DataDog/java-profiler/issues/76
