### ISSUE TITLE
DataDog agent segmentation fault

### ISSUE THREAD

**Issue by ambrusadrianz** [DataDog/datadog-agent#2337]
**Describe what happened:**

Upgraded to the latest DataDog agent (version `6.5.1`), the agent is working for ~1 minute, but after that it fails with the following error:

```
[ AGENT ] panic: runtime error: invalid memory address or nil pointer dereference
[ AGENT ] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16292e6]
[ AGENT ]
[ AGENT ] goroutine 594 [running]:
[ AGENT ] github.com/DataDog/datadog-agent/pkg/logs/input/docker.(*Tailer).Stop(0xc42002c500)
[ AGENT ] /go/src/github.com/DataDog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/input/docker/tailer.go:75 +0xf6
[ AGENT ] created by github.com/DataDog/datadog-agent/pkg/logs/input/docker.(*Launcher).stopTailer
[ AGENT ] /go/src/github.com/DataDog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/input/docker/launcher.go:179 +0x8b
[ AGENT ] AGENT EXITED WITH CODE 2, SIGNAL 0, KILLING CONTAINER
[ TRACE ] 2018-09-19 13:30:39 INFO (main.go:35) - received signal 15 (terminated)
[ TRACE ] 2018-09-19 13:30:39 INFO (agent.go:161) - exiting
[ TRACE ] 2018-09-19 13:30:39 INFO (concentrator.go:75) - exiting concentrator, computing remaining stats
[ TRACE ] 2018-09-19 13:30:39 INFO (trace_writer.go:129) - exiting trace writer, flushing all remaining traces
[ TRACE ] 2018-09-19 13:30:39 INFO (trace_writer.go:132) - Flushed. Exiting
[PROCESS] process-agent exited with code 0, disabling
[ TRACE ] 2018-09-19 13:30:40 INFO (payload.go:212) - exiting payload sender, try flushing whatever is left
[ TRACE ] 2018-09-19 13:30:40 INFO (trace_writer.go:98) - flushed trace payload to the API, time:344.401234ms, size:2762 bytes
[ TRACE ] 2018-09-19 13:30:40 INFO (stats_writer.go:84) - exiting stats writer
[ TRACE ] 2018-09-19 13:30:40 INFO (payload.go:212) - exiting payload sender, try flushing whatever is left
[ TRACE ] 2018-09-19 13:30:40 INFO (service_writer.go:106) - exiting service writer, flushing all modified services
[ TRACE ] 2018-09-19 13:30:40 INFO (payload.go:212) - exiting payload sender, try flushing whatever is left
[ TRACE ] trace-agent exited with code 0, disabling
```

**Additional environment details (Operating System, Cloud provider, etc):**

We are running the agent with ECS on AWS.

**Comment by ajacquemot** [comment]
Hi @ambrusadrianz,

Thanks for opening this issue, we've been able to identify the root cause and fix it.
The fix should be included in the next release of the agent happening in the coming days.
