### ISSUE TITLE
[BUG]  serverless-init - SIGSEGV when statd port already in use with GCP Cloud Run 

### ISSUE THREAD

**Issue by piotrekkr** [DataDog/datadog-agent#26599]
**Agent Environment**

Using binary from docker image datadog/serverless-init:1.1.4

**Describe what happened:**

When `statd` port is already taken `serverless-init` binary crashes with SISEGV error

![image](https://github.com/DataDog/datadog-agent/assets/503782/9d6fa9be-df10-4665-8be5-247d18b9100c)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe387f5]

goroutine 1 [running]:
github.com/DataDog/datadog-agent/cmd/serverless-init/metric.add({0xc00004fa00?, 0x1?}, {0x0?, 0x16f63f0?, 0x8?}, {0x16f63f0?, 0x8?, 0x260e020?}, {0x0, 0x0})
	/tmp/dd/datadog-agent/cmd/serverless-init/metric/metric.go:33 +0x135
github.com/DataDog/datadog-agent/cmd/serverless-init/metric.AddColdStartMetric({0x16f492b?, 0x1?}, {0x0, 0x0, 0x0}, {0x0?, 0x0?, 0x0?}, {0x0, 0x0})
	/tmp/dd/datadog-agent/cmd/serverless-init/metric/metric.go:21 +0xc5
main.setup()
	/tmp/dd/datadog-agent/cmd/serverless-init/main.go:118 +0x61f
main.run(0xc00040e210)
	/tmp/dd/datadog-agent/cmd/serverless-init/main.go:62 +0x18
reflect.Value.call({0x1441ba0?, 0x1784590?, 0x10?}, {0x16f1331, 0x4}, {0xc00040e4b0, 0x1, 0xc000617cf0?})
	/usr/local/go/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0x1441ba0?, 0x1784590?, 0x190faa8?}, {0xc00040e4b0?, 0x0?, 0x0?})
	/usr/local/go/src/reflect/value.go:380 +0xb9
github.com/DataDog/datadog-agent/pkg/util/fxutil.(*delayedFxInvocation).call(0xc000135790?)
	/tmp/dd/datadog-agent/pkg/util/fxutil/args.go:72 +0x8e
github.com/DataDog/datadog-agent/pkg/util/fxutil.OneShot({0x1441ba0?, 0x1784590?}, {0xc0007060a0, 0x1, 0x1})
	/tmp/dd/datadog-agent/pkg/util/fxutil/oneshot.go:54 +0x327
main.main()
	/tmp/dd/datadog-agent/cmd/serverless-init/main.go:54 +0x111
```

I know that there are some messages about statd port already in use but exiting with `SIGSEGV` is a bit extreme imo.

**Describe what you expected:**

In best case scenario I would expect some warning and then just DD agent not sending any metrics at all. In slightly worse scenario expected behavior would be to just exit with some nice message saying that cannot continue due to statd issue.

**Steps to reproduce the issue:**

Deploy cloud run service **with two containers** inside. One depending on another, both of them using `serverless-init` as entrypoint with default statd port `8125`.

**Comment by jcstorms1** [comment]
Hi @piotrekkr thanks for opening this issue. I'm currently investigating why we exit with `SIGSEGV` in this case. In the meantime, the current workaround would be to add `DD_DOGSTATSD_PORT` with something other than `8125` in the additional container.

**Comment by piotrekkr** [comment]
@jcstorms1 Hi. Thanks for your reply. This is exactly what we do currently as a workaround but would be nice to have it handled properly on dd side. Thanks.

**Comment by piotrekkr** [comment]
@jcstorms1 Hi. Thanks for the link looked at it and seems like interesting idea. Not sure why same env vars are set on both main app container and sidecar. Should it not be only sidecar to have most of those env vars? I understand shared empty dir volume path need to be set on main app so it will know where to write logs but the rest is only used by side container, no?

**Comment by jcstorms1** [comment]
@piotrekkr the env vars are not shared across containers unfortunately. This means things like `DD_ENV` or `DD_SERVICE` would need to be on both containers to make sure the libraries and agents have access to them.

**Comment by piotrekkr** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/503782?s=64&amp;v=4">@piotrekkr](https://github.com/piotrekkr?rgh-link-date=2025-01-15T14%3A35%3A06.000Z) the env vars are not shared across containers unfortunately. This means things like `DD_ENV` or `DD_SERVICE` would need to be on both containers to make sure the libraries and agents have access to them.

@jcstorms1 Yeah I understand that containers do not share env vars but my question is more if containers beside sidecar with serverless init need all those env vars for some reason. Assuming I have some simple app that is handling requests and writing logs to shared volume, then this app, by itself, will probably do not need `DD_ENV`, `DD_SITE`, `DD_API_KEY` etc. It will just need `DD_SERVERLESS_LOG_PATH` to know where to write logs. Most of those env vars is needed only by serverless init sidecar. Am I wrong?

**Comment by jcstorms1** [comment]
Hey @piotrekkr let me double check all of these and update the docs I shared. `DD_SERVERLESS_LOG_PATH` is only required for the sidecar container, but your application needs to be set up to write to that path. I'll get back to you once I confirm the rest of the env vars. Thanks for the questions.

**Comment by jcstorms1** [comment]
@piotrekkr the changes to the documentation is done. Thanks for pointing out the extra environment variables.
