### ISSUE TITLE
HTTP check encoding bug

### ISSUE THREAD

**Issue by storytime** [DataDog/datadog-agent#2758]
**Output of the info page (if this is a bug)**
```
 http_check (3.0.0)
    ------------------
        Instance ID: http_check:b127574ebb31fe13 [ERROR]
        Total Runs: 9
        Metric Samples: 5, Total: 45
        Events: 0, Total: 0
        Service Checks: 0, Total: 0
        Average Execution Time : 3.48s
        Error: 'ascii' codec can't decode byte 0xc3 in position 37: ordinal not in range(128)
        Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 366, in run
          self.check(copy.deepcopy(self.instances[0]))
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/network.py", line 44, in check
          self.report_as_service_check(sc_name, status, instance, msg)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/http_check/http_check.py", line 225, in report_as_service_check
          tags.append("instance:{}".format(instance_name))
      UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 37: ordinal not in range(128)
```

**Describe what happened:**
I'm checking the several external systems by using the HTTP module. 
Http check is crashed on one check.  But system is UP.  Probably system returns not UTF-8 symbols. 
 
**Describe what you expected:**
    
    file_handle
    -----------
        Instance ID: file_handle [OK]
        Total Runs: 9
        Metric Samples: 5, Total: 45
        Events: 0, Total: 0
        Service Checks: 0, Total: 0
        Average Execution Time : 0s

**Steps to reproduce the issue:**
Try to check URL that return not UTF symbols.

**Additional environment details (Operating System, Cloud provider, etc):**
 
> uname -a

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

> locale

LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

>datadog-agent version

Agent 6.7.0 - Commit: 2555a01 - Serialization version: 4.7.1

**How I fix the issue (dirty fix)** 
I've added next code to: http_check.py

`import sys`
`reload(sys)`
`sys.setdefaultencoding('utf8')`

**Comment by zippolyte** [comment]
Hey @storytime, thanks for the report !
This looks like an issue that is solved by https://github.com/DataDog/integrations-core/pull/2435.
This fix to the check will be included in agent version 6.8.0 that will be released really soon, likely by the end of the week. Once it is available, would you be willing to try it out and tell us whether your issue is resolved ?
Thanks !
