### ISSUE TITLE
invoke deps fail

### ISSUE THREAD

**Issue by piscue** [DataDog/datadog-agent#2894]
Running the invoke deps:

```
Traceback (most recent call last):
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/lib/python3.7/site-packages/invoke/program.py", line 321, in run
    self.parse_collection()
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/lib/python3.7/site-packages/invoke/program.py", line 399, in parse_collection
    self.load_collection()
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/lib/python3.7/site-packages/invoke/program.py", line 588, in load_collection
    module, parent = loader.load(coll_name)
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/lib/python3.7/site-packages/invoke/loader.py", line 75, in load
    module = imp.load_module(name, fd, path, desc)
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/tasks/__init__.py", line 7, in <module>
    from . import agent, android, benchmarks, customaction, docker, dogstatsd, pylauncher, cluster_agent, systray, release
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/tasks/pylauncher.py", line 14, in <module>
    PYLAUNCHER_BIN_PATH = os.path.join(get_root(), "bin", "pylauncher")
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/bin/../lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/piscue/go/src/github.com/DataDog/datadog-agent/venv/bin/../lib/python3.7/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

I followed this guide, setting pipenv and the recommendations [Setting up your development environment](https://github.com/DataDog/datadog-agent/blob/master/docs/dev/agent_dev_env.md)

**Steps to reproduce the issue:**
Trying to setup a developer environment to build the agent on OSX Mojave

**Comment by xvello** [comment]
hi @piscue 
As our agent runs with python2.7, please try running invoke in a python2.7 venv

**Comment by piscue** [comment]
@xvello absolutely right, I just made a quick PR to clarify it #2895

**Comment by xvello** [comment]
Thanks! Closing this
