### ISSUE TITLE
error reading AWS storage metrics with EBS of type NVME

### ISSUE THREAD

**Issue by overratedpro** [DataDog/datadog-agent#2912]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

==============
Agent (v6.8.3)
==============

  Status date: 2019-01-21 14:02:44.877298 UTC
  Pid: 370
  Python Version: 2.7.15
  Logs: 
  Check Runners: 6
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 450µs
    System UTC time: 2019-01-21 14:02:44.877298 UTC

  Host Info
  =========
    bootTime: 2019-01-04 14:42:24.000000 UTC
    kernelVersion: 4.19.9-coreos
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: buster/sid
    procs: 78
    uptime: 407h9m42s
    virtualizationRole: guest
    virtualizationSystem: docker

  Hostnames
  =========
    ec2-hostname: <MUNGED>
    hostname: <MUNGED>
    instance-id: <MUNGED>
    socket-fqdn: <MUNGED>
    socket-hostname: <MUNGED>
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance, and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

=========
Collector
=========

  Running Checks
  ==============
    
    cpu
    ---
      Instance ID: cpu [[32mOK[0m]
      Total Runs: 43
      Metric Samples: Last Run: 6, Total: 252
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    disk (2.0.0)
    ------------
      Instance ID: disk: <MUNGED> [[31mERROR[0m]
      Total Runs: 42
      Metric Samples: Last Run: 456, Total: 19,152
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 202ms
      Error: not sure how to interpret line ' 259       0 nvme1n1 4874118 330 144870634 16073394 27734110 51761248 1389117360 54415939 0 32198573 69979855 0 0 0 0\n'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 374, in run
          self.check(copy.deepcopy(self.instances[0]))
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/disk/disk.py", line 59, in check
          self.collect_metrics_psutil()
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/disk/disk.py", line 128, in collect_metrics_psutil
          self.collect_latency_metrics()
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/disk/disk.py", line 255, in collect_latency_metrics
          for disk_name, disk in iteritems(psutil.disk_io_counters(True)):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil/__init__.py", line 2026, in disk_io_counters
          rawdict = _psplatform.disk_io_counters(**kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil/_pslinux.py", line 1115, in disk_io_counters
          for entry in gen:
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil/_pslinux.py", line 1088, in read_procfs
          raise ValueError("not sure how to interpret line %r" % line)
      ValueError: not sure how to interpret line ' 259       0 nvme1n1 4874118 330 144870634 16073394 27734110 51761248 1389117360 54415939 0 32198573 69979855 0 0 0 0\n'
    
    docker
    ------
      Instance ID: docker [[32mOK[0m]
      Total Runs: 43
      Metric Samples: Last Run: 200, Total: 8,598
      Events: Last Run: 0, Total: 2
      Service Checks: Last Run: 1, Total: 43
      Average Execution Time : 46ms
      
    
    elastic (1.9.1)
    ---------------
      Instance ID: elastic: <MUNGED> [[32mOK[0m]
      Total Runs: 43
      Metric Samples: Last Run: 179, Total: 7,697
      Events: Last Run: 0, Total: 1
      Service Checks: Last Run: 2, Total: 86
      Average Execution Time : 23ms
      
    
    file_handle
    -----------
      Instance ID: file_handle [[32mOK[0m]
      Total Runs: 42
      Metric Samples: Last Run: 5, Total: 210
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    io
    --
      Instance ID: io [[32mOK[0m]
      Total Runs: 43
      Metric Samples: Last Run: 130, Total: 5,500
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    load
    ----
      Instance ID: load [[32mOK[0m]
      Total Runs: 42
      Metric Samples: Last Run: 6, Total: 252
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    memory
    ------
      Instance ID: memory [[32mOK[0m]
      Total Runs: 43
      Metric Samples: Last Run: 17, Total: 731
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    network (1.8.0)
    ---------------
      Instance ID: network: <MUNGED> [[32mOK[0m]
      Total Runs: 42
      Metric Samples: Last Run: 104, Total: 4,368
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      
    
    ntp
    ---
      Instance ID: ntp: <MUNGED> [[32mOK[0m]
      Total Runs: 43
      Metric Samples: Last Run: 1, Total: 43
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 43
      Average Execution Time : 0s
      
    
    uptime
    ------
      Instance ID: uptime [[32mOK[0m]
      Total Runs: 42
      Metric Samples: Last Run: 1, Total: 42
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
========
JMXFetch
========

  Initialized checks
  ==================
    jmx
      instance_name : <MUNGED>
      message : Cannot connect to instance <MUNGED>. java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
      metric_count : 0
      service_check_count : 0
      status : ERROR
      instance_name : <MUNGED>
      message : Cannot connect to instance <MUNGED>. java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
      metric_count : 0
      service_check_count : 0
      status : ERROR
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 42
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 6
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 90
    TimeseriesV1: 42

  API Keys status
  ===============
    API key ending with <MUNGED> on endpoint https://app.datadoghq.com: API Key valid

==========
Logs Agent
==========

  Logs Agent is not running

=========
Aggregator
=========
  Checks Metric Sample: 47,696
  Dogstatsd Metric Sample: 3,056
  Event: 4
  Events Flushed: 4
  Number Of Flushes: 42
  Series Flushed: 30,824
  Service Check: 686
  Service Checks Flushed: 714

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 3,056
  Metric Parse Errors: 0
  Service Check Packets: 88
  Service Check Parse Errors: 0
```

**Describe what happened:**

Traceback during collecting metrics for block device of type NVME and consequently no data collected for the following graphs in the DataDog infrastructure view for the EC2 instance: "EC2 Disk IO", "EC2: Read Disk Ops", "EC2: Write Disk Ops".

**Describe what you expected:**

Successful metrics collection. Also, graphs for  "EC2 Disk IO", "EC2: Read Disk Ops", "EC2: Write Disk Ops" on the DD infrastructure page for the EC2 instance.

**Steps to reproduce the issue:**

Run DataDog docker agent (datadog/agent:6.8.3-jmx) on a m5-class instance (with NVME EBS volumes) on AWS. 

**Additional environment details (Operating System, Cloud provider, etc):**

CoreOS on an AWS m5-large instance.

**Comment by streetmanagerops** [comment]
+1

**Comment by overratedpro** [comment]
Can be fixed with an upgrade of psutil: `pip install psutil==5.5.0`

**Comment by kutzi** [comment]
Is this fixed with a new agent version?
We're running and still seeing the same message

**Comment by kutzi** [comment]
Also psutil is already on version 5.6.7 in that image
