### ISSUE TITLE
panic on android

### ISSUE THREAD

**Issue by yonderblue** [DataDog/datadog-agent#2924]
Similar to https://github.com/DataDog/gohai/issues/57 i'm trying to build and run on an android box with `GOOS=android GOARCH=arm GOARM=7 CGO_ENABLED=1 go generate ./info` and `GOOS=android GOARCH=arm GOARM=7 CGO_ENABLED=1 go build -o trace-agent ./cmd/trace-agent`

But when running on the box, it works and I see profile's in datadog site, but then panics.

Couple other questions I could find in the repos/site:
Does the trace agent have to be manually run along side the regular agent? Or does the regular agent start it if located in a certain place?
Does the trace agent depend on the regular agent for functionality or upload to datadog on it's own?
I don't see a "service" in the datadog site created, only point in time profile's?

```
2018-06-26 23:23:13 DEBUG (sampler.go:105) - *sampler.ScoreEngine: inTPS: 0.027939, outTPS: 0.027939, maxTPS: 10.000000, offset: 1.000000, slope: 3.000000, cardinality: 1
seelog internal error: mkdir /var: read-only file system
2018-06-26 23:23:13 DEBUG (trace_writer.go:124) - Flushing current traces
seelog internal error: mkdir /var: read-only file system
2018-06-26 23:23:13 DEBUG (stats_writer.go:107) - going to flush 3 entries in 1 stat buckets in 1 payloads
seelog internal error: mkdir /var: read-only file system
2018-06-26 23:23:13 ERROR (logonpanic.go:38) - Unexpected panic: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
github.com/DataDog/datadog-trace-agent/watchdog.LogOnPanic()
	/go/src/github.com/DataDog/datadog-trace-agent/watchdog/logonpanic.go:29 +0x84
panic(0xab8690d8, 0xabab6688)
	/usr/local/go/src/runtime/panic.go:505 +0x218
sync/atomic.addUint64(0xbc742264, 0x1, 0x0, 0x3, 0x3)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/DataDog/datadog-trace-agent/writer.(*StatsWriter).handleStats(0xbc742240, 0xbc7f43e0, 0x1, 0x1)
	/go/src/github.com/DataDog/datadog-trace-agent/writer/stats_writer.go:114 +0x1a4
github.com/DataDog/datadog-trace-agent/writer.(*StatsWriter).Run(0xbc742240)
	/go/src/github.com/DataDog/datadog-trace-agent/writer/stats_writer.go:82 +0xd4
github.com/DataDog/datadog-trace-agent/writer.(*StatsWriter).Start.func1(0xbc742240)
	/go/src/github.com/DataDog/datadog-trace-agent/writer/stats_writer.go:62 +0x3c
created by github.com/DataDog/datadog-trace-agent/writer.(*StatsWriter).Start
	/go/src/github.com/DataDog/datadog-trace-agent/writer/stats_writer.go:60 +0x40
```

**Comment by ajgajg1134** [comment]
Closing this issue for inactivity. If you still experience this issue feel free to re-open. Thanks!
