### ISSUE TITLE
mysql check: ValueError: dictionary update sequence element #0 has length 3; 2 is required

### ISSUE THREAD

**Issue by Zenexer** [DataDog/datadog-agent#3014]
Not too sure what's going on here:

```
INFO (collector.py:415): Running check mysql
ERROR (mysql.py:317): error!
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mysql/mysql.py", line 310, in check
    self._collect_metrics(db, tags, options, queries, max_custom_queries)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mysql/mysql.py", line 487, in _collect_metrics
    'Binlog_space_usage_bytes'] = self._get_binary_log_stats(db)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mysql/mysql.py", line 853, in _get_binary_log_stats
    master_logs = dict(cursor.fetchall())
ValueError: dictionary update sequence element #0 has length 3; 2 is required
ERROR (__init__.py:840): Check 'mysql' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 823, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mysql/mysql.py", line 318, in check
    raise e
ValueError: dictionary update sequence element #0 has length 3; 2 is required
INFO (transaction.py:190): No transaction to flush during flush #1
```

``` yaml
init_config:

instances:
    # NOTE: Even if the server name is "localhost", the agent will connect to MySQL using TCP/IP, unless you also
    # provide a value for the sock key (below).
  - server: localhost
    user: datadog
    pass: "redacted"
    sock: /run/mysqld/mysqld.sock
    options:
      replication: true
      replication_non_blocking_status: true
      extra_status_metrics: true
      extra_innodb_metrics: true
      extra_performance_metrics: true
      schema_size_metrics: true
    tags:
      - 'dbinstanceidentifier:redacted-0'
      - 'application:redacted'
      - 'stage:redacted'
      - 'service:redacted'
      - 'role:redacted-redacted'
```

**Comment by Zenexer** [comment]
```
$ dpkg -s datadog-agent
Package: datadog-agent
Status: install ok installed
Priority: extra
Section: utils
Installed-Size: 306058
Maintainer: Datadog Packages <package@datadoghq.com>
Architecture: amd64
Version: 1:5.31.0-1
Replaces: datadog-agent-base (<< 5.0.0), datadog-agent-lib (<< 5.0.0)
Conflicts: datadog-agent-base (<< 5.0.0)
Description: Datadog Monitoring Agent
  The Datadog Monitoring Agent is a lightweight process that monitors system
  processes and services, and sends information back to your Datadog account.
  .
  This package installs and runs the advanced Agent daemon, which queues and
  forwards metrics from your applications as well as system services.
  .
  See http://www.datadoghq.com/ for more information
License: Simplified BSD License
Vendor: Datadog <info@datadoghq.com>
Homepage: http://www.datadoghq.com
```

```
$ dpkg -s mysql-community-server
Package: mysql-community-server
Status: install ok installed
Priority: optional
Section: database
Installed-Size: 147793
Maintainer: MySQL Release Engineering <mysql-build@oss.oracle.com>
Architecture: amd64
Source: mysql-community
Version: 8.0.15-1ubuntu18.04
Replaces: mysql, mysql-cluster-commercial-server, mysql-cluster-community-server, mysql-commercial-server, mysql-common (<< 5.7.14), mysql-community-client (<< 5.7), mysql-server-5.0, mysql-server-5.1, mysql-server-5.5, mysql-server-5.6, mysql-server-5.7, mysql-server-core-5.0, mysql-server-core-5.1, mysql-server-core-5.5, mysql-server-core-5.6, mysql-server-core-5.7
Provides: virtual-mysql-server
Depends: mysql-common (>= 8.0.15-1ubuntu18.04), mysql-client (= 8.0.15-1ubuntu18.04), mysql-community-server-core (= 8.0.15-1ubuntu18.04), perl, psmisc, libaio1 (>= 0.3.93), libc6 (>= 2.17), libgcc1 (>= 1:3.4), libmecab2, libnuma1 (>= 2.0.11), libsasl2-2, libssl1.1 (>= 1.1.0d), libstdc++6 (>= 7), debconf (>= 0.5) | debconf-2.0
Pre-Depends: debconf (>= 0.2.17), adduser
Breaks: mysql-common (<< 5.7.14), mysql-community-client (<< 5.7)
Conflicts: mariadb-client-10.0, mariadb-client-10.1, mariadb-client-10.2, mariadb-client-5.5, mariadb-client-core-10.0, mariadb-client-core-10.1, mariadb-client-core-10.2, mariadb-client-core-5.5, mariadb-server-10.0, mariadb-server-10.1, mariadb-server-10.2, mariadb-server-5.5, mariadb-server-core-10.0, mariadb-server-core-10.1, mariadb-server-core-10.2, mariadb-server-core-5.5, mysql, mysql-client-5.0, mysql-client-5.1, mysql-client-5.5, mysql-client-5.6, mysql-client-5.7, mysql-client-core-5.0, mysql-client-core-5.1, mysql-client-core-5.5, mysql-client-core-5.6, mysql-client-core-5.7, mysql-cluster-commercial-server, mysql-cluster-community-server, mysql-commercial-server, mysql-server-5.0, mysql-server-5.1, mysql-server-5.5, mysql-server-5.6, mysql-server-5.7, mysql-server-core-5.0, mysql-server-core-5.1, mysql-server-core-5.5, mysql-server-core-5.6, mysql-server-core-5.7
Conffiles:
 /etc/apparmor.d/usr.sbin.mysqld 424fef0612be6be074958da0a59bb5de
 /etc/mysql/mysql.cnf 155086ed1e6dc40d01bb471813c60c9f
 /etc/mysql/mysql.conf.d/mysqld.cnf 4b02bc25431f974867823b200a9b8700
Description: MySQL Server
 The MySQL(TM) software delivers a very fast, multi-threaded, multi-user,
 and robust SQL (Structured Query Language) database server. MySQL Server
 is intended for mission-critical, heavy-load production systems as well
 as for embedding into mass-deployed software. MySQL is a trademark of
 Oracle. This package includes the MySQL server binary as well as related
 utilities to run and administer a MySQL server.
Homepage: http://www.mysql.com/
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by dabcoder** [comment]
Thanks for reporting. This should fix it: https://github.com/DataDog/integrations-core/pull/3174. The fix will be available in the upcoming version of the MySQL check.
