### ISSUE TITLE
%%host%% interpolation not honored in conf.d

### ISSUE THREAD

**Issue by whuff739** [DataDog/datadog-agent#3167]
**Describe what happened:**
With configmap 
```yaml
data:
  conf: |-
    init_config:
    instances:
      - url: "http://%%env_NODE_IP%%:4001"
      - url: "http://%%env_NODE_IP%%:4002"
```
mounted as 
```yaml
            - mountPath: /conf.d/etcd.d/
              name: dd-agent-conf-masters
              readOnly: true
```
and
```yaml
        - name: dd-agent-conf-masters
          configMap:
            name: dd-agent-conf-masters
            items:
              - key: conf
                path: conf.yaml
```
with env var set thusly
```yaml
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```
we receive the following error:
```
    etcd (1.6.1)
    ------------
      Instance ID: etcd:60991aae3a74c004 [ERROR]
      Total Runs: 3
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 2, Total: 6
      Average Execution Time : 89ms
      Error: HTTPConnectionPool(host='%25%25env_node_ip%25%25', port=4001): Max retries exceeded with url: /v2/stats/self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcd35e19d50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 387, in run
          self.check(copy.deepcopy(self.instances[0]))
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 105, in check
          self.check_pre_v3(instance)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 214, in check_pre_v3
          self_response = self._get_self_metrics(url, ssl_params, timeout, critical_tags)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 287, in _get_self_metrics
          return self._get_json(url, "/v2/stats/self", ssl_params, timeout, tags)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 308, in _get_json
          r = self._perform_request(url, path, ssl_params, timeout)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 303, in _perform_request
          url + path, verify=verify, cert=certificate, timeout=timeout, headers=headers(self.agentConfig)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 75, in get
          return request('get', url, params=params, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 60, in request
          return session.request(method=method, url=url, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
          resp = self.send(prep, **send_kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
          r = adapter.send(request, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
          raise ConnectionError(e, request=request)
      ConnectionError: HTTPConnectionPool(host='%25%25env_node_ip%25%25', port=4001): Max retries exceeded with url: /v2/stats/self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcd35e19d50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
      Warning: In Agent 6.10 this check will only support ETCD v3&#43;. If you wish to preview the new version, set `use_preview` to `true`.

      Instance ID: etcd:7ec1f415e0b4fbbc [ERROR]
      Total Runs: 2
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 2, Total: 4
      Average Execution Time : 49ms
      Error: HTTPConnectionPool(host='%25%25env_node_ip%25%25', port=4002): Max retries exceeded with url: /v2/stats/self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcd35e19d90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 387, in run
          self.check(copy.deepcopy(self.instances[0]))
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 105, in check
          self.check_pre_v3(instance)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 214, in check_pre_v3
          self_response = self._get_self_metrics(url, ssl_params, timeout, critical_tags)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 287, in _get_self_metrics
          return self._get_json(url, "/v2/stats/self", ssl_params, timeout, tags)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 308, in _get_json
          r = self._perform_request(url, path, ssl_params, timeout)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/etcd/etcd.py", line 303, in _perform_request
          url + path, verify=verify, cert=certificate, timeout=timeout, headers=headers(self.agentConfig)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 75, in get
          return request('get', url, params=params, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 60, in request
          return session.request(method=method, url=url, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
          resp = self.send(prep, **send_kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
          r = adapter.send(request, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
          raise ConnectionError(e, request=request)
      ConnectionError: HTTPConnectionPool(host='%25%25env_node_ip%25%25', port=4002): Max retries exceeded with url: /v2/stats/self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcd35e19d90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
      Warning: In Agent 6.10 this check will only support ETCD v3&#43;. If you wish to preview the new version, set `use_preview` to `true`.
```
**Describe what you expected:**
We expected the %%env_XXXX%% to expand the environment variable to get the node's IP address per https://github.com/DataDog/datadog-agent/pull/1339 . We also tried %%host%%  and got the same results. When hardcoding the node's IP address as a test, things worked as expected, but is untenable to deploy in our setup.

**Steps to reproduce the issue:**
See above.

**Additional environment details (Operating System, Cloud provider, etc):**
Kops gererated Kube cluster 1.10.x running in AWS, Datadog agent 6.9.0

**Comment by CharlyF** [comment]
Hey there,

Thank you for reaching out!
I think the issue here is that the template you are passing in your configmap is processed as a regular integration template.
Could you add the ad_identifiers field as follows:
https://github.com/DataDog/integrations-core/blob/master/etcd/datadog_checks/etcd/data/auto_conf.yaml#L1 
?

With that, the agent should understand that it's supposed to process the template as an autodiscovery one and thus interpolate the template variables.

Let us know if that helps.
Best,
.C

**Comment by zabaat** [comment]
Same problem, but how are you supposed to do this for the postgres integration since it doesn't match any containers.

```
## All options defined here are available to all instances.
      #
      init_config:
  
          ## @param service - string - optional
          ## Attach the tag `service:<SERVICE>` to every metric, event, and service check emitted by this integration.
          ##
          ## Additionally, this sets the default `service` for every log source.
          #
          # service: <SERVICE>
  
      ## Every instance is scheduled independent of the others.
      #
      instances:
  
          ## @param host - string - required
          ## The hostname to connect to.
          ## NOTE: Even if the server name is `localhost`, the Agent connects to PostgreSQL using TCP/IP unless you also
          ## provide a value for the sock key.
          #
        - host: psql-masterytrack-production.cyspzu9k3jsf.us-west-2.rds.amazonaws.com
  
          ## @param port - integer - optional - default: 5432
          ## The port to use when connecting to PostgreSQL.
          #
          # port: 5432
  
          ## @param username - string - required
          ## The Datadog username created to connect to PostgreSQL.
          #
          username: datadog
  
          ## @param password - string - optional
          ## The password associated with the Datadog user.
          #
          password: "%%env_DATADOG_PGPASSWORD%%"
```

this doesn't work, if I hardcode that password line it works fine.
