### ISSUE TITLE
[BUG] agent crashing

### ISSUE THREAD

**Issue by kevinburkesegment** [DataDog/datadog-agent#32176]
**Agent Environment**

7.50.3-jmx, running on amd64 in Kubernetes.

**Describe what happened:**

Agents crash with the following stack trace (every goroutine gets dumped, but this is the most germane). I can't tell if this is an issue with the Go runtime or with the Datadog agent doing something it's not supposed to with unsafe.

I ran the Datadog agent tests with the race detector and gcflags=-d=checkptr turned on, and found one data race, but it didn't match this one.

log="goroutine 1 [chan receive, 905 minutes]:" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601865825Z
log= pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601857714Z
log="	/usr/local/go/src/runtime/mgc.go:178 +0x6b" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601855714Z
log="created by runtime.gcenable" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601853354Z
log="	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000ad7e8 sp=0xc0000ad7e0 pc=0x22f5d41" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601850844Z
log=runtime.goexit() pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601848654Z
log="	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000ad7e0 sp=0xc0000ad7c8 pc=0x229d946" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601846334Z
log=runtime.gcenable.func1() pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601843643Z
log="	/usr/local/go/src/runtime/mgcsweep.go:299 +0xff fp=0xc0000ad7c8 sp=0xc0000ad780 pc=0x22a889f" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601828623Z
log=runtime.bgsweep(0x0?) pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601826162Z
log="	/usr/local/go/src/runtime/mgcsweep.go:391 +0xf9 fp=0xc0000ad780 sp=0xc0000ad730 pc=0x22a8ad9" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601823882Z
log=runtime.sweepone() pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601821272Z
log="	/usr/local/go/src/runtime/mgcsweep.go:629 +0x34d fp=0xc0000ad730 sp=0xc0000ad640 pc=0x22a910d" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601818552Z
log="runtime.(*sweepLocked).sweep(0xc2a1460?, 0x0)" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601806681Z
log="	/usr/local/go/src/runtime/mgcsweep.go:846 +0x2e5 fp=0xc0000ad640 sp=0xc0000ad5c0 pc=0x22a9e45" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601804461Z
log=runtime.(*mspan).reportZombies(0x7f367858daa8) pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601802051Z
log="	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0000ad5c0 sp=0xc0000ad590 pc=0x22bd07d" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601799781Z
log="runtime.throw({0x7c84b92?, 0xc000000400?})" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601796871Z
log="goroutine 3 [running]:" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601793230Z
log= pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.601777690Z
log="fatal error: found pointer to free object" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.599670983Z
log="0xc000000000 free  marked   zombie" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.599371515Z
log="runtime: marked free object in span 0x7f367858daa8, elemsize=1024 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)" pod=datadog-agent-4b6c6 time=2024-12-14T02:18:24.599312012Z

**Describe what you expected:**

I expected the agent to continue running or shut down in an orderly fashion.

**Steps to reproduce the issue:**

I don't know how to reproduce it.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by sgnn7** [comment]
Hi @kevinburkesegment,
Thank you for filing this report!

Based on the description of the issue, it looks like a support ticket is a better fit to track and resolve it as it will require collection of deeper crash logs that may contain your internal data not intended to be publicly shared. In order to help you, we ask you to recreate it in [our helpdesk system (no login required)](https://help.datadoghq.com/hc/en-us/requests/new?tf_1260824651490=pt_product_type:agent) which will allow you provide additional information in private.

I will close this issue for now but please add the helpdesk ticket ID in comments once you have it opened
