### ISSUE TITLE
[mongodb] False NetworkTimeout exception on a Mongo node that is resyncing

### ISSUE THREAD

**Issue by skijash** [DataDog/datadog-agent#3293]
**Output of the info page (if this is a bug)**
```
==============
Agent (v6.9.0)
==============

  Status date: 2019-04-12 09:02:14.515396 UTC
  Pid: 17092
  Python Version: 2.7.15
  Logs:
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 2.088ms
    System UTC time: 2019-04-12 09:02:14.515396 UTC

  Host Info
  =========
    bootTime: 2019-04-12 06:50:30.000000 UTC
    kernelVersion: 4.4.0-1079-aws
    os: linux
    platform: ubuntu
    platformFamily: debian
    platformVersion: 16.04
    procs: 243
    uptime: 1h10m23s
    virtualizationRole: guest
    virtualizationSystem: xen

  Hostnames
  =========
    ec2-hostname: ip-10-0-200-207.us-west-1.compute.internal
    hostname: i-0e48cff41937ff4fe
    instance-id: i-0e48cff41937ff4fe
    socket-fqdn: ip-10-0-200-207.us-west-1.compute.internal.
    socket-hostname: ip-10-0-200-207
    hostname provider: aws
    unused hostname providers:
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

=========
Collector
=========

  Running Checks
  ==============

    cpu
    ---
      Instance ID: cpu [OK]
      Total Runs: 245
      Metric Samples: Last Run: 6, Total: 1,464
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    disk (2.0.1)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Total Runs: 245
      Metric Samples: Last Run: 118, Total: 28,910
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 20ms


    file_handle
    -----------
      Instance ID: file_handle [OK]
      Total Runs: 245
      Metric Samples: Last Run: 5, Total: 1,225
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    io
    --
      Instance ID: io [OK]
      Total Runs: 245
      Metric Samples: Last Run: 52, Total: 12,704
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 5ms


    load
    ----
      Instance ID: load [OK]
      Total Runs: 246
      Metric Samples: Last Run: 6, Total: 1,476
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    memory
    ------
      Instance ID: memory [OK]
      Total Runs: 245
      Metric Samples: Last Run: 17, Total: 4,165
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    mongo (1.7.0)
    -------------
      Instance ID: mongo:a2b3e6885ac503ed [ERROR]
      Total Runs: 82
      Metric Samples: Last Run: 0, Total: 27
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 82
      Average Execution Time : 30.033s
      Error: localhost:27017: timed out
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 387, in run
          self.check(copy.deepcopy(self.instances[0]))
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mongo/mongo.py", line 768, in check
          status = db.command('serverStatus', tcmalloc=collect_tcmalloc_metrics)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pymongo/database.py", line 516, in command
          codec_options, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pymongo/database.py", line 428, in _command
          parse_write_concern_error=parse_write_concern_error)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pymongo/pool.py", line 482, in command
          self._raise_connection_failure(error)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pymongo/pool.py", line 608, in _raise_connection_failure
          _raise_connection_failure(self.address, error)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pymongo/pool.py", line 259, in _raise_connection_failure
          raise NetworkTimeout(msg)
      NetworkTimeout: localhost:27017: timed out

    network (1.8.0)
    ---------------
      Instance ID: network:2a218184ebe03606 [OK]
      Total Runs: 246
      Metric Samples: Last Run: 20, Total: 4,920
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    ntp
    ---
      Instance ID: ntp:b4579e02d1981c12 [OK]
      Total Runs: 245
      Metric Samples: Last Run: 1, Total: 245
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 245
      Average Execution Time : 7ms


    uptime
    ------
      Instance ID: uptime [OK]
      Total Runs: 246
      Metric Samples: Last Run: 1, Total: 246
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s

========
JMXFetch
========

  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 245
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 20
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 510
    TimeseriesV1: 245

  API Keys status
  ===============
    API key ending with b0961: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - b0961

==========
Logs Agent
==========

  Logs Agent is not running

=========
Aggregator
=========
  Checks Metric Sample: 59,481
  Dogstatsd Metric Sample: 3,059
  Event: 1
  Events Flushed: 1
  Number Of Flushes: 245
  Series Flushed: 53,468
  Service Check: 2,377
  Service Checks Flushed: 2,616

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 3,059
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Packet Reading Errors: 0
  Udp Packets: 3,060
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0

```

**Describe what happened:**
On a Mongo node which is resyncing data (so it is in OTHER state, not SECONDARY), the agent is reporting `NetworkTimeout: localhost:27017: timed out` which isn't true. I am able to connect to Mongo shell on localhost:27017.

**Describe what you expected:**
On running `datadog-agent status`, I would expect it to not throw an exception, but to report that the node is up, just not responding to stats queries.

**Steps to reproduce the issue:**
Have the agent running on a mongo node, with mongo integration active, delete the data directory and restart mongo service so it starts resyncing data. On running `datadog-agent status`, you should get the `NetworkTimeout: localhost:27017: timed out` exception.

**Additional details:**
We have a monitor alerting us on high values of `mongodb.opcounters.updateps'. That monitor is alerting that it has `No data`. Looking at the agent code, I believe the reason is:
* the agent opens a connection, preferring the primary, but it got localhost, which is in startup state
* lists the databases
* runs the stats command on a db, but gets no response, since the db is not operational
* timeouts and reports a NetworkTimeout somewhere down the stack

**Comment by olivielpeau** [comment]
Thanks @skijash for the detailed report, since this affects an Agent check I'll go ahead and move this to the related repository: https://github.com/DataDog/integrations-core
