### ISSUE TITLE
Kafka Integration Breaks in datadog-agent v6.14

### ISSUE THREAD

**Issue by elizajanus** [DataDog/datadog-agent#4176]
**Output of the info page (if this is a bug)**
```
UTC | CORE | ERROR | (pkg/collector/python/datadog_agent.go:114 in LogMessage) | kafka_consumer:b2bce3bcb6083a9b | (legacy_0_10_2.py:95) | There was a problem collecting consumer offsets from Kafka.
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/kafka_consumer/legacy_0_10_2.py", line 93, in check
    self._get_kafka_consumer_offsets()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/kafka_consumer/legacy_0_10_2.py", line 382, in _get_kafka_consumer_offsets
    'Invalid configuration - if you are collecting consumer offsets from Kafka, and your brokers are '
ConfigurationError: Invalid configuration - if you are collecting consumer offsets from Kafka, and your brokers are older than 0.10.2, then you _must_ specify consumer groups and their topics. Older brokers lack the necessary protocol support to determine which topics a consumer is consuming. See KIP-88 for details.
```

**Describe what happened:**
I updated the datadog-agent version from v6.13 to v6.14 and my kafka_consumers.d configuration was no longer valid. I rolled back to v6.13 and everything worked fine again.

**Describe what you expected:**
I expected to update the agent to v6.14 and have the kafka consumers integration remain functional.

**Steps to reproduce the issue:**
Configure kafka_consumers.d/conf.yaml with explicitly listed consumer groups/topics to gather offset info from kafka (not zookeeper). Ensure the integration is successful in v6.13, then upgrade agent to v6.14 and note the error message.

**Additional environment details (Operating System, Cloud provider, etc):**
Red Hat Enterprise Linux Server release 7.7 (Maipo) running on AWS m4.large EC2 instances

**Comment by therve** [comment]
Hi, thanks for your report. Can you provide the configuration that you used? This shouldn't happen if the configuration is following the guidelines.

**Comment by elizajanus** [comment]
Yep, here it is. This works completely fine with v6.13.

```
## WARNING: To avoid blindly collecting offsets and lag for an unbounded number
## of partitions (as could be the case after introducing the self discovery
## of consumer groups, topics and partitions) the check collects metrics
## for at most 200 partitions.

init_config:

  ## @param zk_timeout - integer - optional - default: 5
  ## Customizes the ZooKeeper connection timeout.
  #
  # zk_timeout: 5

  ## @param kafka_timeout - integer - optional - default: 5
  ## Customizes the Kafka connection timeout.
  #
  # kafka_timeout: 5

  ## @param kafka_retries - integer - optional - default: 3
  ## Customizes the max number of retries per failed query to Kafka.
  #
  # kafka_retries: 3

  ## @param min_collection_interval - integer - optional - default: 600
  ## Customize the number of seconds that must elapse between running this check.
  ## When checking Kafka offsets stored in Zookeeper, a single run of this check
  ## must stat zookeeper more than the number of consumers * topic_partitions
  ## that you're monitoring. If that number is greater than 100, it's recommended
  ## to increase this value to avoid hitting zookeeper too hard.
  ## https://docs.datadoghq.com/developers/write_agent_check/#collection-interval
  #
  # min_collection_interval: 600

instances:

    ## @param kafka_connect_str - list of strings - required
    ## Kafka endpoints and port to connect to.
    ##
    ## In a production environment, it's often useful to specify multiple
    ## Kafka nodes for a single check instance. This way you
    ## only generate a single check process, but if one host goes down,
    ## KafkaClient / KazooClient tries contacting the next host.
    ## Details: https://github.com/DataDog/dd-agent/issues/2943
    #
  - kafka_connect_str:
    - {{ kafka_connect_str }}
    # - <KAFKA_BROKER_ENDPOINT>:9092

    ## @param zk_connect_str - list of objects - required
    ## Zookeeper endpoints and port to connect to.
    ## In a production environment, it's often useful to specify multiple
    ## Zookeeper nodes for a single check instance. This way you
    ## only generate a single check process, but if one host goes down,
    ## KafkaClient / KazooClient tries contacting the next host.
    ## Details: https://github.com/DataDog/dd-agent/issues/2943
    ##
    ## If you wish to only collect consumer offsets from kafka, because
    ## you're using the new style consumers, you can comment out all
    ## zk_* configuration elements below.
    ## Please note that unlisted consumer groups are not supported at
    ## the moment when zookeeper consumer offset collection is disabled.
    #
   # zk_connect_str:
   # - {{ zk_connect_str }}
    # - <ZOOKEEPER_ENDPOINT>:2181

    ## @param zk_iteration_ival - integer - optional
    ## Set how many seconds the check should wait between two ZK consumer offset
    ## collections. If kafka consumer offsets is disabled, this has no effect.
    #
    # zk_iteration_ival: 1

    ## @param zk_prefix - string - optional
    ## Zookeeper chroot prefix under which kafka data is living in zookeeper.
    ## If kafka is connecting to `my-zookeeper:2181/kafka` then the `zk_prefix` is `/kafka`.
    #
    # zk_prefix: <ZK_PREFIX>

    ## @param consumer_groups - object - optional
    ## When using Kafka to store consumer offsets each level is mandatory.
    ## When using zookeeper to store consumer offsets  each level is optional.
    ## Any empty values are fetched from Zookeeper. You can have empty partitions (example: <CONSUMER_NAME_2>),
    ## topics (example: <CONSUMER_NAME_3>), and even consumer_groups. If you omit
    ## consumer_groups, you must set 'monitor_unlisted_consumer_groups': true.
    
    consumer_groups:
      opportunity-update-builder:
        OpportunityUpdateEvents: [0]
      leads-to-homes:
        HomesRoutedLeads: [0]
      leads-to-s3:
        Leads: [0]
      agent-match-list: {}
      homes-leads-to-s3-consumer:
        HomesRoutedLeads: [0]
      MobileNotificationConsumer:
        MobileNotifications: [0]
      user-change-consumer:
        Users: [0]
      agent-recommendation-lists-json:
        AgentRecommendationListsJson: [0]
      leads-api:
        Leads: [0]
        leads-api-leads-store-repartition: [0]
      interviews-api: {}
      user-update-builder:
        UserUpdateEvents: [0]
      leads-to-opportunities: {}
      EmailNotificationConsumer:
        EmailNotifications: [0]
      opportunities-to-recommendations:
        Opportunities: [0]
      spring.application.name:
        AgentUpdateEvents: [0]
      agent-change-consumer:
        Agents: [0]
      opportunity-change-consumer:
        Opportunities: [0]                                       

    ## @param monitor_unlisted_consumer_groups - boolean - required
    ## Setting monitor_unlisted_consumer_groups to `true` tells the check to
    ## discover and fetch all offsets for all consumer groups stored in zookeeper.
    ## While this is convenient, it can also put a lot of load on zookeeper.
    #
    monitor_unlisted_consumer_groups: false

    ## @param kafka_consumer_offsets - boolean - optional - default: false
    ## Set to true if consumer offsets data are stored within Kafka.
    ## Set to false if consumer offsets data are stored within Zookeeper.
    #
    kafka_consumer_offsets: true

    ## @param tags - list of key:value string - optional
    ## List of tags to attach to every metric and service check emitted by this integration.
    ##
    ## Learn more about tagging at https://docs.datadoghq.com/tagging
    #
    # tags:
    #   - <KEY_1>:<VALUE_1>
    #   - <KEY_2>:<VALUE_2>

    ## @param security_protocol - string - required
    ## Protocol used to communicate with brokers.
    ## Valid values are: PLAINTEXT, SSL. Default: PLAINTEXT.
    #
    security_protocol: PLAINTEXT

    ## @param sasl_mechanism - string - optional
    ## String picking sasl mechanism when security_protocol is SASL_PLAINTEXT or SASL_SSL.
    ## Currently only PLAIN is supported.
    #
    # sasl_mechanism: PLAIN

    ## @param sasl_plain_username - string - optional
    ## Username for sasl PLAIN authentication.
    #
    # sasl_plain_username: <USERNAME>

    ## @param sasl_plain_password - string - optional
    ## Password for sasl PLAIN authentication.
    #
    # sasl_plain_password: <PASSWORD>

    ## @param sasl_kerberos_service_name - string - optional - default: kafka
    ## Service name to include in GSSAPI sasl mechanism handshake.
    #
    # sasl_kerberos_service_name: kafka

    ## @param sasl_kerberos_domain_name - string - optional - default: one of the bootstrap servers
    ## Kerberos domain name to use in GSSAPI sasl mechanism handshake.
    #
    # sasl_kerberos_domain_name: localhost

    ## @param ssl_context - string - optional
    ## Pre-configured SSLContext for wrapping socket connections.
    ## If provided, all other ssl_* configurations are ignored.
    #
    # ssl_context: <SSL_CONTEXT>

    ## @param ssl_check_hostname - string - optional - default: true
    ## Flag to configure whether SSL handshake should verify that the
    ## certificate matches the broker’s hostname.
    #
    # ssl_check_hostname: true

    ## @param ssl_cafile - string - optional
    ## Filename of CA file path to use in certificate verification.
    #
    # ssl_cafile: <CA_FILE_PATH>

    ## @param ssl_certfile - string - optional
    ## Filename path of file in PEM format containing the client certificate,
    ## as well as any CA certificates needed to establish the certificate’s authenticity.
    #
    # ssl_certfile: <CERT_FILE_PATH>

    ## @param ssl_keyfile - string - optional
    ## Optional filename containing the client private key.
    #
    # ssl_keyfile: <KEY_FILE_PATH>

    ## @param ssl_password - string - optional
    ## Password to be used when loading the certificate chain.
    #
    # ssl_password: <PASSWORD>

    ## @param ssl_crlfile - string - optional
    ## Filename path containing the CRL to check for certificate expiration.
    ## By default, no CRL check is done. When providing a file, only the leaf certificate
    ## will be checked against this CRL. The CRL can only be checked with Python 3.4+ or 2.7.9+.
    #
    # ssl_crlfile: <SSL_FILE_PATH>
```

**Comment by therve** [comment]
OK I believe I see the issue. `6.13` is not failing indeed, but it's **not** reporting metrics for the groups where you don't have topics (`agent-match-list`, `interviews-api`, `leads-to-opportunities`). `6.14` is failing explicitly, which sounds like a better outcome to me. What do you think?

**Comment by elizajanus** [comment]
This makes sense now! I removed the consumer groups with no topics. Thanks!
