### ISSUE TITLE
Agent Vault status check is not passing for standby instances

### ISSUE THREAD

**Issue by soeirosantos** [DataDog/datadog-agent#4325]
**Describe what happened:**

After enabling the Vault integration in my cluster as [described here](https://docs.datadoghq.com/integrations/vault/) I cannot get the Vault check passing in the standby instances. Here are the details:

This is what I get for `$ sudo datadog-agent status`
```
vault (1.5.0)
    -------------
      Instance ID: vault:10262e521e965031 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/vault.d/vault-conf.yaml
      Total Runs: 264
      Metric Samples: Last Run: 1, Total: 260
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 264
      Average Execution Time : 84ms
      Error:
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 556, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/vault/vault.py", line 53, in check
          api['check_health'](config, tags)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/vault/vault.py", line 88, in check_health_v1
          health_data = self.access_api(url, config, tags)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/vault/vault.py", line 152, in access_api
          raise ApiUnreachable
      ApiUnreachable
```

The log shows this error `HTTPError: 429 Client Error: Too Many Requests for url: http://localhost:8200/v1/sys/health`

When I try this endpoint directly I get the following result:

```
$ curl http://localhost:8200/v1/sys/health
{"initialized":true,"sealed":false,"standby":true,"performance_standby":false,"replication_performance_mode":"unknown","replication_dr_mode":"unknown","server_time_utc":1571327129,"version":"1.2.2","cluster_name":"vault-cluster-xxx","cluster_id":"3fe63e38-f0f5-11e9-a713-2a2ae2xxxxxx"}
```

**Describe what you expected:**

I'd expect to see the datadog-agent status check passing in the standby instances.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**DD Agent**: Agent 6.14.1 - Commit: fa227f0 - Serialization version: 4.12.0 - Go version: go1.12.9
**Vault version**: Vault v1.2.2
**OS**: CentOS Linux 7

Thanks!

**Comment by olivielpeau** [comment]
Hi @soeirosantos, thanks for reporting this.

Since this is related to an Agent integration, I'm going to transfer the issue to the `integrations-core` repo.
