### ISSUE TITLE
docker autodiscovery getting containers in different networks

### ISSUE THREAD

**Issue by yovasx2** [DataDog/datadog-agent#4523]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

===============
Agent (v6.15.1)
===============

  Status date: 2019-11-28 20:44:27.382003 UTC
  Agent start: 2019-11-28 20:40:01.379729 UTC
  Pid: 337
  Go Version: go1.12.9
  Python Version: 2.7.17
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -5.722ms
    System UTC time: 2019-11-28 20:44:27.382003 UTC

  Host Info
  =========
    bootTime: 2019-11-27 03:41:46.000000 UTC
    kernelVersion: 4.9.184-linuxkit
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 10.2
    procs: 68
    uptime: 40h58m17s
    virtualizationRole: guest
    virtualizationSystem: docker

  Hostnames
  =========
    hostname: docker-desktop
    socket-fqdn: b2b60ea45b1e
    socket-hostname: b2b60ea45b1e
    host tags:
      env:dev
      docker_swarm_node_role:manager
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance, and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: Get http://169.254.169.254/computeMetadata/v1/instance/hostname: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

=========
Collector
=========

  Running Checks
  ==============
    
    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 17
      Metric Samples: Last Run: 6, Total: 96
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    disk (2.5.1)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/disk.d/conf.yaml.default
      Total Runs: 18
      Metric Samples: Last Run: 218, Total: 3,924
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 34ms
      
    
    docker
    ------
      Instance ID: docker [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/docker.d/conf.yaml.default
      Total Runs: 17
      Metric Samples: Last Run: 625, Total: 10,625
      Events: Last Run: 0, Total: 3
      Service Checks: Last Run: 1, Total: 17
      Average Execution Time : 195ms
      
    
    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 18
      Metric Samples: Last Run: 5, Total: 90
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 17
      Metric Samples: Last Run: 65, Total: 1,060
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      
    
    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 18
      Metric Samples: Last Run: 6, Total: 108
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 17
      Metric Samples: Last Run: 17, Total: 289
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    network (1.11.5)
    ----------------
      Instance ID: network:e0204ad63d43c949 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 18
      Metric Samples: Last Run: 175, Total: 3,150
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 7ms
      
    
    ntp
    ---
      Instance ID: ntp:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 1
      Metric Samples: Last Run: 1, Total: 1
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1
      Average Execution Time : 966ms
      
    
    redisdb (1.13.0)
    ----------------
      Instance ID: redisdb:a378826d514449e8 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/redisdb.d/auto_conf.yaml
      Total Runs: 18
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 18
      Average Execution Time : 1.211s
      Error: Error 111 connecting to 172.20.5.98:6379. Connection refused.
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 652, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/redisdb/redisdb.py", line 468, in check
          self._check_db(instance, custom_tags)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/redisdb/redisdb.py", line 176, in _check_db
          info = conn.info()
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/client.py", line 665, in info
          return self.execute_command('INFO')
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
          connection.send_command(*args)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
          self.send_packed_command(self.pack_command(*args))
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
          self.connect()
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
          raise ConnectionError(self._error_message(e))
      ConnectionError: Error 111 connecting to 172.20.5.98:6379. Connection refused.
      Instance ID: redisdb:ecee8d6bbe555cb3 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/redisdb.d/auto_conf.yaml
      Total Runs: 18
      Metric Samples: Last Run: 33, Total: 594
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 18
      Average Execution Time : 3ms
      
    
    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 17
      Metric Samples: Last Run: 1, Total: 17
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
========
JMXFetch
========

  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 17
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 4
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 38
    TimeseriesV1: 17

  API Keys status
  ===============
    API key ending with 77cc9: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 77cc9

==========
Logs Agent
==========

  Logs Agent is not running

=========
Aggregator
=========
  Checks Metric Sample: 20,341
  Dogstatsd Metric Sample: 70
  Event: 4
  Events Flushed: 4
  Number Of Flushes: 17
  Series Flushed: 16,333
  Service Check: 248
  Service Checks Flushed: 254

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 69
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 3,653
  Udp Packet Reading Errors: 0
  Udp Packets: 70
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0
```

**Describe what happened:**
I have two containerized redis one in the same containerized datadog's network (metrics) and the other in another network (proxy), datadog is trying to connect to both, the proxy one is obviously producing connection refused

**Describe what you expected:**
not to be autodiscovery since the container is in another network

**Steps to reproduce the issue:**
Create two networks, attach one redis to one and the other to the other, init datadog in one network, it tries to hit both

**Additional environment details (Operating System, Cloud provider, etc):**
I'm using docker.

**Datadog logs**

```
ops_datadog.0.yrjme6po5mez@docker-desktop    | 2019-11-28 20:40:02 UTC | CORE | WARN | (pkg/autodiscovery/autoconfig.go:529 in resolveTemplateForService) | error resolving template redisdb for service docker://b2b60ea45b1efac769bf9abffe431c89511c579ed76b1ffc7899d8570617c244: failed to resolve IP address for container docker://b2b60ea45b1efac769bf9abffe431c89511c579ed76b1ffc7899d8570617c244, ignoring it. Source error: not able to determine which network is reachable
```

**Comment by yovasx2** [comment]
possibly related with #4019

**Comment by f3l1x** [comment]
I hit the same error. 

- OS: Debian
- Agent: install on host (no docker agent)
- Config: /etc/datadog-agent/datadog.yaml

```
listeners:
  - name: auto
  - name: docker

config_providers:
  - name: docker
    polling: true
```

----

**docker-compose.yaml**

```
version: '2'

services:

  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - default
      - redis
    labels:
      com.datadoghq.ad.check_names: '["redisdb"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host": "%%host%%","port":"6379","password":"pwd"}]'
    command: ["redis-server", "--requirepass", "pwd", "--databases", "32"]

networks:
  redis:
    external:
      name: redis
```

-----

`sudo datadog-agent check redisdb`

```
* error resolving template redisdb for service docker://[id]: failed to resolve IP address for container docker://[id], ignoring it. Source error: not able to determine which network is reachable
* Can't resolve the template for redisdb at this moment.
Error: no valid check found
```

-----

If I switch %%host%% to localhost (yes I know it's wrong).

> com.datadoghq.ad.instances: '[{"host": "localhost","port":"6379","password":"pwd"}]'

`sudo datadog-agent check redisdb`

```
=== Service Checks ===
[
  {
    "check": "redis.can_connect",
    "host_name": "docker",
    "timestamp": 1602512355,
    "status": 2,
    "message": "",
    "tags": [
      "docker_image:redis:5-alpine",
      "image_name:redis",
      "image_tag:5-alpine",
      "redis_host:localhost",
      "redis_port:6379",
      "short_image:redis"
    ]
  }
]
=========
Collector
=========

  Running Checks
  ==============

    redisdb (3.1.1)
    ---------------
      Instance ID: redisdb:[id] [ERROR]
      Configuration Source: docker:docker://[id]
      Total Runs: 1
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1
      Average Execution Time : 4ms
      Last Execution Date : 2020-10-12 16:19:15.000000 CEST
      Last Successful Execution Date : Never
      Error: Error 111 connecting to localhost:6379. Connection refused.
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 550, in connect
          sock = self._connect()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 606, in _connect
          raise err
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 594, in _connect
          sock.connect(socket_address)
      ConnectionRefusedError: [Errno 111] Connection refused

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 828, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py", line 500, in check
          self._check_db()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py", line 194, in _check_db
          info = conn.info()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py", line 1304, in info
          return self.execute_command('INFO')
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
          conn = self.connection or pool.get_connection(command_name, **options)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 1183, in get_connection
          connection.connect()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 554, in connect
          raise ConnectionError(self._error_message(e))
      redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

Check has run only once, if some metrics are missing you can try again with --check-rate to see any other metric if available.
```

----

If I fill valid IP address.

> com.datadoghq.ad.instances: '[{"host": "172.22.0.3","port":"6379","password":"lotus"}]'

It works.

**Comment by patricksamson** [comment]
I managed to solve a somewhat similar issue here : https://github.com/DataDog/datadog-agent/issues/4019#issuecomment-2772688942
Maybe it'll help someone.
