### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jose-ledesma** [DataDog/datadog-agent#6616]
After upgrading to datadog agent 6.23 in Kubernetes we are facing this panic time to time:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x141f9da]
goroutine 407 [running]:
github.com/DataDog/datadog-agent/pkg/util/kubernetes/kubelet.(*KubeUtil).searchPodForContainerID(0xc000694ea0, 0xc0019d0a00, 0x9c, 0x9c, 0xc000f00460, 0x4f, 0x0, 0x0, 0xc000bd8f48)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/kubernetes/kubelet/kubelet.go:271 +0xfa
github.com/DataDog/datadog-agent/pkg/util/kubernetes/kubelet.(*KubeUtil).GetPodForContainerID(0xc000694ea0, 0xc000f00460, 0x4f, 0x0, 0x0, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/kubernetes/kubelet/kubelet.go:214 +0xce
github.com/DataDog/datadog-agent/pkg/util/kubernetes/kubelet.(*KubeUtil).GetPodForEntityID(0xc000694ea0, 0xc000f00460, 0x4f, 0xc000193180, 0x1, 0x35ea900)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/kubernetes/kubelet/kubelet.go:334 +0x119
github.com/DataDog/datadog-agent/pkg/util/kubernetes/kubelet.(*PodWatcher).GetPodForEntityID(...)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/kubernetes/kubelet/podwatcher.go:190
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*KubeletCollector).Fetch(0xc00053b0e0, 0xc000f00460, 0x4f, 0x2, 0x2, 0xc001d58600, 0x2, 0x4, 0x0, 0x0, ...)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/kubelet_main.go:123 +0x66
github.com/DataDog/datadog-agent/pkg/tagger.(*Tagger).Tag(0xc00018e8c0, 0xc000f00460, 0x4f, 0x2, 0x40, 0xc000f00460, 0x4f, 0x6, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/tagger.go:255 +0x31b
github.com/DataDog/datadog-agent/pkg/tagger.Tag(...)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/global.go:55
github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers.(*dockerEventBundle).toDatadogEvent(0xc00152c000, 0xc000186000, 0x4d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/docker_eventbundle.go:83 +0x790
github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers.(*DockerCheck).reportEvents(0xc000930000, 0xc0011e1400, 0x66, 0x80, 0x3e59060, 0xc00072e380, 0x0, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/docker_events.go:81 +0x120
github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers.(*DockerCheck).Run(0xc000930000, 0x5e696b7bff0, 0x567ce00)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/docker.go:311 +0x3634
github.com/DataDog/datadog-agent/pkg/collector/runner.(*Runner).work(0xc000591830)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/runner/runner.go:270 +0x4bc
created by github.com/DataDog/datadog-agent/pkg/collector/runner.(*Runner).AddWorker
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/runner/runner.go:100 +0x8a
AGENT EXITED WITH CODE 2, SIGNAL 0, KILLING CONTAINER
2020-10-22 11:52:45 UTC | PROCESS | CRITICAL | (pkg/process/util/signal_nowindows.go:21 in HandleSignals) | Caught signal 'terminated'; terminating.
```

**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

===============
Agent (v6.23.0)
===============

  Status date: 2020-10-22 12:51:45.185747 UTC
  Agent start: 2020-10-22 11:53:31.384222 UTC
  Pid: 391
  Go Version: go1.14.7
  Python Version: 2.7.18
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 2.228ms
    System UTC time: 2020-10-22 12:51:45.185747 UTC

  Host Info
  =========
    bootTime: 2020-10-22 10:03:22.000000 UTC
    kernelArch: x86_64
    kernelVersion: 4.19.112+
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: bullseye/sid
    procs: 510
    uptime: 1h50m23s
    virtualizationRole: guest

  Metadata
  ========
    cloud_provider: GCP
    hostname_source: gce

=========
Collector
=========

  Running Checks
  ==============

    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 7, Total: 1,618
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-10-22 12:51:38.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:38.000000 UTC


    disk (3.0.0)
    ------------
      Instance ID: disk:XXXXXXX [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/disk.d/conf.yaml.default
      Total Runs: 231
      Metric Samples: Last Run: 240, Total: 55,440
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 128ms
      Last Execution Date : 2020-10-22 12:51:30.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:30.000000 UTC


    docker
    ------
      Instance ID: docker [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/docker.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 504, Total: 120,960
      Events: Last Run: 0, Total: 49
      Service Checks: Last Run: 1, Total: 232
      Average Execution Time : 206ms
      Last Execution Date : 2020-10-22 12:51:37.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:37.000000 UTC


    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 5, Total: 1,160
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 2ms
      Last Execution Date : 2020-10-22 12:51:44.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:44.000000 UTC


    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 195, Total: 45,105
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-10-22 12:51:36.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:36.000000 UTC


    kubelet (5.0.0)
    ---------------
      Instance ID: kubelet:xxxxxxxxxxxxxxx [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 616, Total: 147,062
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 4, Total: 928
      Average Execution Time : 1.119s
      Last Execution Date : 2020-10-22 12:51:44.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:44.000000 UTC


    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml
      Total Runs: 232
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-10-22 12:51:31.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:31.000000 UTC


    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 6, Total: 1,392
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-10-22 12:51:35.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:35.000000 UTC


    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 18, Total: 4,176
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-10-22 12:51:42.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:42.000000 UTC


    network (1.18.1)
    ----------------
      Instance ID: network:xxxxxxxxxx [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 79, Total: 18,820
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 22ms
      Last Execution Date : 2020-10-22 12:51:34.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:34.000000 UTC


    ntp
    ---
      Instance ID: ntp:xxxxxxxxxxxxx [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 4
      Metric Samples: Last Run: 1, Total: 4
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 4
      Average Execution Time : 0s
      Last Execution Date : 2020-10-22 12:38:46.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:38:46.000000 UTC


    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 232
      Metric Samples: Last Run: 1, Total: 232
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-10-22 12:51:41.000000 UTC
      Last Successful Execution Date : 2020-10-22 12:51:41.000000 UTC

========
JMXFetch
========

  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 232
    Connections: 0
    Containers: 0
    Deployments: 0
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 70
    Metadata: 0
    Nodes: 0
    Pods: 0
    Processes: 0
    RTContainers: 0
    RTProcesses: 0
    ReplicaSets: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    Services: 0
    SketchSeries: 0
    Success: 534
    TimeseriesV1: 232

  API Keys status
  ===============
    API key ending with xxxxx: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - xxxxx

==========
Logs Agent
==========


  Logs Agent is not running

=========
APM Agent
=========
  Status: Running
  Pid: 396
  Uptime: 3494 seconds
  Mem alloc: 49,769,296 bytes
  Hostname: redacted
  Receiver: 0.0.0.0:8126
  Endpoints:
    https://trace.agent.datadoghq.com

  Receiver (previous minute)
  ==========================
    From go 1.13.15 (gc-amd64-linux), client v1.26.0
      Traces received: 1 (4,184 bytes)
      Spans received: 16

    Default priority sampling rate: 100.0%
    Priority sampling rate for 'service:xxxxxxxx,env:': 100.0%
    Priority sampling rate for 'service:xxxxxxxx,env:none': 100.0%

  Writer (previous minute)
  ========================
    Traces: 0 payloads, 0 traces, 0 events, 0 bytes
    Stats: 0 payloads, 0 stats buckets, 0 bytes

=========
Aggregator
=========
  Checks Metric Sample: 401,079
  Dogstatsd Metric Sample: 90,865
  Event: 50
  Events Flushed: 50
  Number Of Flushes: 232
  Series Flushed: 371,634
  Service Check: 3,719
  Service Checks Flushed: 3,938

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 90,864
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 5,064,113
  Udp Packet Reading Errors: 0
  Udp Packets: 10,324
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0```

**Describe what happened:**


**Describe what you expected:**


**Steps to reproduce the issue:**


**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by ahmed-mez** [comment]
Hi @jose-ledesma 

Thanks for reporting this, we'll definitely look into it!

Out of curiosity, what was the Agent version you were using before `7.23.0` ? Also, do you happen to know if these panics are correlated with other events? (e.g kubelet restarts, other container restarts...)

Thanks!

**Comment by jose-ledesma** [comment]
Hi! 
We were running `6.3` before `6.23` (watch out you wrote `7.23`). I don't know if it correlated with any other event (this kubernetes cluster runs a lot of short-lived pods with cluster autoscaler enabled so it may be really difficult to check)

**Comment by ahmed-mez** [comment]
Thanks for your reply, I meant `6.23.0` yes, sorry 🤦  

Okay, that could be useful for the investigation, one last question, how often do these panics happen?

Thanks!

**Comment by jose-ledesma** [comment]
> Thanks for your reply, I meant `6.23.0` yes, sorry 🤦
> 
> Okay, that could be useful for the investigation, one last question, how often do these panics happen?
> 
> Thanks!

I upgraded this datadog-agent 3 days ago, and it happened 3 times since then (so it's not usual taking in account also this cluster has 150+ nodes). The other clusters with more normal workloads have been updated today, so we may need to wait some days before confirming it happens there too.

**Comment by vboulineau** [comment]
Which Kubernetes version are you running?

**Comment by jose-ledesma** [comment]
Masters are 1.16, Nodes 1.15

**Comment by vboulineau** [comment]
Hey @jose-ledesma,

Normally a piece of code that is explicitly checking and removing `nil` PODs in case we get some from the Kubelet, so this panic should never happen.

Do you have the full panic stack with all goroutines? Also, do you have any clue on "when" this happens, i.e. any specific event or action that would occur just before or at the same time, or is it completely random?

Also, feel free to open a support ticket if it's easier for you.

**Comment by jose-ledesma** [comment]
> Do you have the full panic stack with all goroutines? Also, do you have any clue on "when" this happens, i.e. any specific event or action that would occur just before or at the same time, or is it completely random?

I only got the log I pasted, it seems that it is not printing the full panic stack :/  
I have been unable to find any other event that happens at the same time.

**Comment by mattKaczorowski** [comment]
I too am experience this issue on GKE:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x36aaadf]

goroutine 352 [running]:
github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/generic.(*Processor).processContainer(0xc0009fed20, {0x4eb7320, 0xc001aded70}, {0xc001a37c00, 0x40, 0x20}, 0xc0009fed20, 0x0)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/generic/processor.go:145 +0x15f
github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/generic.(*Processor).Run(0xc000e97710, {0x4eb7320, 0xc001aded70}, 0xc000473360)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/generic/processor.go:111 +0x62c
github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/generic.(*ContainerCheck).Run(0xc000e976b0)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/containers/generic/check.go:75 +0x56
github.com/DataDog/datadog-agent/pkg/collector/worker.(*Worker).Run(0xc0000a26e0)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/worker/worker.go:147 +0x4cb
github.com/DataDog/datadog-agent/pkg/collector/runner.(*Runner).newWorker.func1()
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/runner/runner.go:131 +0x6d
created by github.com/DataDog/datadog-agent/pkg/collector/runner.(*Runner).newWorker
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/runner/runner.go:128 +0x1bd
	```

**Comment by jacjtito** [comment]
Hi @jose-ledesma 👋 — thanks again for taking the time to report this issue.

We're closing this due to inactivity: it's been over 6 months since the last update, and the stale bot's check-in didn't receive a response. This isn't a reflection of the value of the contribution — it's purely a hygiene pass to keep the backlog actionable.

If this is still relevant to you:
- Feel free to **reopen this issue** or open a new one with updated reproduction steps
- If the underlying issue is still present, a fresh report against the current version will get faster attention

Thanks for your patience and for contributing to the Datadog Agent! 🙏
