### ISSUE TITLE
If the process mentioned in process.d is missing, unnecessary Traceback logged in logs.

### ISSUE THREAD

**Issue by akagalkararkin** [DataDog/datadog-agent#6660]
**Describe what happened:**
In /etc/datadog-agent/conf.d/process.d/conf.yaml, I have entry for service which is not running on the machine. It's expected that the service won't be running some times.  Here is the entry detail - (Name of the service has replaced to "non-running-service"
  - name: non-running-service
  search_string:
  - com.vnera.nonrunningservice.service.NonRunninService
  exact_match: 'false'`

**Describe what you expected:**
In such cases, in the logs file, only the statement should be logged mentioning the service is missing. 
However, agent logs stacktrace, which doesn't make any sense for log reader. (Its issue with logging statement in runner.go)
This also unnecessarily filling log file.
Following is the excerpt from 
`sudo -u dd-agent -- datadog-agent check process`

`=========
Collector
=========

  Running Checks
  ==============
    
    process (1.15.1)
    ----------------
      Instance ID: process:hdfs-datanode:4352219f184c0da0 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/process.d/conf.yaml
      Total Runs: 1
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 91ms
      Last Execution Date : 2020-10-30 05:45:14.000000 UTC
      Last Successful Execution Date : Never
      Error: psutil.NoSuchProcess process no longer exists (pid=45880, name='sleep')
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_common.py", line 449, in wrapper
          ret = self._cache[fun]
      AttributeError: _cache
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1516, in wrapper
          return fun(self, *args, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_common.py", line 452, in wrapper
          return fun(self)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1558, in _parse_stat_file
          with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
          return open(fname, "rb", **kwargs)
      FileNotFoundError: [Errno 2] No such file or directory: '/proc/45880/stat'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 841, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/process/process.py", line 417, in check
          pids = self.find_pids(name, search_string, exact_match, ignore_ad=ignore_ad)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/process/process.py", line 192, in find_pids
          ', '.join(sorted(proc.name() for proc in self.process_list_cache.elements)),
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/process/process.py", line 192, in <genexpr>
          ', '.join(sorted(proc.name() for proc in self.process_list_cache.elements)),
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/__init__.py", line 630, in name
          name = self._proc.name()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1516, in wrapper
          return fun(self, *args, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1611, in name
          name = self._parse_stat_file()['name']
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1523, in wrapper
          raise NoSuchProcess(self.pid, self._name)
      psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=45880, name='sleep')

=========
Collector
=========

  Running Checks
  ==============
    
    process (1.15.1)
    ----------------
      Instance ID: process:hdfs-namenode:119c8bacc9084e63 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/process.d/conf.yaml
      Total Runs: 1
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 77ms
      Last Execution Date : 2020-10-30 05:45:14.000000 UTC
      Last Successful Execution Date : Never
      Error: psutil.NoSuchProcess process no longer exists (pid=45880, name='sleep')
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_common.py", line 449, in wrapper
          ret = self._cache[fun]
      AttributeError: _cache
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1516, in wrapper
          return fun(self, *args, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_common.py", line 452, in wrapper
          return fun(self)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1558, in _parse_stat_file
          with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
          return open(fname, "rb", **kwargs)
      FileNotFoundError: [Errno 2] No such file or directory: '/proc/45880/stat'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 841, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/process/process.py", line 417, in check
          pids = self.find_pids(name, search_string, exact_match, ignore_ad=ignore_ad)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/process/process.py", line 192, in find_pids
          ', '.join(sorted(proc.name() for proc in self.process_list_cache.elements)),
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/process/process.py", line 192, in <genexpr>
          ', '.join(sorted(proc.name() for proc in self.process_list_cache.elements)),
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/__init__.py", line 630, in name
          name = self._proc.name()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1516, in wrapper
          return fun(self, *args, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1611, in name
          name = self._parse_stat_file()['name']
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/psutil/_pslinux.py", line 1523, in wrapper
          raise NoSuchProcess(self.pid, self._name)
      psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=45880, name='sleep')

`
**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by jacjtito** [comment]
Automatically closed due to inactivity.
