### ISSUE TITLE
The agent panics when UDP port is busy and dogstatsd_so_rcvbuf are configured

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#6803]
There is a bug [here](https://github.com/DataDog/datadog-agent/blob/fbe415d9ec9875e173525b7234911e502ab33bf0/pkg/dogstatsd/listeners/udp.go#L65-L75): the connection returned from `net.ListenUDP("udp", addr)` is used before the error check is performed. Here is what that results in:
```
2020-11-19 02:33:54 UTC | CORE | INFO | (cmd/agent/app/run.go:360 in StopAgent) | See ya!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c8925c]

goroutine 1 [running]:
github.com/DataDog/datadog-agent/pkg/dogstatsd/listeners.NewUDPListener(0xc00098f380, 0xc0007d3e60, 0xe, 0x1fbd, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/dogstatsd/listeners/udp.go:68 +0x5fc
github.com/DataDog/datadog-agent/pkg/dogstatsd.NewServer(0xc0008485a0, 0x3a1af38, 0xd, 0x1)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/dogstatsd/server.go:158 +0x1100
github.com/DataDog/datadog-agent/cmd/agent/app.StartAgent(0xc000000008, 0x3b17538)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/app/run.go:275 +0x126e
github.com/DataDog/datadog-agent/cmd/agent/app.run(0x5627f00, 0x580e2f0, 0x0, 0x0, 0x0, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/app/run.go:122 +0x1de
github.com/spf13/cobra.(*Command).execute(0x5627f00, 0x580e2f0, 0x0, 0x0, 0x5627f00, 0x580e2f0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/vendor/github.com/spf13/cobra/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x56232e0, 0x0, 0x4f180, 0xc0000e2058)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/main.go:18 +0x2d
```

**Comment by penberg** [comment]
Looks like this was broken by commit 0afb48b173d4d5f51249d4381bd7a94afacb64b8, which added socket read buffer updating before the error check.

The following should fix the panic:

```patch
diff --git a/pkg/dogstatsd/listeners/udp.go b/pkg/dogstatsd/listeners/udp.go
index 4dfa090ba..38be85b04 100644
--- a/pkg/dogstatsd/listeners/udp.go
+++ b/pkg/dogstatsd/listeners/udp.go
@@ -64,16 +64,16 @@ func NewUDPListener(packetOut chan Packets, sharedPacketPool *PacketPool) (*UDPL
        }
        conn, err := net.ListenUDP("udp", addr)

+       if err != nil {
+               return nil, fmt.Errorf("can't listen: %s", err)
+       }
+
        if rcvbuf := config.Datadog.GetInt("dogstatsd_so_rcvbuf"); rcvbuf != 0 {
                if err := conn.SetReadBuffer(rcvbuf); err != nil {
                        return nil, fmt.Errorf("could not set socket rcvbuf: %s", err)
                }
        }

-       if err != nil {
-               return nil, fmt.Errorf("can't listen: %s", err)
-       }
-
        bufferSize := config.Datadog.GetInt("dogstatsd_buffer_size")
        packetsBufferSize := config.Datadog.GetInt("dogstatsd_packet_buffer_size")
        flushTimeout := config.Datadog.GetDuration("dogstatsd_packet_buffer_flush_timeout")
```

**Comment by olivielpeau** [comment]
Thanks for reporting this issue @deadok22, and for proposing a fix @penberg.

@penberg could you open a PR with your fix? (so that authorship can be preserved)

**Comment by irabinovitch** [comment]
@penberg Were you still interested in opening a PR for this?

**Comment by penberg** [comment]
@olivielpeau @irabinovitch Sorry, I missed this notification and completely forgot about the whole thing. I will send a pull request later today.
