### ISSUE TITLE
Unable to use custom_check if it requires Quartz

### ISSUE THREAD

**Issue by lmesz-bitrise** [DataDog/datadog-agent#6896]
**Agent status**
```
===============
Agent (v6.22.0)
===============

  Status date: 2020-12-02 19:21:24.813952 GMT
  Agent start: 2020-12-02 19:21:20.023927 GMT
  Pid: 39330
  Go Version: go1.13.11
  Python Version: 3.8.5
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 6
  Log Level: info
```

**Output of the info page (if this is a bug)**
```
{
	"StandardOutPath" = "/var/log/datadog/launchd.log";
	"LimitLoadToSessionType" = "Aqua";
	"StandardErrorPath" = "/var/log/datadog/launchd.log";
	"Label" = "com.datadoghq.agent";
	"OnDemand" = true;
	"LastExitStatus" = 19968;
	"Program" = "/opt/datadog-agent/bin/agent/agent";
	"ProgramArguments" = (
		"/opt/datadog-agent/bin/agent/agent";
		"run";
	);
};
```

**Describe what happened:**
I have created a custom check that needs `pyobjc-framework-Quartz` python module. I installed it with this command `/opt/datadog-agent/embedded/bin/pip3 install pyobjc-framework-Quartz`. After I tested with the following command: `datadog-agent check sleep_checker` it has been terminated with the following stacktrace:
```
* Python Check Loader: unable to import module 'sleep_checker': Traceback (most recent call last):
  File "/opt/datadog-agent/etc/checks.d/sleep_checker.py", line 8, in <module>
    import Quartz
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/Quartz/__init__.py", line 6, in <module>
    import AppKit
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/AppKit/__init__.py", line 10, in <module>
    import Foundation
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/CoreFoundation/__init__.py", line 9, in <module>
    import objc
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/objc/__init__.py", line 6, in <module>
    from . import _objc
ImportError: dlopen(/opt/datadog-agent/embedded/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/opt/datadog-agent/embedded/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so: code signature in (/opt/datadog-agent/embedded/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

**Describe what you expected:**

Check executed without error.

**Steps to reproduce the issue:**
Put the following script under `/opt/datadog-agent/etc/checks.d/`:
```
try:
    # first, try to import the base class from new versions of the Agent...
    from datadog_checks.base import AgentCheck
except ImportError:
    # ...if the above failed, the check is running in Agent version < 6.6.0
    from checks import AgentCheck

import Quartz

__version__ = "1.0.0"

class SleepChecker(AgentCheck):
    def check(self, instance):
        return
```

Put the config file under `/opt/datadog-agent/etc/conf.d/` with the following content:
```
init_config:

instances:
  - min_collection_interval: 15
```

**Additional environment details (Operating System, Cloud provider, etc):**
The agent is running on MacOS. system_profiler output:
```
Software:

    System Software Overview:

      System Version: macOS 10.15.7 (19H2)
      Kernel Version: Darwin 19.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: administrator’s Mac mini
      User Name: administrator (administrator)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 42 days 57 minutes
```

When I try the `import Quartz` from a simple script on the same host with the installed python it works as expected.
Can you guide me what could be the source of the problem and how can I solve it?

**Comment by lmesz-bitrise** [comment]
Can I get some help here?

**Comment by jacjtito** [comment]
Automatically closed due to inactivity.
