### ISSUE TITLE
Concurrent map read and map write in metadata/inventories

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#6958]
I saw Datadog Agent crash due to concurrent map read and map write in the `metadata/inventories` package. The error message logged before exit:
```
fatal error: concurrent map read and map write

goroutine 364 [running]:
runtime.throw(0x3a51db4, 0x21)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/runtime/panic.go:774 +0x72 fp=0xc000907288 sp=0xc000907258 pc=0
x149ef92
runtime.mapaccess2(0x35e1cc0, 0xc002bf19e0, 0xc048bf3c90, 0xc048bf3c90, 0xc01506a110)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/runtime/map.go:470 +0x278 fp=0xc0009072d0 sp=0xc000907288 pc=0x
147d9e8
reflect.mapaccess(0x35e1cc0, 0xc002bf19e0, 0xc048bf3c90, 0x3a31f92)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/runtime/map.go:1319 +0x3f fp=0xc000907308 sp=0xc0009072d0 pc=0x
147fcff
reflect.Value.MapIndex(0x35e1cc0, 0xc0480b0688, 0x195, 0x346d9e0, 0xc048bf3c90, 0x98, 0x357c740, 0xc048bf3d00, 0x94)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/reflect/value.go:1176 +0x16d fp=0xc000907380 sp=0xc000907308 pc
=0x153bbcd
encoding/json.mapEncoder.encode(0x3b170a8, 0xc00e142460, 0x35e1cc0, 0xc0480b0688, 0x195, 0x200100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:706 +0x302 fp=0xc0009074c8 sp=0xc000907
380 pc=0x1644ad2
encoding/json.mapEncoder.encode-fm(0xc00e142460, 0x35e1cc0, 0xc0480b0688, 0x195, 0xc0480b0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:682 +0x64 fp=0xc000907508 sp=0xc0009074
c8 pc=0x16505d4
encoding/json.ptrEncoder.encode(0xc0036b9e20, 0xc00e142460, 0x33d7860, 0xc0480b0690, 0x196, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:810 +0xb1 fp=0xc000907550 sp=0xc0009075
08 pc=0x1645a21
encoding/json.ptrEncoder.encode-fm(0xc00e142460, 0x33d7860, 0xc0480b0690, 0x196, 0x33d0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:805 +0x64 fp=0xc000907590 sp=0xc0009075
50 pc=0x1650754
encoding/json.arrayEncoder.encode(0xc0036b9e40, 0xc00e142460, 0x33d8be0, 0xc048729d80, 0x97, 0xc048720100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:791 +0xd6 fp=0xc0009075e8 sp=0xc0009075
90 pc=0x1645846
encoding/json.arrayEncoder.encode-fm(0xc00e142460, 0x33d8be0, 0xc048729d80, 0x97, 0xc048ca0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:784 +0x64 fp=0xc000907628 sp=0xc0009075
e8 pc=0x16506d4
encoding/json.sliceEncoder.encode(0xc0036b9e60, 0xc00e142460, 0x33d8be0, 0xc048729d80, 0x97, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:765 +0x8f fp=0xc000907670 sp=0xc0009076
28 pc=0x16454af
encoding/json.sliceEncoder.encode-fm(0xc00e142460, 0x33d8be0, 0xc048729d80, 0x97, 0xc048bf0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:760 +0x64 fp=0xc0009076b0 sp=0xc0009076
70 pc=0x1650654
encoding/json.mapEncoder.encode(0xc0036b9e70, 0xc00e142460, 0x35eeb60, 0xc0480b05a0, 0x195, 0xc015060100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:706 +0x351 fp=0xc0009077f8 sp=0xc000907
6b0 pc=0x1644b21
encoding/json.mapEncoder.encode-fm(0xc00e142460, 0x35eeb60, 0xc0480b05a0, 0x195, 0xc0480b0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:682 +0x64 fp=0xc000907838 sp=0xc0009077
f8 pc=0x16505d4
encoding/json.ptrEncoder.encode(0xc0036b9e90, 0xc00e142460, 0x34149a0, 0xc048ca7818, 0x196, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:810 +0xb1 fp=0xc000907880 sp=0xc0009078
38 pc=0x1645a21
encoding/json.ptrEncoder.encode-fm(0xc00e142460, 0x34149a0, 0xc048ca7818, 0x196, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:805 +0x64 fp=0xc0009078c0 sp=0xc0009078
80 pc=0x1650754
encoding/json.structEncoder.encode(0xc0005a0480, 0x4, 0x4, 0xc00378a960, 0xc00e142460, 0x37c5f60, 0xc048ca7800, 0x199, 0x1640100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:664 +0x306 fp=0xc000907960 sp=0xc0009078c0 pc=0x1644586
encoding/json.structEncoder.encode-fm(0xc00e142460, 0x37c5f60, 0xc048ca7800, 0x199, 0xc048ca0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:635 +0x7f fp=0xc0009079b8 sp=0xc000907960 pc=0x165054f
encoding/json.ptrEncoder.encode(0xc00378a990, 0xc00e142460, 0x33d6860, 0xc048ca7800, 0x16, 0x33d0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:810 +0xb1 fp=0xc000907a00 sp=0xc0009079b8 pc=0x1645a21
encoding/json.ptrEncoder.encode-fm(0xc00e142460, 0x33d6860, 0xc048ca7800, 0x16, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:805 +0x64 fp=0xc000907a40 sp=0xc000907a00 pc=0x1650754
encoding/json.arrayEncoder.encode(0xc0036b9e40, 0xc00e142460, 0x33d8be0, 0xc048729d80, 0x97, 0xc048720100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:791 +0xd6 fp=0xc0009075e8 sp=0xc0009075
90 pc=0x1645846
encoding/json.arrayEncoder.encode-fm(0xc00e142460, 0x33d8be0, 0xc048729d80, 0x97, 0xc048ca0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:784 +0x64 fp=0xc000907628 sp=0xc0009075
e8 pc=0x16506d4
encoding/json.sliceEncoder.encode(0xc0036b9e60, 0xc00e142460, 0x33d8be0, 0xc048729d80, 0x97, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:765 +0x8f fp=0xc000907670 sp=0xc0009076
28 pc=0x16454af
encoding/json.sliceEncoder.encode-fm(0xc00e142460, 0x33d8be0, 0xc048729d80, 0x97, 0xc048bf0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:760 +0x64 fp=0xc0009076b0 sp=0xc0009076
70 pc=0x1650654
encoding/json.mapEncoder.encode(0xc0036b9e70, 0xc00e142460, 0x35eeb60, 0xc0480b05a0, 0x195, 0xc015060100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:706 +0x351 fp=0xc0009077f8 sp=0xc000907
6b0 pc=0x1644b21
encoding/json.mapEncoder.encode-fm(0xc00e142460, 0x35eeb60, 0xc0480b05a0, 0x195, 0xc0480b0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:682 +0x64 fp=0xc000907838 sp=0xc0009077
f8 pc=0x16505d4
encoding/json.ptrEncoder.encode(0xc0036b9e90, 0xc00e142460, 0x34149a0, 0xc048ca7818, 0x196, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:810 +0xb1 fp=0xc000907880 sp=0xc0009078
38 pc=0x1645a21
encoding/json.ptrEncoder.encode-fm(0xc00e142460, 0x34149a0, 0xc048ca7818, 0x196, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:805 +0x64 fp=0xc0009078c0 sp=0xc0009078
80 pc=0x1650754
encoding/json.structEncoder.encode(0xc0005a0480, 0x4, 0x4, 0xc00378a960, 0xc00e142460, 0x37c5f60, 0xc048ca7800, 0x199, 0x1640100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:664 +0x306 fp=0xc000907960 sp=0xc0009078c0 pc=0x1644586
encoding/json.structEncoder.encode-fm(0xc00e142460, 0x37c5f60, 0xc048ca7800, 0x199, 0xc048ca0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:635 +0x7f fp=0xc0009079b8 sp=0xc000907960 pc=0x165054f
encoding/json.ptrEncoder.encode(0xc00378a990, 0xc00e142460, 0x33d6860, 0xc048ca7800, 0x16, 0x33d0100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:810 +0xb1 fp=0xc000907a00 sp=0xc0009079b8 pc=0x1645a21
encoding/json.ptrEncoder.encode-fm(0xc00e142460, 0x33d6860, 0xc048ca7800, 0x16, 0x100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:805 +0x64 fp=0xc000907a40 sp=0xc000907a00 pc=0x1650754
encoding/json.(*encodeState).reflectValue(0xc00e142460, 0x33d6860, 0xc048ca7800, 0x16, 0x3990100)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:337 +0x82 fp=0xc000907a78 sp=0xc000907a40 pc=0x1641dc2
encoding/json.(*encodeState).marshal(0xc00e142460, 0x33d6860, 0xc048ca7800, 0x100, 0x0, 0x0)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:309 +0x10b fp=0xc000907af8 sp=0xc000907a78 pc=0x164186b
encoding/json.Marshal(0x33d6860, 0xc048ca7800, 0x0, 0x0, 0x0, 0x8, 0x3e839f8)
        /root/.gimme/versions/go1.13.11.linux.amd64/src/encoding/json/encode.go:161 +0x52 fp=0xc000907b70 sp=0xc000907af8 pc=0x1640e42
github.com/DataDog/datadog-agent/pkg/metadata/inventories.(*Payload).MarshalJSON(0xc048ca7800, 0xc009b77800, 0x203012, 0x203012, 0x203012, 0x1490fe5)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/inventories/payload.go:37 +0x37 fp=0xc000907bb8 sp=0xc000907b70 pc=0x2329987
github.com/DataDog/datadog-agent/pkg/serializer/split.marshal(0x3f53140, 0xc048ca7800, 0x0, 0x147bd74, 0xc048729d00, 0x20, 0x8, 0x33eb120)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/split/split.go:183 +0xe9 fp=0xc000907bf8 sp=0xc000907bb8 pc=0x2b79e59
github.com/DataDog/datadog-agent/pkg/serializer/split.serializeMarshaller(0x3f53140, 0xc048ca7800, 0xc0023b9c01, 0x0, 0xc0023b9cb8, 0x14dd508, 0xc0023b9cd8, 0x147c3f8, 0x20, 0x33eb120, ...)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/split/split.go:159 +0x4c fp=0xc000907c78 sp=0xc000907bf8 pc=0x2b79bfc
github.com/DataDog/datadog-agent/pkg/serializer/split.CheckSizeAndSerialize(0x3f53140, 0xc048ca7800, 0xc048ca7801, 0x0, 0xc0023b9cc8, 0x23297f8, 0x0, 0x0, 0xc0023b9ec8, 0x580df70, ...)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/split/split.go:60 +0x52 fp=0xc000907ce8 sp=0xc000907c78 pc=0x2b78a12
github.com/DataDog/datadog-agent/pkg/serializer.(*Serializer).SendMetadata(0xc0018effe0, 0x3f53140, 0xc048ca7800, 0xc0019104c0, 0xc048ca7800)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/serializer.go:331 +0x78 fp=0xc000907da0 sp=0xc000907ce8 pc=0x2be2ef8
github.com/DataDog/datadog-agent/pkg/metadata.inventoriesCollector.Send(0x3ef32c0, 0xc000d5b7a0, 0x3ef3300, 0xc0019104c0, 0xc00152d530, 0xc0018effe0, 0xc0023b9e60, 0x14f8561)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/inventories_collector.go:42 +0x98 fp=0xc000907df8 sp=0xc000907da0 pc=0x2cc84d8
github.com/DataDog/datadog-agent/pkg/metadata.(*inventoriesCollector).Send(0xc00240a300, 0xc0018effe0, 0x0, 0x2)
        <autogenerated>:1 +0x81 fp=0xc000907e70 sp=0xc000907df8 pc=0x2cca181
github.com/DataDog/datadog-agent/pkg/metadata.(*Scheduler).AddCollector.func1(0xc00152d530, 0xc000a723a0, 0x8bb2c97000, 0x3ef70c0, 0xc00240a300, 0x3a163aa, 0xb)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/scheduler.go:100 +0x1c7 fp=0xc000907fa8 sp=0xc000907e70 pc=0x2cc9977
runtime.goexit()
        /root/.gimme/versions/go1.13.11.linux.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000907fb0 sp=0xc000907fa8 pc=0x14ceeb1
created by github.com/DataDog/datadog-agent/pkg/metadata.(*Scheduler).AddCollector
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/scheduler.go:87 +0x1f5
```

I'll provide a pull request shortly.

**Comment by deadok22** [comment]
Here's another example:
```
fatal error: concurrent map iteration and map write

goroutine 386 [running]:
runtime.throw(0x3931f3c, 0x26)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/runtime/panic.go:1116 +0x72 fp=0xc0013110b8 sp=0xc001311088 pc=0
x13f61b2
runtime.mapiternext(0xc00b197980)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/runtime/map.go:853 +0x552 fp=0xc001311138 sp=0xc0013110b8 pc=0x1
3d0f12
reflect.mapiternext(0xc00b197980)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/runtime/map.go:1337 +0x2b fp=0xc001311150 sp=0xc001311138 pc=0x1
3d1e8b
reflect.Value.MapKeys(0x3503a60, 0xc003d78240, 0x195, 0x0, 0xc004e20100, 0x98)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/reflect/value.go:1211 +0x10a fp=0xc0013111e0 sp=0xc001311150 pc=
0x149222a
encoding/json.mapEncoder.encode(0x39eae10, 0xc00da7ea80, 0x3503a60, 0xc003d78240, 0x195, 0x13c0100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:785 +0xff fp=0xc001311358 sp=0xc0013111e
0 pc=0x159626f
encoding/json.mapEncoder.encode-fm(0xc00da7ea80, 0x3503a60, 0xc003d78240, 0x195, 0xc003d70100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:777 +0x64 fp=0xc001311398 sp=0xc00131135
8 pc=0x15a2464
encoding/json.ptrEncoder.encode(0xc00075c680, 0xc00da7ea80, 0x32ca280, 0xc004e09a68, 0x196, 0x100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:915 +0x116 fp=0xc001311458 sp=0xc001311398 pc=0x1597456
encoding/json.ptrEncoder.encode-fm(0xc00da7ea80, 0x32ca280, 0xc004e09a68, 0x196, 0x32c0100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:900 +0x64 fp=0xc001311498 sp=0xc001311458 pc=0x15a25e4
encoding/json.arrayEncoder.encode(0xc00075c6a0, 0xc00da7ea80, 0x32cb300, 0xc00bc347a0, 0x97, 0xc00bc30100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:886 +0xd6 fp=0xc0013114f0 sp=0xc001311498 pc=0x1597216
encoding/json.arrayEncoder.encode-fm(0xc00da7ea80, 0x32cb300, 0xc00bc347a0, 0x97, 0xc0020b0100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:879 +0x64 fp=0xc001311530 sp=0xc0013114f0 pc=0x15a2564
encoding/json.sliceEncoder.encode(0xc00075c6c0, 0xc00da7ea80, 0x32cb300, 0xc00bc347a0, 0x97, 0x100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:860 +0x8f fp=0xc001311578 sp=0xc001311530 pc=0x1596e9f
encoding/json.sliceEncoder.encode-fm(0xc00da7ea80, 0x32cb300, 0xc00bc347a0, 0x97, 0xc004e00100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:855 +0x64 fp=0xc0013115b8 sp=0xc001311578 pc=0x15a24e4
encoding/json.mapEncoder.encode(0xc00075c6d0, 0xc00da7ea80, 0x3518e60, 0xc003d78010, 0x195, 0xc00da70100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:801 +0x354 fp=0xc001311730 sp=0xc0013115b8 pc=0x15964c4
encoding/json.mapEncoder.encode-fm(0xc00da7ea80, 0x3518e60, 0xc003d78010, 0x195, 0xc003d70100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:777 +0x64 fp=0xc001311770 sp=0xc001311730 pc=0x15a2464
encoding/json.ptrEncoder.encode(0xc00075c6f0, 0xc00da7ea80, 0x3300480, 0xc004e0bea8, 0x196, 0x100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:915 +0x116 fp=0xc001311830 sp=0xc001311770 pc=0x1597456
encoding/json.ptrEncoder.encode-fm(0xc00da7ea80, 0x3300480, 0xc004e0bea8, 0x196, 0x100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:900 +0x64 fp=0xc001311870 sp=0xc001311830 pc=0x15a25e4
encoding/json.structEncoder.encode(0xc000500b40, 0x4, 0x4, 0xc00147cff0, 0xc00da7ea80, 0x36b1d80, 0xc004e0be90, 0x199, 0x3480100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:759 +0x2bb fp=0xc001311910 sp=0xc001311870 pc=0x1595efb
encoding/json.structEncoder.encode-fm(0xc00da7ea80, 0x36b1d80, 0xc004e0be90, 0x199, 0xc004e00100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:730 +0x7f fp=0xc001311968 sp=0xc001311910 pc=0x15a23df
encoding/json.ptrEncoder.encode(0xc00147d020, 0xc00da7ea80, 0x32c9380, 0xc004e0be90, 0x16, 0x32c0100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:915 +0x116 fp=0xc001311a28 sp=0xc001311968 pc=0x1597456
encoding/json.ptrEncoder.encode-fm(0xc00da7ea80, 0x32c9380, 0xc004e0be90, 0x16, 0x56a0100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:900 +0x64 fp=0xc001311a68 sp=0xc001311a28 pc=0x15a25e4
encoding/json.(*encodeState).reflectValue(0xc00da7ea80, 0x32c9380, 0xc004e0be90, 0x16, 0xc00e4c0100)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:358 +0x82 fp=0xc001311aa0 sp=0xc001311a68 pc=0x15935f2
encoding/json.(*encodeState).marshal(0xc00da7ea80, 0x32c9380, 0xc004e0be90, 0x100, 0x0, 0x0)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:330 +0xf0 fp=0xc001311b00 sp=0xc001311aa0 pc=0x1593110
encoding/json.Marshal(0x32c9380, 0xc004e0be90, 0x38da0d5, 0x4, 0xc0003194a0, 0x8, 0x0)
        /root/.gimme/versions/go1.14.7.linux.amd64/src/encoding/json/encode.go:161 +0x52 fp=0xc001311b78 sp=0xc001311b00 pc=0x15925f2
github.com/DataDog/datadog-agent/pkg/metadata/inventories.(*Payload).MarshalJSON(0xc004e0be90, 0x0, 0x203002, 0x203002, 0x203002, 0x0)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/inventories/payload.go:37 +0x37 fp=0xc001311bc0 sp=0xc001311b78 pc=0x1f596b7
github.com/DataDog/datadog-agent/pkg/serializer/split.marshal(0x3e29220, 0xc004e0be90, 0x0, 0x13cdcc6, 0xc00bc34460, 0x20, 0x18, 0x32db580)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/split/split.go:189 +0xe9 fp=0xc001311c00 sp=0xc001311bc0 pc=0x2a64839
github.com/DataDog/datadog-agent/pkg/serializer/split.serializeMarshaller(0x3e29220, 0xc004e0be90, 0x1, 0x0, 0x0, 0x0, 0xc00e4c0ce0, 0x13ce538, 0x20, 0x32db580, ...)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/split/split.go:162 +0x4c fp=0xc001311c80 sp=0xc001311c00 pc=0x2a645dc
github.com/DataDog/datadog-agent/pkg/serializer/split.CheckSizeAndSerialize(0x3e29220, 0xc004e0be90, 0xc00e4c0d01, 0x0, 0x56e2940, 0xb, 0x3dcc560, 0xc0012a4000, 0x3dcc5a0, 0xc000a87380, ...)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/split/split.go:61 +0x52 fp=0xc001311cf0 sp=0xc001311c80 pc=0x2a63412
github.com/DataDog/datadog-agent/pkg/serializer.(*Serializer).sendMetadata(0xc000dacd60, 0x3e29220, 0xc004e0be90, 0x0, 0xc004e0be90, 0x0)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/serializer.go:341 +0x78 fp=0xc001311dc8 sp=0xc001311cf0 pc=0x2acca78
github.com/DataDog/datadog-agent/pkg/serializer.(*Serializer).SendMetadata(...)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/serializer/serializer.go:332
github.com/DataDog/datadog-agent/pkg/metadata.inventoriesCollector.Send(0x3dcc560, 0xc0012a4000, 0x3dcc5a0, 0xc000a87380, 0xc000de9b30, 0xc000dacd60, 0xc00e4c0e88, 0x1450ded)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/inventories_collector.go:42 +0xa1 fp=0xc001311e20 sp=0xc001311dc8 pc=0x2b85bf1
github.com/DataDog/datadog-agent/pkg/metadata.(*inventoriesCollector).Send(0xc00147c060, 0xc000dacd60, 0x0, 0x2)
        <autogenerated>:1 +0x81 fp=0xc001311e98 sp=0xc001311e20 pc=0x2b87761
github.com/DataDog/datadog-agent/pkg/metadata.(*Scheduler).AddCollector.func1(0xc000de9b30, 0xc001402c00, 0x8bb2c97000, 0x3dd02a0, 0xc00147c060, 0x38e65cf, 0xb)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/scheduler.go:100 +0x1c1 fp=0xc001311fa8 sp=0xc001311e98 pc=0x2b87081
runtime.goexit()
        /root/.gimme/versions/go1.14.7.linux.amd64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc001311fb0 sp=0xc001311fa8 pc=0x1428ff1
created by github.com/DataDog/datadog-agent/pkg/metadata.(*Scheduler).AddCollector
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/metadata/scheduler.go:87 +0x1f5

```
