### ISSUE TITLE
Istio: ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by huy-hoang-mox** [DataDog/datadog-agent#8251]
**Output of the info page (if this is a bug)**
```
 Instance ID: istio:37327416c35c075d [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/istio.d/auto_conf.yaml
      Total Runs: 30
      Metric Samples: Last Run: 204, Total: 6,032
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 18.997s
      Last Execution Date : 2021-05-27 03:25:15.000000 UTC
      Last Successful Execution Date : 2021-05-27 03:01:15.000000 UTC
      Error: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 696, in _update_chunk_length
          self.chunk_left = int(line, 16)
      ValueError: invalid literal for int() with base 16: b''

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 436, in _error_catcher
          yield
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 763, in read_chunked
          self._update_chunk_length()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 700, in _update_chunk_length
          raise httplib.IncompleteRead(line)
      http.client.IncompleteRead: IncompleteRead(0 bytes read)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py", line 750, in generate
          for chunk in self.raw.stream(chunk_size, decode_content=True):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 571, in stream
          for line in self.read_chunked(amt, decode_content=decode_content):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 792, in read_chunked
          self._original_response.close()
        File "/opt/datadog-agent/embedded/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 454, in _error_catcher
          raise ProtocolError("Connection broken: %r" % e, e)
      urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 876, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/istio/legacy_1_4.py", line 48, in check
          self.process(istio_mesh_config)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 521, in process
          for metric in self.scrape_metrics(scraper_config):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 492, in scrape_metrics
          for metric in self.parse_metric_family(response, scraper_config):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 416, in parse_metric_family
          for metric in text_fd_to_metric_families(input_gen):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/libs/prometheus.py", line 33, in text_fd_to_metric_families
          for line in fd:
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py", line 794, in iter_lines
          for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/utils.py", line 505, in stream_decode_response_unicode
          for chunk in iterator:
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py", line 753, in generate
          raise ChunkedEncodingError(e)
      requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Describe what happened:**
Run agent status command to check, I got bunch of those errors when checking istio

**Describe what you expected:**
Seem like we need to handle this: `ValueError: invalid literal for int() with base 16: b''

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
EKS: 1.16.15
datadog agent version: 7.25.1-jmx

**Comment by huy-hoang-mox** [comment]
Same thing for openmetrics:
```
 openmetrics (1.11.0)
    --------------------
      Instance ID: openmetrics:envoy:11ca32ca15f26f28 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/openmetrics.yaml
      Total Runs: 30
      Metric Samples: Last Run: 111, Total: 3,330
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 30
      Average Execution Time : 13.566s
      Last Execution Date : 2021-05-27 03:26:09.000000 UTC
      Last Successful Execution Date : 2021-05-27 03:26:09.000000 UTC

      Instance ID: openmetrics:envoy:13c5f5fe8d5348f6 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/openmetrics.yaml
      Total Runs: 30
      Metric Samples: Last Run: 249, Total: 7,450
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 30
      Average Execution Time : 18.741s
      Last Execution Date : 2021-05-27 03:25:33.000000 UTC
      Last Successful Execution Date : Never
      Error: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 696, in _update_chunk_length
          self.chunk_left = int(line, 16)
      ValueError: invalid literal for int() with base 16: b''

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 436, in _error_catcher
          yield
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 763, in read_chunked
          self._update_chunk_length()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 700, in _update_chunk_length
          raise httplib.IncompleteRead(line)
      http.client.IncompleteRead: IncompleteRead(0 bytes read)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py", line 750, in generate
          for chunk in self.raw.stream(chunk_size, decode_content=True):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 571, in stream
          for line in self.read_chunked(amt, decode_content=decode_content):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 792, in read_chunked
          self._original_response.close()
        File "/opt/datadog-agent/embedded/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/response.py", line 454, in _error_catcher
          raise ProtocolError("Connection broken: %r" % e, e)
      urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 876, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/base_check.py", line 112, in check
          self.process(scraper_config)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 521, in process
          for metric in self.scrape_metrics(scraper_config):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 492, in scrape_metrics
          for metric in self.parse_metric_family(response, scraper_config):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/mixins.py", line 416, in parse_metric_family
          for metric in text_fd_to_metric_families(input_gen):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/libs/prometheus.py", line 33, in text_fd_to_metric_families
          for line in fd:
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py", line 794, in iter_lines
          for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/utils.py", line 505, in stream_decode_response_unicode
          for chunk in iterator:
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py", line 753, in generate
          raise ChunkedEncodingError(e)
      requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by kirecek** [comment]
Any chance you have figured out the root cause?

**Comment by kirecek** [comment]
Any chance you have figured out the root cause?

We are occasionally also experiencing these issues, however, proxy seems to be healthy. Therefore the problem is IMHO related to how DD treats connection to DD proxy?

Besides the error, we already noticed doubled CPU usage of agents when integration is in error state.

**Comment by ndolya** [comment]
Observing the same issue with 7.30.1 agent and Istio 1.9.2.
