### ISSUE TITLE
Snowflake integration broken

### ISSUE THREAD

**Issue by YonatanKiron** [DataDog/datadog-agent#8997]
**Output of the info page (if this is a bug)**
```
    kubelet (7.0.0)                                                                                                                                                                                  
    ---------------
      Instance ID: kubelet:5bbc63f3938c02f4 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
      Total Runs: 1
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1
      Average Execution Time : 300ms
      Last Execution Date : 2021-08-26 14:43:10 UTC (1629988990000)
      Last Successful Execution Date : Never
      Error: 'SSLSocket' object has no attribute 'connection'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1006, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kubelet/kubelet.py", line 336, in check
          self._report_node_metrics(self.instance_tags)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kubelet/kubelet.py", line 382, in _report_node_metrics
          node_resp = self._retrieve_node_spec()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kubelet/kubelet.py", line 365, in _retrieve_node_spec
          node_resp = self.perform_kubelet_query(self.node_spec_url)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/kubelet_base/base.py", line 31, in perform_kubelet_query
          return self.http.get(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/http.py", line 304, in get
          return self._request('get', url, options)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/http.py", line 368, in _request
          response = self.make_request_aia_chasing(request_method, method, url, new_options, persist)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/http.py", line 373, in make_request_aia_chasing
          response = request_method(url, **new_options)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/api.py", line 76, in get
          return request('get', url, params=params, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/api.py", line 61, in request
          return session.request(method=method, url=url, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
          resp = self.send(prep, **send_kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
          r = adapter.send(request, **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
          resp = conn.urlopen(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
          httplib_response = self._make_request(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
          self._validate_conn(conn)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
          conn.connect()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
          self.sock = ssl_wrap_socket(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/snowflake/connector/ssl_wrap_socket.py", line 418, in ssl_wrap_socket_with_ocsp
          ).validate(server_hostname, ret.connection)
      AttributeError: 'SSLSocket' object has no attribute 'connection'
```

**Describe what happened:**
We are using agent version v7.30.0 over the K8s cluster (Using the official Helm chart)
After searching a bit over the internet we have found out that is known issue https://github.com/snowflakedb/snowflake-connector-python/issues/335

* After downgrading to v7.29.0 it solved the issue*

**Describe what you expected:**
Snowflake integration to work

**Steps to reproduce the issue:**
Use v7.30.0 agent version and setup snowflake integration

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by olivielpeau** [comment]
Hi @YonatanKiron, thanks for the details here. As mentioned in https://github.com/DataDog/datadog-agent/issues/8895 this issue has been fixed in v7.30.1, therefore upgrading your Agent should fix this.

I'll go ahead and close this issue, but please comment here if you have any questions, thanks!
