### ISSUE TITLE
Serverless: "panic: runtime error: index out of range [23] with length 5"

### ISSUE THREAD

**Issue by skaggmannen** [DataDog/datadog-agent#9916]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
We are using the setup described [here](https://docs.datadoghq.com/serverless/installation/go) for collecting traces for AWS Lambdas using the `go1.x` runtime.

When checking the logs after a request returned "502 Bad Gateway" I found that the Lambda invocaton had failed with the following logs:

```
2021-11-15 16:34:35 UTC SAGENT INFO [endpoint_version:v0.4] -> traces received: 0, traces filtered: 0, traces amount: 1 bytes, events extracted: 0, events sampled: 0
2021-11-15 16:34:35 UTC SAGENT INFO [lang:go lang_version:1.17.1 interpreter:gc-amd64-linux tracer_version:v1.30.0 endpoint_version:v0.4] -> traces received: 14, traces filtered: 0, traces amount: 9967 bytes, events extracted: 0, events sampled: 0
panic: runtime error: index out of range [23] with length 5

goroutine 129 [running]:
github.com/DataDog/datadog-agent/pkg/dogstatsd.(*batcher).appendSample(...)
/tmp/dd/datadog-agent/pkg/dogstatsd/batch.go:42
github.com/DataDog/datadog-agent/pkg/dogstatsd.(*Server).parsePackets(0xc0003e9400, 0xc0002b0540,
0xc0002de500, 0xc0000c5e00, 0x2, 0x20, 0xc0005a8000, 0x1, 0x400, 0xc0005a8000, ...)
/tmp/dd/datadog-agent/pkg/dogstatsd/server.go:551 +0xfbe
github.com/DataDog/datadog-agent/pkg/dogstatsd.(*worker).run(0xc000097980)
/tmp/dd/datadog-agent/pkg/dogstatsd/server_worker.go:51 +0x165
created by github.com/DataDog/datadog-agent/pkg/dogstatsd.(*Server).handleMessages
/tmp/dd/datadog-agent/pkg/dogstatsd/server.go:407 +0x119
END RequestId: ec5ba44b-d80c-4ca3-81f2-930a60fd85de
REPORT RequestId: ec5ba44b-d80c-4ca3-81f2-930a60fd85de Duration: 2122.30 ms Billed Duration: 2123 ms Memory Size: 256 MB Max Memory Used: 133 MB  XRAY TraceId: 1-61928c1a-25afaafc266deabb29a665b0 SegmentId: 6ceb1a16132427f1 Sampled: true
RequestId: ec5ba44b-d80c-4ca3-81f2-930a60fd85de Error: exit status 2 Extension.Crash
START RequestId: a52b4da3-d21a-4e7b-b5b3-2f9a82d197da Version: 17
LOGS Name: cloudwatch_lambda_agent State: Already subscribed Types: [platform]
2021-11-15 16:34:41 UTC SAGENT INFO Retry queue storage on disk is disabled
2021-11-15 16:34:41 UTC SAGENT INFO dogstatsd-udp: starting to listen on 127.0.0.1:8125
2021-11-15 16:34:41 UTC SAGENT WARN Error loading config: open /var/task/datadog.yaml: no such file or directory
2021-11-15 16:34:41 UTC SAGENT INFO Features detected from environment:
LOGS Name: datadog-agent State: Already subscribed Types: [platform,function,extension]
2021-11-15 16:34:41 UTC SAGENT INFO Starting a serverless logs-agent...
2021-11-15 16:34:41 UTC SAGENT INFO logs-agent started
2021-11-15 16:34:41 UTC SAGENT INFO Listening for traces at http://localhost:8126
```

We are not doing any custom tracing, only wrapping the Lambda function handler using `ddlambda.WrapFunction(...)`.

**Describe what you expected:**
I obiously expected it to not panic 😅 

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
Cloud provider: AWS
Datadog library version:  `github.com/DataDog/datadog-lambda-go v1.3.0`

SAM template excerpt:
```yaml
Globals:
  Function:
    Tracing: Active
    Runtime: provided.al2
    Handler: bootstrap
    CodeUri: ../../
    Timeout: 15
    MemorySize: 256
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
      # Datadog Lambda Extension: https://docs.datadoghq.com/serverless/installation/go/
      - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension:13
    Environment:
      Variables:
        DD_API_KEY: !Sub "{{resolve:secretsmanager:${DatadogSecretId}:SecretString:apiKey}}"
        DD_TRACE_ENABLED: true
        DD_ENV: !Ref Shard
        DD_SERVICE: dm-encoder
        DD_LOG_LEVEL: info
        DD_SITE: datadoghq.eu
```

**Comment by nrgraham23** [comment]
We just noticed this too.  +1

**Comment by piradata** [comment]
same error here on agent version 7.57.2

**Comment by jacjtito** [comment]
Automatically closed due to inactivity.
