### ISSUE TITLE
sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by diman-neosec** [DataDog/datadog-agent#9987]
Using DD Go extension layer arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:13.

Getting the following error:

```
http: panic serving: 
negative WaitGroup counter
goroutine 4863 [running]:
net/http.(*conn).serve.func1(0xc0000b6b40)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x11f0ce0, 0x15e6ad0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
sync.(*WaitGroup).Add(0xc00012e8c0, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x147
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
github.com/DataDog/datadog-agent/pkg/serverless/daemon.(*Daemon).FinishInvocation.func1()
	/tmp/dd/datadog-agent/pkg/serverless/daemon/daemon.go:339 +0x37
sync.(*Once).doSlow(0xc0000a6338, 0xc0009c8a78)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/DataDog/datadog-agent/pkg/serverless/daemon.(*Daemon).FinishInvocation(0xc0000a62d0)
	/tmp/dd/datadog-agent/pkg/serverless/daemon/daemon.go:338 +0x65
github.com/DataDog/datadog-agent/pkg/serverless/daemon.(*Flush).ServeHTTP(0xc000010ce0, 0x161ad98, 0xc0000e40e0, 0xc000180100)
	/tmp/dd/datadog-agent/pkg/serverless/daemon/daemon.go:148 +0x3a5
net/http.(*ServeMux).ServeHTTP(0xc0001726c0, 0x161ad98, 0xc0000e40e0, 0xc000180100)
	/usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00017c1c0, 0x161ad98, 0xc0000e40e0, 0xc000180100)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0000b6b40, 0x161edd8, 0xc0002f6100)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by maxday** [comment]
Thanks for reaching out!
I have a couple of questions to better understand the issue :
- Which runtime are you using with the extension?
- Does it happen 100% of the time or is this behaviour non deterministic over many invocations?

**Comment by diman-neosec** [comment]
Hi, we are using go1.x runtime and it's happening every couple of hours consistently.
We saw this post which is saying it's advices to update to linux2: https://docs.datadoghq.com/serverless/installation/go/

**Comment by diman-neosec** [comment]
If seems that there is no actual need for the layer to be added in order for metrics to work.
Closing the issue
